In [1]:
!pip install -U googlemaps
# !pip install geopandas

Collecting googlemaps
  Downloading https://files.pythonhosted.org/packages/cb/87/5cbe65cd19defe67472db7afd84963a77fbbbe4a764320a67d4a64282b61/googlemaps-4.4.1.tar.gz
Requirement already satisfied, skipping upgrade: requests<3.0,>=2.20.0 in d:\python\lib\site-packages (from googlemaps) (2.22.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\python\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.2)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in d:\python\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in d:\python\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2019.6.16)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in d:\python\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py): started
  Building wheel for googlemaps (setup.py): finished with status 'done'
  Stored in directory: C:\Users\PC\AppData\Local\pip\Cache\wheels\5c\ec\b9\9d0c26b80d7dcf16496c82e8108c93186c6d4df097a41bba4f
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.4.1

In [2]:
import googlemaps
import re
import matplotlib.pyplot as plt
import os

In [3]:
gmaps = googlemaps.Client(key='AIzaSyA88VXLRMHW7vauq-BzwFVGWaMvsUaNQyA')

In [4]:
import math

def distance(origin, destination):
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371 # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d

In [5]:
import pandas as pd

In [6]:
df1 = pd.read_csv("E:\\MCM\\Practicum docs\\Datasets\\final\\daftrent_May31st.csv")

In [7]:
df1

,Location,Area,Area code,Price(in Euros),House_type,Beds,Bathroom,Area_code,latitude,longitude,Entered,Views
0,Parnell Square West|| Dublin 1,Dublin 1,D01,2350,Apartment to Rent,2,2,D00,53.352069,-6.264353,30.05.2020,261
1,North Frederick Street|| Dublin 1,Dublin 1,D01,1400,Apartment to Rent,1,1,D01,53.355038,-6.264109,30.05.2020,3746
2,Apartment 10 Behan Sq|| 14 Russell St|| Dublin 1,Dublin 1,D01,2200,Apartment to Rent,2,1,D01,53.358795,-6.254438,30.05.2020,188
3,O'Connell Street Upper 1 Bed|| Dublin 1,Dublin 1,D01,1500,Apartment to Rent,1,1,D00,53.352384,-6.261213,30.05.2020,7508
4,The Asgard|| Custom House Harbour|| Dublin 1,Dublin 1,D01,2000,Apartment to Rent,2,1,D00,53.350669,-6.247787,30.05.2020,1606
5,24/25 Hill Street|| Dublin 1,Dublin 1,D01,1750,Apartment to Rent,1,1,D00,53.355594,-6.260537,29.05.2020,105
6,36A Fitzgibbon Street|| Dublin 1,Dublin 1,D01,1650,Apartment to Rent,1,1,D00,53.357716,-6.256452,29.05.2020,110
7,Riverstown House|| Spencer Dock|| North Wall Q...,Dublin 1,D01,2050,Apartment to Rent,2,1,D00,53.350152,-6.238196,29.05.2020,266
8,51 Cloncurry House|| Spencer Dock|| Dublin 1,Dublin 1,D01,2250,Apartment to Rent,2,2,D01,53.349365,-6.239463,29.05.2020,324
9,The Courtyard|| Hill Street|| Dublin 1,Dublin 1,D01,1650,Apartment to Rent,1,1,D00,53.354196,-6.259163,29.05.2020,2008
10,Bachelors Walk Apartments|| Dublin 1,Dublin 1,D01,1500,Apartment to Rent,1,1,D00,53.347181,-6.262330,29.05.2020,2139
11,Caple Street|| Dublin 1,Dublin 1,D01,2000,Apartment to Rent,2,2,D00,53.350657,-6.269917,29.05.2020,999
12,Greeg court Parnell street|| Dublin 1,Dublin 1,D01,2400,Apartment to Rent,2,2,D00,53.350783,-6.264322,29.05.2020,509
13,75 Dorset Street Upper|| Dublin 1,Dublin 1,D01,1450,Apartment to Rent,1,1,D00,53.357261,-6.264369,28.05.2020,3385
14,St josephs parade|| off Dorset st|| Dublin 1,Dublin 1,D01,3300,House to Rent,4,2,D00,53.357635,-6.267159,27.05.2020,581
15,58 Middle Abbey St|| Dublin 1,Dublin 1,D01,2800,Apartment to Rent,3,2,D00,53.348010,-6.261929,27.05.2020,128
16,Church Place|| Dublin 1,Dublin 1,D01,1792,House to Rent,2,1,D00,53.351368,-6.235093,27.05.2020,2493
17,Block D|| Castleforbes Sq|| IFSC|| Dublin 1,Dublin 1,D01,1750,Apartment to Rent,1,1,D00,53.349363,-6.230894,27.05.2020,620
18,29 Dorset street lower|| Dublin 1,Dublin 1,D01,2000,Apartment to Rent,2,1,D00,53.359057,-6.261560,27.05.2020,206
19,Block K Castleforbes Square|| IFSC|| Dublin 1,Dublin 1,D01,2780,Apartment to Rent,3,2,D00,53.348672,-6.230130,26.05.2020,1029
20,Slaney House Custom House Square|| IFSC|| Dubl...,Dublin 1,D01,2200,Apartment to Rent,2,2,D00,53.349461,-6.241044,26.05.2020,472
21,Gardiner Place|| Dublin 1,Dublin 1,D01,1750,Apartment to Rent,2,1,D00,53.355989,-6.260954,25.05.2020,2512
22,Spencer Dock|| Dublin 1,Dublin 1,D01,1900,Apartment to Rent,1,2,D01,53.349409,-6.238656,24.05.2020,437
23,138 Castleforbes Square|| Castleforbes Road|| ...,Dublin 1,D01,2600,Apartment to Rent,3,2,D01,53.349390,-6.231450,18.05.2020,687
24,109 parnell street|| Dublin 1,Dublin 1,D01,1800,Apartment to Rent,1,1,D01,53.354007,-6.257057,18.05.2020,952
25,The Penthouses at Custom House Square|| Dublin 1,Dublin 1,D01,3950,Apartment to Rent,3,2,D00,53.349296,-6.243453,31.05.2020,900
26,The Penthouses at Custom House Square|| Dublin 1,Dublin 1,D01,6429,Apartment to Rent,3,2,D00,53.349310,-6.243486,31.05.2020,252
27,1 Old Distillery Apartments|| Smithfield|| Dub...,Dublin 1,D01,2400,Apartment to Rent,3,2,D00,53.349084,-6.273264,31.05.2020,681
28,Kingscourt Parnell Street|| Dublin 1,Dublin 1,D01,2000,Apartment to Rent,2,1,D00,53.350598,-6.265687,31.05.2020,243
29,48 Pakenham House|| Spencer Dock|| IFSC|| Dubl...,Dublin 1,D01,2250,Apartment to Rent,2,2,D00,53.348863,-6.239513,31.05.2020,522
...,...,...,...,...,...,...,...,...,...,...,...,...
1844,Wolfe Tone Lofts|| Dublin 1,Dublin 1,D01,2017,Apartment to Rent,2,1,D00,53.349074,-6.267719,27.05.2020,113
1845,Castleforbes Square|| Dublin 1,Dublin 1,D01,2300,Apartment to Rent,2,1,D00,53.349293,-6.231892,31.05.2020,583
1846,Castleforbes Square|| IFSC|| Dublin 1,Dublin 1,D01,2100,Apartment to Rent,2,2,D00,53.349291,-6.231894,30.05.2020,185
1847,25 wolfe tone street|| Dublin 1,Dublin 1,D01,2036,Apartment to Rent,2,1,D00,53.349402,-6.267826,30.05.2020,386
1848,25 Wolfe Tone street|| Dublin 1,Dublin 1,D01,1500,Apartment to Rent,1,1,D00,53.349400,-6.267828,29.05.2020,675
1849,IFSC|| Dublin 1,Dublin 1,D01,3600,Apartment to Rent,2,1,D00,53.349596,-6.237633,27.05.2020,835
1850,IFSC|| Dublin 1,Dublin 1,D01,3600,Apartment to Rent,1,2,D00,53.349594,-6.237591,27.05.2020,571
1851,13 Custom Hall|| Block 1|| Deverell Place|| Du...,Dublin 1,D01,1550,Apartment to Rent,1,1,D01,53.351675,-6.255062,28.05.2020,620
1852,Custom Hall|| Gardiner Street|| D01 TW10|| Dub...,Dublin 1,D01,2250,Apartment to Rent,3,1,D00,53.351673,-6.255064,29.05.2020,1698
1853,10 Gardiner Place|| Dublin 1,Dublin 1,D01,2000,Apartment to Rent,2,1,D01,53.353753,-6.252957,28.05.2020,3816
1854,Jervis Place Apartments|| Dublin 1,Dublin 1,D01,1500,Apartment to Rent,1,1,D00,53.353753,-6.252957,25.05.2020,4421
1855,No. 30 Nelson Street|| Dublin 1,Dublin 1,D01,1300,Studio apartment to Rent,5,4,D00,53.353751,-6.252959,29.05.2020,4316
1856,22 Dunlin House|| Redcourt Oaks|| Seafield Roa...,Dublin 3,D03,1948,Apartment to Rent,3,2,D00,53.363043,-6.181486,29.05.2020,2006
1857,33 Dunlin House|| Redcourt Oaks|| Seafield Roa...,Dublin 3,D03,2785,Apartment to Rent,3,3,D00,53.363041,-6.181488,29.05.2020,1024
1858,Ashbrook|| Howth Road|| Clontarf|| Dublin 3,Dublin 3,D03,2250,Apartment to Rent,1,1,D00,53.370000,-6.213462,31.05.2020,146
1859,Ashbrook|| Howth Road|| Clontarf|| Dublin 3,Dublin 3,D03,2625,Apartment to Rent,3,2,D00,53.368000,-6.213461,31.05.2020,1007
1860,Ashbrook|| Howth Road|| Clontarf|| Dublin 3,Dublin 3,D03,2750,Apartment to Rent,2,2,D00,53.369000,-6.213460,31.05.2020,154
1861,Ashbrook|| Howth Road|| Clontarf|| Dublin 3,Dublin 3,D03,1950,Apartment to Rent,2,1,D00,53.368998,-6.213464,31.05.2020,658
1862,104 Iona Road|| Drumcondra|| Dublin 3,Dublin 3,D03,1400,Flat to Rent,1,1,D00,53.370140,-6.252226,27.05.2020,696
1863,5 Millbourne Avenue|| Drumcondra|| Dublin 3,Dublin 3,D03,2200,House to Rent,3,3,D00,53.370140,-6.252226,26.05.2020,1242
1864,77 Russell Avenue|| Drumcondra|| Dublin 3,Dublin 3,D03,2500,House to Rent,4,1,D00,53.370140,-6.252226,29.05.2020,221
1865,Drumcondra|| Drumcondra|| Dublin 9,Dublin 9,D09,1700,Apartment to Rent,2,1,D00,53.370138,-6.252228,30.05.2020,1052
1866,Beneavin|| Glasnevin|| Dublin 11,Dublin 11,D11,2300,House to Rent,3,1,D00,53.377404,-6.274068,28.05.2020,1304
1867,Whitworth Road|| Drumcondra|| D9|| Glasnevin||...,Dublin 9,D09,1200,Studio apartment to Rent,2,2,D00,53.377402,-6.274070,30.05.2020,13428
1868,Adelaide Square|| Whitefriar Street|| Dublin 2...,Dublin 2,D02,1800,Apartment to Rent,1,1,D00,53.382479,-6.313365,25.05.2020,294
1869,The Waterside|| Charlotte Quay Dock|| Grand Ca...,Dublin 4,D04,2380,Apartment to Rent,2,2,D00,53.382477,-6.313367,29.05.2020,622
1870,Francis Street|| Christchurch|| Dublin 8,Dublin 8,D08,1850,Apartment to Rent,1,1,D00,53.392871,-6.260079,29.05.2020,324
1871,Old Town Avenue|| Santry|| Dublin 9,Dublin 9,D09,950,Studio apartment to Rent,2,1,D00,53.392869,-6.260081,29.05.2020,3431
1872,Ongar House|| Ongar|| Dublin 15,Dublin 15,D15,1800,Apartment to Rent,2,2,D00,53.395098,-6.438388,25.05.2020,340
1873,Ongar House|| Ongar|| Dublin 15,Dublin 15,D15,2100,Apartment to Rent,3,3,D00,53.395096,-6.438390,25.05.2020,284

### Primary and secondary school

In [11]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'Primary and secondary school')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,St Brigids Girl School,"5 St Brigid's Rd, Blanchardstown, Dublin 5, D0...",D15,F79X,Primary school,3.0,2.0,53.384664,-6.373433
1,St Louis Senior Primary School,"3 Leinster Rd, Rathmines, Louis Lane, Co. Dubl...",D06,N0A1,Primary school,4.1,8.0,53.324727,-6.267897
2,John Scottus Primary School,"47-49 Northumberland Rd, Ballsbridge, Dublin 4...",D04,NaN,School,4.9,20.0,53.334464,-6.237324
3,St. David's Boys National School,"Kilmore Rd, Beaumont, Dublin 5, D05 YY68",D05,K8X9,Primary school,5.0,8.0,53.386056,-6.216173
4,The Teresian School,"12 Stillorgan Rd, Dublin 4, D04 E9X5",D04,NaN,School,4.8,8.0,53.314923,-6.227960
5,Scoil Neasáin,"McAuley Rd, Harmonstown, Dublin 5, D05 VF95",D05,RT20,School,5.0,2.0,53.382146,-6.196239
6,The Embassy Primary School,"5 Clyde Rd, Dublin 4, D04 W292",D04,W292,School,5.0,2.0,53.329453,-6.235399
7,Springdale National School,"Lough Derg Rd, Edenmore, Dublin 5, D05 E954",D05,X316,School,4.2,13.0,53.382313,-6.179557
8,St Patrick Boys National School,"Cambridge Rd, Dublin, D04 AP98",D04,AP98,Primary school,5.0,1.0,53.343392,-6.225355
9,Scoil Aine Girls School,"5 All Saints Rd, Clontarf East, Dublin 5, D05 ...",D05,C960,School,3.5,8.0,53.378067,-6.177423
10,Saint Mary's National School​,"Belmont Ave, Ranelagh, Dublin 4, D04 K025",D06,X0T8,School,4.8,5.0,53.321066,-6.238920
11,"St Brigids GNS, Killester, Dublin 5","St Brigid's Rd, Northside, Killester, Co. Dubl...",D05,YV44,School,5.0,2.0,53.378968,-6.205224
12,St Conleth's College,"28 Clyde Rd, Dublin, D04 FT98",D04,FT98,School,4.8,15.0,53.327961,-6.240349
13,St Benedicts & St Marys National School,"30-68 Grange Park View, Grange, Dublin 5, D05 ...",D05,NaN,School,5.0,4.0,53.388497,-6.164294
14,"Scoil Mhuire, Lakelands GNS","Gilford Rd, Sandymount, Co. Dublin, D04 DC04",D04,DC04,School,4.8,5.0,53.328315,-6.211172
15,Shellybanks Educate Together School,"Seafort Ave, Dublin 4, D04 F8P5",D04,H330,School,5.0,6.0,53.333026,-6.214351
16,St. Christopher's Primary School,"Haddington Rd, Dublin, D04 FP20",D04,FP20,School,4.8,5.0,53.335503,-6.240301
17,Special Primary School,"46 Seville Pl, North Dock, Dublin 1, D01 K227",D01,K227,Primary school,NaN,NaN,53.351587,-6.242852
18,St. Joseph's CBS Secondary School,"Merville Ave, Fairview, Dublin 3, D03 H524",D03,VY92,High school,3.9,12.0,53.363939,-6.233694
19,Gouyang Primary School,"34 Aungier St, Dublin 2, D02 HK75",D02,HK75,School,NaN,NaN,53.338913,-6.265536
20,The Georgian Montessori Primary School,"40 Belvedere Pl, Mountjoy, Dublin, D01 W3W5",D01,V4F5,School,5.0,1.0,53.358042,-6.257813
21,Saint Columba's National School,"Waterloo Ave, North Strand, Dublin, D03 NH34",D03,NH34,School,5.0,4.0,53.358710,-6.242333
22,Catholic University School,"89 Leeson Street Lower, Dublin 2, D02 KC81",D02,NaN,Catholic school,3.5,13.0,53.335271,-6.255883
23,Scoil Chaoimhin,"Marlborough Street, North City, Dublin, D01 YT29",D01,YT29,Primary school,3.7,3.0,53.351326,-6.257607
24,St. Joseph's Co-Educational National School,"126 E Wall Rd, East Wall, Dublin 3, D03 K220",D03,K220,School,5.0,6.0,53.354366,-6.228532
25,International School of Dublin,"Synge St, Saint Kevin's, Dublin, D08 PW64",D08,PW64,Private school,4.0,10.0,53.333257,-6.266979
26,Howth Road Mixed National School,"Clontarf Rd, Northside, Dublin 3, D03 E166",D04,FT66,School,2.0,4.0,53.363940,-6.224493
27,Scoil Chaitríona Baggot Street,"59 Baggot Street Lower, Dublin 2, D02 H365",D02,C625,School,4.8,4.0,53.336205,-6.246258
28,O'Connell Secondary School,"13 Richmond St N, Drumcondra, Dublin, D01 V1K2",D01,V1K2,Middle school,3.9,15.0,53.358165,-6.250703
29,St Vincents Infant Boys School,"26 William St N, Northside, Dublin, D01 A5V0",D01,A5V0,School,5.0,1.0,53.357101,-6.247245
...,...,...,...,...,...,...,...,...,...
451,Rathmichael Parish National School,"Stonebridge Rd, Shankill, Dublin",D18,NaN,School,5.0,5.0,53.236146,-6.127750
452,Mater Christi Secondary School,"Heathfield View, Kildonan, Dublin",D11,NaN,High school,NaN,NaN,53.394831,-6.321018
453,St.Mary's College,"73_79, Rathmines Rd Lower, Rathmines, Dublin 6",D06,HW58,School,4.3,17.0,53.327562,-6.267247
454,Firhouse Community College,"Firhouse Rd, Dublin 24",D24,CX39,School,2.9,13.0,53.276232,-6.348494
455,"Marino College, Marino Mart, Dublin","15-21 Marino Mart, Northside, Dublin 3",D03,AD90,School,3.0,1.0,53.364247,-6.231430
456,St. Marnock’s National Catholic School,"Strand Rd, Burrow, Portmarnock, Co. Dublin",D13,NaN,School,5.0,4.0,53.422298,-6.134784
457,St Helen's Tuition Centre,"Limetree Ave, Robswalls, Portmarnock, Co. Dublin",D13,NaN,School,4.5,4.0,53.439210,-6.136242
458,St Helens Jr School,"Limetree Ave, Robswalls, Portmarnock, Co. Dublin",D13,NaN,School,NaN,NaN,53.438998,-6.135762
459,Trinity Comprehensive School,"Ballymun Rd, Northside, Dublin 9",D09,A4N8,School,3.9,14.0,53.393579,-6.263472
460,ST MARY'S SECONDARY SCHOOL,"Holy Faith Convent, Clare Rd, Northside, Dublin 9",D09,NaN,High school,5.0,2.0,53.375900,-6.272866
461,Mount Carmel Secondary School,"King's Inns St, Northside, Dublin 1, D01 W657",D01,W657,Single sex secondary school,3.7,11.0,53.351972,-6.268311
462,holy faith secondaryschool,"Philipsburgh Ave, Northside, Dublin",D03,NaN,School,NaN,NaN,53.367692,-6.239772
463,Maryfield College,"Sion Hill Rd, Grace Park, Dublin",D09,NaN,School,3.1,10.0,53.376004,-6.235165
464,Mercy College,"St Brendan's Dr, Northside, Dublin",D05,NaN,School,5.0,2.0,53.386251,-6.199622
465,O'Farrell School Wear,"Unit 104, Kingsford Cross, Strand Rd, Burrow, ...",D13,A028,School,4.7,15.0,53.422650,-6.135185
466,Sandymount Park Educate Together Secondary School,"16 Simmonscourt Rd, Dublin",D04,NaN,School,NaN,NaN,53.326000,-6.225889
467,Dominican College,"204 Griffith Ave, Drumcondra, Dublin 9",D09,NaN,School,4.4,8.0,53.374364,-6.249518
468,St. Fiachra's Senior National Catholic School,"Montrose Park, Beaumont, Dublin 5",D05,NaN,School,3.7,3.0,53.387240,-6.226844
469,The Institute of Education,"85 Leeson Street Lower, Dublin",D02,NaN,School,4.4,31.0,53.335053,-6.255542
470,Coolmine Community School,"Clonsilla, Dublin",D15,NaN,Community school,5.0,1.0,53.349809,-6.260274
471,Gaelscoil Bhaile Munna,"Coultry Rd, Ballymun, Dublin, 9",D09,NaN,School,5.0,3.0,53.398206,-6.255974
472,Gardiner Street School,"6 Belvedere Court, Mountjoy, Dublin",D01,HX30,School,3.6,8.0,53.357882,-6.258940
473,St Marys Boys National School,"Haddington Rd, Dublin",D04,NaN,School,5.0,4.0,53.334323,-6.241028
474,S N Seosamh Na Mbrathar,"Clontarf West, Dublin",D03,NaN,School,NaN,NaN,53.364752,-6.233361
475,Abacas Kilbarrack,"5 Greendale Rd, Northside, Dublin 5",D05,NY54,School,NaN,NaN,53.387060,-6.156940
476,St Eithnes Girls National School,"Edenmore Ave, Edenmore, Dublin 5",D05,A7X6,School,4.4,9.0,53.389311,-6.180828
477,Scoil Bhríde,"Grange Rd, Donaghmede, Dublin",D13,NaN,School,5.0,2.0,53.397125,-6.161100
478,Lindsay Road National School,"Lindsay Rd, Glasnevin, Dublin 9",D09,T2F3,School,3.0,2.0,53.364913,-6.264743
479,Scoil an tSeachtar Laoch,"Ballymun Rd, Ballymun, Dublin 11",D11,NaN,School,3.9,7.0,53.392702,-6.264820
480,Belgrove girls school,"Clontarf East, Dublin",D03,NaN,School,5.0,1.0,53.363868,-6.199438

In [14]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [15]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [16]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(9258, 18)
(9258, 22)

In [17]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_Primary_secondary_school_final.xlsx', index = False)

### GP

In [18]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'GP')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Dr. C. Donaghy,"109 Dorset Street Lower, Northside, Dublin 1",D01 X953,General practitioner,4.4,14.0,53.358024,-6.263544
1,Capel Street Medical Centre,"138 Capel St, North City, Dublin, D01 C4E9",D01 C4E9,General practitioner,4.7,91.0,53.347860,-6.268725
2,Dr Edel Dominique,"Clare St, Dublin 2, D02 VX59",D02 CK80,General practitioner,4.6,20.0,53.341471,-6.252176
3,Temple Bar Medical Centre,"26 Wellington Quay, Temple Bar, Dublin, D02 R221",D02 R221,General practitioner,5.0,16.0,53.345666,-6.264570
4,"D15 G.P., Dr Anas Mansour, MICGP, MUDR, MD, Ge...","D15GP, Unit 3 Ground Floor, Main St, Blanchard...",D15 YP03,Doctor,4.1,63.0,53.386900,-6.377402
5,Generation Health Medical Clinic,"9A Castlecourt Shopping Centre, Castleknock, D...",D15 E652,General practitioner,3.9,10.0,53.374805,-6.363206
6,Ballsbridge Medical Centre,"66 Merrion Rd, Ballsbridge, Dublin 4, D04 N1W5",D04 N1W5,Doctor,3.6,30.0,53.327128,-6.224904
7,Griffith Avenue Practice,"411 Griffith Ave, Whitehall, Dublin 9, D09 YY19",D09 YY19,General practitioner,3.7,7.0,53.378135,-6.260983
8,Rafter's Medical Centre Rathmines,"Rathmines Road Lower Rathmines Rd Lower, Rathm...",D06 HW58,General practitioner,3.5,19.0,53.322875,-6.265924
9,Sirona Medical,"185 Cabra Rd, Northside, Dublin 7, D07 FR52",D07 FR52,General practitioner,3.2,11.0,53.361602,-6.291004
10,Summerhill Family Practice,"Summerhill, Mountjoy, Dublin",D01 A031,General practitioner,3.5,4.0,53.355661,-6.253201
11,Chapelizod Medical Centre,"Belgrove Park, Chapelizod, Dublin",D20,General practitioner,4.4,11.0,53.350732,-6.350963
12,Marino Medical Centre,"144 Philipsburgh Ave, Northside, Dublin 3, D03...",D03 R6X6,General practitioner,4.7,11.0,53.368822,-6.239072
13,Corvin Medical Centre,"201 Sevenoaks, Sarsfield Rd, Dublin",D10,General practitioner,2.3,3.0,53.341618,-6.327047
14,Templeogue Village Medical,"184 Templeogue Rd, Templeogue Village, Dublin",D6W WN53,General practitioner,5.0,8.0,53.298265,-6.303698
15,Dr Robert Dybkowski and Dr Ilona Izdebska medi...,"No 1, Orby Chambers, 7 Coke Ln, Smithfield, Du...",D07 NV02,Doctor,3.5,57.0,53.346848,-6.279559
16,"Oakwood Medical Clinic, Castleknock","Castlecourt Shopping Centre, 3, Dublin 15",D15 E652,General practitioner,3.9,16.0,53.374861,-6.363201
17,Dr. John Blennerhassett,"80 Malahide Rd, Northside, Dublin 3, D03 N9C8",D03 N9C8,General practitioner,NaN,NaN,53.367949,-6.226615
18,Clontarf General Practice,"188 Clontarf Rd, Clontarf East, Dublin 3, D03 ...",D03 C3W0,General practitioner,4.2,5.0,53.359506,-6.196921
19,Iveagh Medical Clinic,"235 Crumlin Rd, Crumlin, Dublin 12, D12 WR53",D12 WR53,General practitioner,3.9,14.0,53.327633,-6.308049
20,Rowan Family Practice,"123 Churchtown Rd Lower, Churchtown Lower, Dub...",D14 E840,General practitioner,5.0,10.0,53.296645,-6.253906
21,Dr. Martin Maguire,"40 Drumcondra Rd Upper, Drumcondra South, Dubl...",D09 C4H3,General practitioner,3.7,3.0,53.369717,-6.253959
22,Irishtown & Ringsend Primary Care Centre,"Irishtown Rd, Dublin",D04,General practitioner,3.4,21.0,53.340728,-6.225657
23,Dr Anver Amod,"44 R118, Co. Dublin",D02,General practitioner,4.3,6.0,53.342840,-6.249920
24,Dr. Fred Shackleton GP,"115 Cromwellsfort Rd, Walkinstown, Dublin 12, ...",D12 YR27,General practitioner,3.7,6.0,53.316961,-6.322847
25,Kirkfield Clinic,"Blanchardstown Primary Care Centre, Grove Rd, ...",D15 HNT2,General practitioner,4.8,5.0,53.391130,-6.394036
26,Dr Robert Nelson,"17 Beechpark Ave, Castleknock, Dublin 15, D15 ...",D15 HP5H,General practitioner,5.0,2.0,53.378112,-6.358579
27,Perrystown Medical Centre,"171 Whitehall Rd, Terenure, Dublin 12, D12 P030",D12 P030,General practitioner,4.8,5.0,53.307601,-6.319332
28,Dr. Dolores Rafter,"2 Hazelwood Ave, Clonsilla, Dublin 15, D15 VP04",D15 KCW9,General practitioner,5.0,2.0,53.393617,-6.418285
29,St Jude Family Practice,"69A Orwell Park Rise, Templeogue, Dublin 6W, C...",D6W AF86,General practitioner,5.0,7.0,53.299562,-6.323697
...,...,...,...,...,...,...,...,...
137,Dundrum Family Practice,"218 Barton Rd E, Dundrum, Dublin 14, D14 AE92",D14 AE92,Doctor,4.0,5.0,53.288717,-6.246854
138,Moe Family Practice,"Woodlawn, Clonskeagh Rd, Farranboley, Dublin 14",D14 X5R3,General practitioner,5.0,1.0,53.308040,-6.237337
139,Dr Abdul Rashid Ibrahim,"52 Ascaill Ard an Rátha, Grange, Dublin 13, D1...",D13 RK03,Doctor,5.0,8.0,53.396317,-6.169539
140,Clongriffin Medical Centre,"17A Main St, Clongriffin, Dublin 13, D13 CT89",D13 N2Y4,Doctor,4.2,13.0,53.402377,-6.152325
141,Dr. Luke B. Brady,"65 Knockcullen Dr, Ballyroan, Dublin 16, D16 ET78",D16 ET78,Doctor,4.5,4.0,53.286825,-6.309786
142,Dr. Ashcroft-Jones,"1 Grange Manor Dr, Rathfarnham, Dublin, D16 X254",D16 X254,Doctor,5.0,3.0,53.285504,-6.272591
143,Bayside Surgery,"Bayside Shopping Centre, Bayside Square E, Nor...",D13 C2F6,Doctor,4.8,8.0,53.388413,-6.140352
144,Dr. Alex Khourie,"5 St Enda's Dr, Rathfarnham, Dublin 14, D14 T2P8",D14 P6F2,Doctor,4.0,4.0,53.289172,-6.283425
145,David Kelly,"114 Morehampton Rd, Dublin 4, D04 K3H7",D04 K3H7,Doctor,NaN,NaN,53.323378,-6.238335
146,Dr K.B Olinger,"Village Centre, Unit 6, The, Watery Ln, Dublin 22",D22 AW72,Doctor,4.3,12.0,53.322655,-6.393011
147,The Meridian Clinic Clarehall,"13 Malahide Rd, Grange, Dublin",D03 TH73,Doctor,3.3,24.0,53.401204,-6.180002
148,Dr Patrick O'Connor,"Glenveiw Medical Center 24, 12 Glenview Park, ...",D24 DX6K,Doctor,5.0,4.0,53.288750,-6.347608
149,Grange Mount Surgery,"Grange, Co. Dublin",D16,General practitioner,NaN,NaN,53.609405,-6.252330
150,Glenfield Family Practice,"20 Glenfield Ave, Rowlagh, Dublin, D22 E309",D22 E309,Doctor,4.2,11.0,53.347527,-6.398420
151,Newlands Cross Medical Centre,Newlands Cross Medical Centre Aldi Shopping Co...,D22,Doctor,3.9,25.0,53.313322,-6.394556
152,Doctor Wilson,"15 Ashwood Rd, Clonburris Great, Dublin 22, D2...",D22 C7P9,Doctor,5.0,4.0,53.326159,-6.410975
153,Manor Road Surgery,"31 Manor Rd, Redcowfarm, Dublin 20, D20 AW73",D20 AW73,Doctor,3.6,21.0,53.351019,-6.368593
154,School Age Team HSE,"off, Leopardstown Shopping Centre, Unit 10/11,...",D18,Doctor,NaN,NaN,53.259254,-6.196897
155,Dr. Paul McCormick,"218 Barton Rd E, Dundrum, Dublin 14, D14 AE92",D14 AE92,Doctor,5.0,2.0,53.288706,-6.246909
156,EAST DOC,"Elm Park, Dublin 4, D04 W6N7",D04 W6N7,Doctor,3.6,9.0,53.317594,-6.209613
157,Healthwell Clinic,"15 Clonsilla Rd, Clonsilla, Dublin, D15 TC6X",D15 P2Y8,Doctor,2.3,9.0,53.382547,-6.406679
158,HSE Health Centre Cabra,"75-87 Quarry Rd, Northside, Dublin 7, D07 X002",D07 H7P8,Doctor,3.7,3.0,53.364602,-6.288845
159,Dr. Desmond Coady,"1 Old Bawn Way, Oldbawn, Dublin 24, D24 XF7A",D24 R7DK,Doctor,5.0,6.0,53.279945,-6.359809
160,"Glenview Medical, Centric Health","Ireland, 192B Glenview Park, Dublin 24",D24 K030,Doctor,NaN,NaN,53.288620,-6.344050
161,Ballycullen Medical Centre,"Oldcourt Shopping Centre, 24 Parklands Rd, Dub...",D24 PXV3,Doctor,5.0,5.0,53.274757,-6.345037
162,Dr. Alvise Calamai,"Blanchardstown Primary Care Centre, Grove Rd, ...",D15 HNT2,Doctor,5.0,6.0,53.391118,-6.394063
163,Old Bawn Family Practice,"59a Old Bawn Way, Tallaght, Dublin, D24 RY77",D24 RY77,Doctor,5.0,1.0,53.279810,-6.364290
164,Greenlea Clinic,"118 Greenlea Rd, Terenure, Dublin, D6W WY18",D6W WY18,Doctor,3.8,19.0,53.307378,-6.300449
165,"Old Bawn Medical, Centric Health","Unit 2 & 3 Old Bawn Shopping Centre , Tallaght...",D24 NVR4,Doctor,5.0,1.0,53.285491,-6.360923
166,Dr Ronan Donohoe,"59A Old Bawn Way, Oldbawn, Dublin 24",D24 R7DK,Doctor,4.1,7.0,53.279611,-6.364166

In [19]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.35)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [20]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [21]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(4209, 18)
(4209, 21)

In [22]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_GP_final.xlsx', index = False)

### College and university

In [24]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'College and university')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Harmony School of Music/Tipperary Fine Foods,"10 Fairview Strand, Northside, Dublin 3, D03 VX48",D03,VX48,University,NaN,NaN,53.362540,-6.238159
1,Pulse College,"20 Ringsend Rd, Dublin 4, D04 CF66",D04,CF66,College,4.6,15.0,53.342172,-6.234706
2,Dorset College,"8 Belvedere Pl, Mountjoy, Dublin, D01 EV27",D01,EV27,College,3.7,29.0,53.358172,-6.257379
3,Hibernia College,"Block B, The Merrion Centre, Merrion Rd, Dubli...",D04,H2H4,College,2.4,7.0,53.319161,-6.213845
4,Trinity College Dublin,"College Green, Dublin 2",D02,VR66,University,4.5,1780.0,53.343793,-6.254572
5,Clonliffe College Seminary,"Clonliffe Rd, Drumcondra, Dublin",D03,NaN,Christian college,5.0,1.0,53.364486,-6.253315
6,University College Dublin,"University College Dublin, Belfield, Dublin 4",D14,K5X0,University,4.5,319.0,53.306749,-6.221034
7,Griffith College,"S Circular Rd, Merchants Quay, Dublin 8, D08 V04N",D08,W56T,College,4.0,153.0,53.330989,-6.278118
8,DCU St Patrick's Campus,"Drumcondra Rd Upper, Drumcondra, Dublin 9",D09,HY29,University,4.3,38.0,53.370180,-6.254689
9,Dublin College of Advanced Studies,"98 Capel St, Rotunda, Dublin 1, D01 HP52",D01,HP52,College,3.9,18.0,53.350174,-6.269685
10,TU Dublin City Campus Mountjoy Square,"41-45, Mountjoy Square S, Mountjoy, Dublin 1, ...",D01,A998,Technical university,4.1,10.0,53.355818,-6.256919
11,CCT College Dublin,"30-34 Westmoreland St, Dublin 2, D02 HK35",D02,NaN,College,4.4,35.0,53.346041,-6.258875
12,Dublin Business School,"13/14 Aungier St, Dublin, D02 WC04",D02,NaN,College,3.7,90.0,53.340538,-6.265492
13,TU Dublin Sackville Place,"5 Sackville Pl, North City, Dublin 1, D01 FH94",D01,FH94,Technical university,3.0,1.0,53.348974,-6.258546
14,Technological University Dublin Bolton Street ...,"Bolton St, Rotunda, Dublin, D01 K822",D01,K822,University,4.2,44.0,53.351515,-6.269278
15,Royal College of Surgeons in Ireland,"123 St Stephen's Green, Dublin, D02 YN77",D02,YN77,University,4.2,72.0,53.338962,-6.262036
16,Independent College Dublin,"Block B, The Steelworks, Foley Street, Dublin ...",D01,X997,College,4.0,12.0,53.352644,-6.250364
17,National College of Ireland,"Mayor Street Lower, International Financial Se...",D01,NaN,College,4.0,96.0,53.349103,-6.242812
18,TCD School of Nursing & Midwifery,"The Gas Building, 24 D'Olier Street, Dublin, D...",D02,T283,University,5.0,4.0,53.346556,-6.257853
19,Irish Bible Institute,"Ulysses House, Foley St, Mountjoy, Dublin 1, D...",D01,WA07,Christian college,4.7,18.0,53.351914,-6.250878
20,Oxford College International,"5 Abbey Street Lower, North City, Dublin 1, D0...",D01,P7V2,College,NaN,NaN,53.348672,-6.258879
21,College of Naturopathic Medicine,"CNM Ireland, 25 Wolfe Tone St, North City, Dub...",D01,E167,College,3.7,7.0,53.349400,-6.267823
22,Kilroy's College,"Wentworth, 13 Eblana Villas, Grand Canal Stree...",D02,T268,College,5.0,2.0,53.340810,-6.242938
23,Dublin City University,"Dublin City University Glasnevin, Dublin 9",D11,W8H1,University,4.3,242.0,53.386094,-6.256369
24,Griffith College City Centre,"25 Wolfe Tone St, North City, Dublin 1, D01 X9K7",D01,X9K7,Private college,4.8,9.0,53.349400,-6.267823
25,Technological University Dublin - City Campus,"Aungier St, Dublin, D02 HW71",D02,HW71,University,4.4,85.0,53.338530,-6.266599
26,TU Dublin Kevin Street,"Kevin Street, Portobello, Dublin 2, D08 X622",D08,F2K3,University,4.3,56.0,53.337144,-6.268237
27,Boston College Ireland,"43 St Stephen's Green, Dublin 2, D02 DY80",D02,DY80,University,4.6,5.0,53.338262,-6.255360
28,GMB College,"14 Mount Street Upper, Dublin 2, D02 EY24",D02,EY24,College,4.0,2.0,53.337710,-6.245939
29,Champlain College Dublin,"43 Leeson Street Lower, Saint Kevin's, Dublin ...",D02,EH10,College,5.0,1.0,53.333022,-6.254051
...,...,...,...,...,...,...,...,...,...
128,Ringsend College,"Cambridge Rd, Dublin 4",D06,HH76,College,3.0,4.0,53.343755,-6.224509
129,Trinity Online Services,"3/ Dublin 2 Ireland, 4 Foster Pl, Dublin",D02,NaN,University,NaN,NaN,53.344827,-6.261318
130,Coláiste na hÉireann,"Clare Ln, Dublin 2",D02,NaN,College,NaN,NaN,53.341543,-6.251294
131,TU Dublin Faculty of Tourism and Food,"Dublin Institute of Technology, Cathal Brugha ...",D01,NaN,Technical university,NaN,NaN,53.352060,-6.260187
132,TCD Arts Building,"20-32 Nassau St, Dublin",D02,VY46,University,NaN,NaN,53.343239,-6.256538
133,Unigran Dublin,"Zhivago Building, Seda College, Dublin Institu...",D06,NaN,Private university,5.0,3.0,53.350484,-6.269391
134,Trinity Research & Innovation,"O'Reilly Institute, Trinity College Dublin, Du...",D03,DH67,University,5.0,1.0,53.343345,-6.250045
135,Drumcondra House,"167 R132, Drumcondra, Dublin",D09,NaN,University,NaN,NaN,53.371031,-6.249237
136,"DIT Grangegorman, Rathdown House","TU Dublin Grangegorman, Rathdown Rd, Arran Qua...",D07,NaN,University,NaN,NaN,53.354784,-6.279085
137,Lloyd Institute,"42A Pearse St, Dublin",D02,EA22,University,4.7,7.0,53.343818,-6.250987
138,Department of Psychiatry,"38 Eccles St, Phibsborough, Dublin 7",D07,V294,University,NaN,NaN,53.359247,-6.268949
139,testprepDublin,"41B Drury St, Dublin",D02,DP11,University,NaN,NaN,53.342374,-6.263371
140,"Greenway Hub, TU Dublin","Grangegorman, Dublin",D07,NaN,University,NaN,NaN,53.356784,-6.279265
141,TU Dublin North House,"Grangegorman Lower, Arran Quay, Dublin",D07,NaN,University,NaN,NaN,53.356345,-6.283620
142,University College Dublin,"Merrion Rd, Dublin",D04,NaN,University,NaN,NaN,53.320649,-6.215804
143,"Trinity College Dublin, School of Nursing and ...","2 Clare St, Dublin 2",D02,CK80,University,NaN,NaN,53.341748,-6.251927
144,Belgrove Student Residences,"Belfield, Dublin",D04,NaN,University,5.0,5.0,53.304572,-6.224095
145,DIT School of Electronic and Communications En...,"Dublin Institute Of Technology, Kevin St, Port...",D08,NF82,University,4.3,3.0,53.336655,-6.267908
146,"Block E, Institute of Technology, Blanchardstown","Blanchardstown Rd N, Ballycoolen, Dublin",D15,NaN,College,NaN,NaN,53.405699,-6.372307
147,"Centre For Talented Youth, Ireland","Dublin City University, Dublin 9",D09,FW22,College,3.0,4.0,53.386029,-6.260915
148,DIT,"Grangegorman Upper, Phibsborough, Dublin",D07,NaN,College,NaN,NaN,53.356762,-6.279085
149,DBL College,"Unit C3, The Steelworks, Foley Street, Dublin 1",D01,NaN,College,NaN,NaN,53.352275,-6.250862
150,Dublin Institute of Technology - Admin and HR,"149 Rathmines Rd Lower, Rathmines, Dublin 6",D06,HW58,College,5.0,1.0,53.325254,-6.265549
151,RCSI Smurfit Building,"Hospital Rd, Beaumont, Dublin",D09,NaN,College,NaN,NaN,53.388954,-6.225557
152,dudance society,"Regent House, Trinity College Dublin, College ...",D02,AT80,College,5.0,1.0,53.344454,-6.258913
153,Agriculture Food Science Center,"Roebuck, Dublin",D14,NaN,College,NaN,NaN,53.307298,-6.224479
154,Adult Basic Education For Everyone (ABLE),"Adult Education Centre, Main St, Blanchardstow...",D15,NaN,College,5.0,2.0,53.386124,-6.375231
155,Trinity,"118-112 R138, Dublin",D01,NaN,College,NaN,NaN,53.344243,-6.259579
156,International School of Business Dublin,"84, 88 South Great George's Street, Dublin",D02,NaN,College,4.7,3.0,53.343711,-6.264589
157,UCD Teaching & Learning,"F309 Newman Building, University College Dubli...",D18,NaN,University,NaN,NaN,53.305487,-6.222079

In [25]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [26]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [27]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(10262, 18)
(10262, 22)

In [28]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_College and university_final.xlsx', index = False)

### Sports facility

In [29]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'Sports facility')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Scoil Ui Chonaill GAA Club,"95 Clontarf Rd, Clontarf East, Dublin 3, D03 F862",D03,C2X0,Sports club,4.5,12.0,53.361138,-6.207547
1,Trinity College Sports Centre,"43 Pearse St, Dublin 2, D02 W085",D02,NaN,Sports complex,4.3,195.0,53.344057,-6.249955
2,Dublin Port Stadium Stella Maris F.C.,"3 Waterfall Ave, Dublin Port, Drumcondra, Stad...",D03,A4W5,Football club,4.2,87.0,53.366247,-6.247590
3,Cymc/L C Pitch & Putt Club,"80 Philipsburgh Ave, Northside, Dublin 3, D03 ...",D03,H3F1,Sports complex,5.0,6.0,53.366066,-6.239358
4,Lourdes Celtic F.C. Football Pitch and Soccer ...,"32 Henry St, Harold's Cross, Dublin, D01 V279",D01,V279,Soccer club,4.7,26.0,53.326220,-6.291067
5,Dublin Docklands Boxing Club,"Arch 3, Seville Pl, Dublin 1, D01 X2T5",D01,X2T5,Boxing club,4.6,5.0,53.354210,-6.246376
6,Corinthians Boxing Club,"off, 2 Bella Place, Buckingham Street Upper, M...",D01,XT81,Boxing club,5.0,3.0,53.354777,-6.250442
7,SPORTSCO,"S Lotts Rd, Dublin 4, D04 R6C2",D04,FR83,Sports complex,4.4,501.0,53.339529,-6.230142
8,BeatBox Boxing Club,"28 Lower Leeson Street Lower, Saint Kevin's, D...",D02,KF97,Boxing club,5.0,36.0,53.333957,-6.255061
9,Pembroke Wanderers Hockey Club,"27A Serpentine Ave, Dublin 4, D04 T329",D04,NaN,Hockey club,4.4,185.0,53.329345,-6.225141
10,Donnybrook Lawn Tennis Club,"4 Brookvale Rd, Ranelagh, Dublin 4, D04 K5V6",D04,K5V6,Sports club,4.5,23.0,53.319440,-6.234087
11,Elm Park Golf & Sports Club,"Nutley House, Nutley Ln, Dublin",D04,WE09,Golf club,4.4,144.0,53.313897,-6.217228
12,Old Wesley,"Donnybrook, Co. Dublin, D04 EY28",D04,NaN,Rugby club,4.5,102.0,53.320090,-6.232962
13,Ballyfermot United Sports & Social Club,"2 Blackditch Rd, Cherry Orchard, Dublin 10, D1...",D10,W738,Sports club,4.1,84.0,53.341819,-6.357480
14,A1 Coaching,"1 Portland St N, Ballybough, Dublin 1, D01 EY00",D01,K768,Sports complex,NaN,NaN,53.359500,-6.256176
15,Dublin City Handball,"27 Mariners Port, North Dock, Dublin",D01,Y0A2,Handball club,5.0,1.0,53.350305,-6.243096
16,Skyvelo Ireland Cycling Club,"3 Burlington Rd, Ballsbridge, Dublin, D04 RD68",D04,RD68,Sports club,NaN,NaN,53.332179,-6.245760
17,Erins Isle GAA Club,"Farnham Dr, Northside, Dublin",D11,NaN,Sports complex,4.4,226.0,53.384970,-6.300142
18,Railway Union Sports Club,"Park Ave, Dublin 4",D04,K462,Sports complex,4.2,164.0,53.325840,-6.212426
19,Wanderers Rugby Club House,"65A Merrion Rd, Ballsbridge, Dublin 4, D04 F8F8",D04,F8F8,Rugby club,4.2,74.0,53.322846,-6.220853
20,Old Belvedere Rugby Club,"Ailesbury Grove, Ballsbridge, Dublin, D04 HF60",D04,NaN,Rugby club,4.2,174.0,53.321602,-6.228584
21,Dublin Chess Club,"3 Fitzwilliam Street Upper, Dublin 2, D02 RR50",D02,RR50,Sports complex,5.0,7.0,53.336609,-6.249609
22,Energia 7's,"Energia Park, 4 Donnybrook Rd, Donnybrook, Co....",D04,VE84,Sports club,NaN,NaN,53.322618,-6.236989
23,Dublin GAA,"Parnell Park, Clancarthy Rd, Northside, Dublin...",D05,X971,Sports club,4.1,21.0,53.372675,-6.217866
24,Ballsbridge Football Club,"Herbert Park, Ballsbridge, Dublin 4, D04 FE40",D04,FE40,Football club,5.0,1.0,53.325320,-6.234150
25,Loop Table Tennis Club,"Ardscoil La Salle, Raheny Rd, Donaghmede, Rahe...",D05,Y132,Table tennis club,4.9,17.0,53.389696,-6.169581
26,St Brigids GAA Club,"Russell Park, Navan Rd, Castleknock, Dublin 15",D15,NaN,Sports complex,4.4,210.0,53.377522,-6.351350
27,Parnells GAA Club,"30 Main Street, Coolock, Dublin 5, D05 H2W0",D05,F2P5,Sports complex,4.2,594.0,53.388390,-6.204958
28,St. John Vianney Football Club,"Kilmore Dr, Beaumont, Dublin, D05 Y765",D05,Y765,Soccer club,3.7,17.0,53.388665,-6.208187
29,UCD Karate,"UCD Sports Centre, University College Dublin, ...",D04,NaN,Martial arts club,5.0,8.0,53.308137,-6.228915
...,...,...,...,...,...,...,...,...,...
281,Red Arches Pitch,"Northside, Baldoyle, Co. Dublin",D13,NaN,Sports complex,3.5,2.0,53.400606,-6.134011
282,Malahide Fingal Hockey Club,"Unnamed Road, Sainthelens, Malahide, Co. Dublin",D17,NaN,Sports club,4.6,8.0,53.439905,-6.150491
283,Poppintree Community And Sports Centre,"Balbutcher Ln, Ballymun, Dublin",D11,NaN,Sports complex,4.4,32.0,53.402879,-6.274250
284,"Pitches 1-7 St Annes Park, Clontarf","Clontarf, Dublin",D03,NaN,Sports complex,NaN,NaN,53.375151,-6.186777
285,Broomfield St. Sylvester's GAA Pitches,"Unnamed Road, Sainthelens, Malahide, Co. Dublin",D17,NaN,Sports club,NaN,NaN,53.438720,-6.151558
286,Raheny GAA Pitch 9,"76-90 All Saints Rd, Clontarf East, Dublin",D05,TK71,Sports complex,3.9,12.0,53.375064,-6.172847
287,Palmerstown Sport Complex,"Oakcourt Ave, Johnstown, Palmerstown, Co. Dublin",D20,NaN,Sports complex,4.2,75.0,53.347865,-6.375080
288,Saint Monica's Gaa,"10, 12 Millwood Park, Grange, Dublin",D05,A5R3,Sports complex,3.9,14.0,53.388832,-6.178250
289,National Tennis Centre,"9 Albert College Park, Whitehall, Dublin 9",D09,AE28,Sports complex,4.5,10.0,53.384463,-6.260495
290,Pitch 30 Clontarf GAA,"Clontarf East, Dublin",D03,NaN,Sports complex,4.0,3.0,53.370728,-6.182849
291,Portmarnock Chess Club,"Clg Naomh Mearnog, Blackwood Lane, Portmarnock...",D13,NaN,Chess club,NaN,NaN,53.434639,-6.140387
292,Cricket Ireland High Performance Training Centre,"Sport Ireland National Sports Campus, Snugboro...",D15,NaN,Sports complex,NaN,NaN,53.394931,-6.353247
293,Portrane Athletic Football Club,Co. Dublin,D01,NaN,Soccer club,4.1,21.0,53.491511,-6.119147
294,Setanta GAA Club,"123 Ballymun Rd, Ballymun, Dublin",D09,W523,Sports complex,4.3,89.0,53.390833,-6.265278
295,Irish Institute of Sports Surface,"Swords Rd, Northside, Dublin 9",D09,DK44,Sports club,1.0,1.0,53.401471,-6.243536
296,Ridgewood New Pitches,"53 The Elms, Rathingle, Co. Dublin",D15,NaN,Football club,3.9,11.0,53.447614,-6.253304
297,Dublin Kendo Kobukai,"Haverty Road, Clontarf West, Dublin",D03,NaN,Sports club,NaN,NaN,53.364722,-6.233405
298,Glasnevin Basketball Club,"St Aidans CBS, Whitehall, Dublin 9",D24,YX6V,Sports club,NaN,NaN,53.384478,-6.251470
299,Dublin Kendo Kobukai,"Grace Park, Dublin",D09,NaN,Sports club,NaN,NaN,53.373792,-6.233759
300,Dublin Kendo Kobukai,"Ballybough, Dublin",D03,NaN,Sports club,NaN,NaN,53.360752,-6.243024
301,A.B.S Powerlifting,"Unit 5 Tolka Valley Industrial Estate, Ballybo...",D11,NaN,Sports club,5.0,27.0,53.376492,-6.295251
302,Glin Boxing Club,"Unit 2, 5 Clonshaugh Rd, Northside, Dublin",D17,NX32,Boxing club,3.7,6.0,53.398043,-6.215624
303,St. Margaret's Golf & Country Club,"Skephubble, St Margaret's, Co. Dublin",D11,NaN,Golf club,4.5,402.0,53.451439,-6.304092
304,Dublin Kendo Kobukai,"Davitt Rd, Dublin Southside, Dublin",D12,NaN,Sports club,NaN,NaN,53.335156,-6.318303
305,Ballymun United Soccer Complex,"St Margaret's Road, Ballymun, Dublin 11",D11,NaN,Soccer club,4.7,54.0,53.407055,-6.278565
306,St Pauls Artane Football Club,"Gracefield Ave, Northside, Artane, Co. Dublin, 5",D05,DR12,Football club,4.3,41.0,53.382275,-6.194623
307,Dublin Combat Academy,"Unit 2 7, Cross Guns Business Park, 7 Royal Ca...",D07,X0W7,Martial arts club,5.0,10.0,53.363696,-6.271252
308,Shankill GAA Shanganagh Cliffs Pitch,"Hackettsland, Dublin",D18,NaN,Sports club,4.8,4.0,53.239841,-6.113179
309,Sportsworld Terenure Running Club,"68 Rathdown Ave, Terenure, Dublin, DUBLIN 6W",D6W,VW80,Athletic club,4.9,8.0,53.302525,-6.289237
310,Batterstown GAA Pitch,"5, 53°28'26.0""N 6°32'41., 6 Richmond St N, Dub...",D01,A0E7,Sports complex,4.3,26.0,53.473889,-6.544861

In [30]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.45)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [31]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [32]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(3572, 18)
(3572, 22)

In [33]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_sports_facility_final.xlsx', index = False)

### Hotel and restaurant

In [8]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'Hotel and restaurant')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Enoteca Delle Langhe,"Italian Quarter, Bloom Ln, North City, Dublin,...",D01,C850,Italian restaurant,4.3,507.0,53.346610,-6.265166
1,Fusciardi's Restaurant and Takeaway,"10 Capel St, North City, Dublin, D01 PW32",D01,PW32,Restaurant,4.4,283.0,53.346724,-6.267948
2,Boco,"57 Bolton St, Northside, Dublin 1, D01 CK40",D01,CK40,Pizza restaurant,4.6,780.0,53.351330,-6.270068
3,The Winding Stair,"40 Ormond Quay Lower, North City, Dublin 1, D0...",D01,R9Y5,Irish restaurant,4.4,1443.0,53.346667,-6.263611
4,Bar Italia ristorante,"26 Ormond Quay Lower, North City, Dublin, D01 ...",D01,X942,Italian restaurant,4.4,738.0,53.346395,-6.264980
5,Il Vignardo Restaurant,"21 Store St, Mountjoy, Dublin 1, D01 T9R2",D01,T9R2,Italian restaurant,3.8,77.0,53.350096,-6.252712
6,Chapter One Restaurant,"18-19 Parnell Square N, Rotunda, Dublin 1, D01...",D01,NaN,Fine dining restaurant,4.7,714.0,53.354343,-6.264093
7,Wasabi Bar & Grill,"4 Dorset Street Lower, Rotunda, Dublin, D01 E1X7",D01,NaN,Brazilian restaurant,4.0,410.0,53.357633,-6.263206
8,Veginity,"101 Dorset Street Upper, Inns Quay, Dublin, D0...",D01,A2F4,Vegan restaurant,4.5,218.0,53.355425,-6.265953
9,Le Bon Crubeen,"81-82 Talbot St, North City, Dublin 1, D01 CD34",D01,P6H2,French restaurant,4.2,799.0,53.350512,-6.255137
10,Hot Bubble Café,"55 Capel St, North City, Dublin 1, D01 N9Y5",D01,N9Y5,Restaurant,4.7,188.0,53.349248,-6.268912
11,Arisu Restaurant,"120 Capel St, North City, Dublin, D01 KC63",D01,KC63,Korean restaurant,4.4,919.0,53.348878,-6.269060
12,Flanagan's Restaurant,"61 O'Connell Street Upper, North City, Dublin ...",D01,Y274,Irish restaurant,4.1,1775.0,53.350333,-6.260933
13,Supermac's & Papa John's,"47-49 Talbot St, Mountjoy, Dublin 1, D01 H798",D01,H798,Family restaurant,3.9,492.0,53.351518,-6.250405
14,Star Pizza Dublin 1,"46 Talbot St, Mountjoy, Dublin, D01 HX49",D01,HX49,Pizza restaurant,4.2,973.0,53.351488,-6.250501
15,Chickn Lickn Dublin,"27 Liffey Street Lower, North City, Dublin, D0...",D01,FK58,American restaurant,3.9,263.0,53.347294,-6.263515
16,Nana's Restaurant African cuisine,"482B N Circular Rd, Mountjoy, Dublin 1, D01 P205",D01,P205,African restaurant,4.5,19.0,53.358859,-6.257759
17,Istanbel Buffet House,"90-91 Marlborough St, North City, Dublin, D01 ...",D01,XT82,Buffet restaurant,4.0,634.0,53.349956,-6.258222
18,Kimchi Hophouse,"160-161 Parnell St, Rotunda, Dublin, D01 Y4A7",D01,Y4A7,Korean restaurant,4.4,1715.0,53.353031,-6.260892
19,Laica Catering,"54b Dorset Street Lower, Northside, Dublin, D0...",D01,E278,Restaurant,4.8,38.0,53.360884,-6.259852
20,Wasabi Restaurant Sushi Bar,"77 Dorset Street Upper, Inns Quay, Dublin, D01...",D01,K3H4,Sushi restaurant,3.9,786.0,53.357139,-6.264567
21,Musashi Sushi Parnell Street,"179 Parnell St, Rotunda, Dublin 1, D01 YP60",D01,YP60,Sushi restaurant,4.5,507.0,53.351309,-6.264402
22,Wallace’s Asti,"15 Russell St, Drumcondra, Dublin 1, D01 VW02",D03,K6C4,Pizza restaurant,4.4,426.0,53.358857,-6.254582
23,Benvindo,"33 Foley St, Mountjoy, Dublin 1, D01 V2H7",D01,WA07,Brazilian restaurant,4.1,163.0,53.352445,-6.249780
24,Toto Ristorante Italiano,"8 Talbot St, North City, Dublin 1, D01 HC56",D01,E065,Italian restaurant,4.1,339.0,53.350393,-6.257075
25,Madina Street Food Co,"60 Mary St, North City, Dublin 1, D01 CD40",D01,CD40,Eclectic restaurant,3.8,1103.0,53.348624,-6.268231
26,Bleecker Street Cafe Bar,"68 Dorset Street Upper, Rotunda, Dublin 1, D01...",D01,KT22,New American restaurant,4.6,628.0,53.357180,-6.263914
27,The Italian Connection Restaurant,"95 Talbot St, North City, Dublin 1, D01 HR68",D01,HR68,Italian restaurant,4.2,495.0,53.350267,-6.256581
28,55 Sushi Bar,"143 Parnell St, Rotunda, Dublin 1, D01 AY02",D01,AY02,Sushi restaurant,3.7,412.0,53.353692,-6.259343
29,Il Fornaio IFSC,"Mayor Street Lower, International Financial Se...",D01,P3K7,Italian restaurant,4.3,471.0,53.349403,-6.243004
...,...,...,...,...,...,...,...,...,...
602,Lemongrass Restaurant,"The Arc Bar, Fonthill Rd, Yellow Walls, Lucan,...",D22,NaN,Asian restaurant,4.2,286.0,53.354293,-6.402827
603,Tamara,"18 Belgard Square W, Whitestown, Dublin 24",D24,NaN,Thai restaurant,3.9,177.0,53.286133,-6.376164
604,The India Gate Take Away,"Belgard Rd, Cookstown, Dublin",D24,NaN,Indian restaurant,4.1,78.0,53.295156,-6.370002
605,Chili Club,"1 Anne's Ln, Dublin 2, D02 Y052",D02,Y052,Thai restaurant,4.2,146.0,53.340874,-6.259646
606,Camile Thai Tallaght,"Village Green Centre, 22 Old Bawn Rd, Tallaght...",D24,YT10,Thai restaurant,4.2,258.0,53.286605,-6.361489
607,Bite Cafe,"36 Killakee Walk, Tymon South, Dublin 24, D24 ...",D24,YWR5,Restaurant,4.4,94.0,53.280793,-6.342446
608,The Woodlock Brasserie,"Citywest hotel, Lána Gairtéir, Saggart, Dublin...",D24,KF8A,Restaurant,4.2,103.0,53.285967,-6.446025
609,Kundan Tandoori,"Tallaght Retail Centre, Belgard Rd, Tallaght, ...",D24,NaN,Indian restaurant,4.3,132.0,53.287534,-6.365713
610,Hala Cafe,"Unit 2, Greenhills Business Centre, Tymon Nort...",D24,EK64,Restaurant,5.0,2.0,53.295376,-6.350056
611,Nando's Tallaght,"Belgard Square S Unit 317, The Square Shopping...",D24,NaN,Chicken restaurant,4.3,645.0,53.286777,-6.372454
612,Aussie Outback Tallaght,"7 Belgard Square W, Tallaght, Dublin",D24,NaN,Australian restaurant,4.3,613.0,53.286334,-6.375207
613,Pizza Mór,"Tallaght Retail Centre, High St, Tallaght, Dub...",D24,FF65,Pizza restaurant,4.0,87.0,53.287754,-6.364866
614,Graham O'Sullivan,"The Square, Tallaght, Dublin 24",D17,F785,Family restaurant,3.1,95.0,53.286664,-6.371556
615,Kay's Kitchen,"Unit 308, The Square, Oldbawn, Dublin 24",D17,F785,Restaurant,4.1,255.0,53.286328,-6.371058
616,Cosmo City Dinner,"Irishtown, Dublin 22",D04,P3Y0,Restaurant,4.0,226.0,53.352741,-6.394453
617,The Brass Fox Tallaght,"2 Tuansgate, Tallaght, Dublin",D24,NaN,Restaurant,3.9,163.0,53.288281,-6.369887
618,Tallaght Hospital Dining Room,"Tallaght Hospital, Belgard Square North, Cooks...",D24,NaN,Restaurant,5.0,3.0,53.290033,-6.377478
619,Kay’s Kitchen,"Unit 14, Jervis St, North City, Dublin",D01,NaN,Restaurant,4.2,272.0,53.348077,-6.266132
620,Kay's Kitchen,"Unit 122, Blanchardstown SC, Blanchardstown, D...",D15,NaN,Restaurant,4.1,704.0,53.392982,-6.389385
621,WOWBURGER Wicklow St.,"8 Wicklow St, Dublin 2, D02 AX90",D02,NaN,Restaurant,4.5,1132.0,53.342870,-6.260389
622,Main Street Pizza Tallaght,"2 Main Rd, Tallaght, Dublin, D24 X27P",D24,NaN,Restaurant,4.6,11.0,53.288318,-6.357175
623,Michie Sushi Rathcoole,"Avoca Rathcoole, Fitzmaurice Rd, Dublin",D24,NaN,Sushi restaurant,4.5,38.0,53.284322,-6.456234
624,Pizza Hut Delivery Tallaght,"Greenhills Retail Park, Unit 2a, Greenhills Rd...",D24,NaN,Pizza restaurant,3.7,92.0,53.293980,-6.354982
625,Kay's Kitchen,Donaghmede SC Donaghmede Dublin 13,D13,PX37,Restaurant,4.0,119.0,53.394696,-6.162198
626,The Egg Cafe,"Naas Rd, Saggart, Rathcoole, Co. Dublin",D24,NaN,Health food restaurant,4.3,113.0,53.284298,-6.456233
627,Ly Garden,"Saint Dominic's Shopping Centre, Unit 6, Millb...",D24,NaN,Chinese restaurant,4.1,152.0,53.285477,-6.355262
628,Carpe Diem @ Saggart Village,"The Forge Guesthouse, Mill Rd, Saggart, Co. Du...",D24,NaN,Mediterranean restaurant,4.4,223.0,53.280810,-6.445155
629,Top Tops,"Unit 8, Old Bawn Shopping Centre, 24 R114, Kil...",D24,NaN,Chinese restaurant,4.4,46.0,53.275622,-6.352917
630,China Moon,Dublin,D01,NaN,Chinese restaurant,3.9,62.0,53.274991,-6.344966
631,"The Good Catch, Dublin Port","3 Promenade Rd, North Dock, Dublin",D03,NaN,Seafood restaurant,3.1,10.0,53.354087,-6.212787

In [9]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst>0.5 and dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp>0.5 and wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.8)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [10]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [11]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(21594, 18)
(21594, 22)

In [12]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_Hotel and restaurant_final.xlsx', index = False)

### Cafe and pub

In [13]:
df = pd.read_excel("E:\\MCM\\Practicum docs\\Datasets\\final\\amenities_d01_24.xlsx", 'Cafe and pub')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,The Music Café Dublin,"Grattan House, 1 Wellington Quay, Temple Bar, ...",D02,DY95,Cafe,4.4,755.0,53.345302,-6.267496
1,Lemon Jelly Cafe,"Millennium Walkway, North City, Dublin 1, D01 ...",D01,Y027,Cafe,4.5,2209.0,53.347195,-6.265404
2,Cloud Cafe,"43 N Strand Rd, North Strand, Dublin 3, D03 E977",D03,H5W5,Cafe,4.6,386.0,53.357305,-6.243441
3,RóCo café,"13 Lord Edward St, Dublin, D02 Y278",D08,NaN,Cafe,4.6,135.0,53.343599,-6.269626
4,Scrumptious Café,"207 Philipsburgh Ave, Drumcondra, Dublin, D03 ...",D03,NR20,Cafe,4.6,108.0,53.371089,-6.238795
5,Blas Cafe,"26 King's Inns St, Rotunda, Dublin 1, D01 P2W7",D01,P2W7,Cafe,4.6,302.0,53.351312,-6.267582
6,Ebb & Flow Coffee,"56 Clontarf Rd, Northside, Dublin 3, D03 YN93",D03,YN93,Cafe,4.5,263.0,53.362728,-6.218209
7,Lily's Café,"3A Cavendish Row, Rae Cavendish, Rotunda, Dubl...",D01,NaN,Cafe,4.2,293.0,53.352901,-6.261394
8,Cocobrew,"5 Bedford Row, Temple Bar, Dublin, D02 E393",D02,E393,Cafe,4.6,203.0,53.346026,-6.261925
9,Tillies Cafe,"18 St Gabriel's Rd, Clontarf East, Dublin 3, D...",D03,VN29,Cafe,4.2,174.0,53.365000,-6.183889
10,Cobalt Cafe & Gallery,"16 N Great George's St, Rotunda, Dublin 1, D01...",D01,W2X9,Art cafe,4.2,82.0,53.354301,-6.260770
11,Shoe Lane Coffee (Tara Street),"7 Tara St, Dublin 2, D02 Y662",D02,Y662,Coffee shop,4.7,484.0,53.347165,-6.255280
12,The Pepper Pot,"59 William St S, Dublin 2, D02 CH28",D02,A625,Cafe,4.3,313.0,53.342199,-6.261688
13,Koffee and Kale,"21B Hill St, Rotunda, Dublin 1, D01 HY68",D01,HY68,Cafe,4.4,166.0,53.355775,-6.260709
14,Keoghs Cafe,"1 & 2 Trinity St, Dublin, D02 A440",D02,H684,Cafe,4.3,813.0,53.344033,-6.262204
15,Javaholics Coffee Company,"Merville Ave, Northside, Dublin 3, D03 XK52",D03,XK52,Cafe,4.6,168.0,53.363611,-6.234722
16,KC Peaches Cafe Dame Street,"54 Dame St, Temple Bar, Dublin, D02 X364",D02,X364,Cafe,4.1,649.0,53.344291,-6.264339
17,Food Room,"46 Clontarf Rd, Northside, Dublin 3, D03 AC84",D03,AC84,Cafe,4.0,382.0,53.363057,-6.219265
18,Starbucks,"1 College Green, Temple Bar, Dublin, D02 YT92",D02,YT92,Coffee shop,4.0,1368.0,53.344475,-6.261256
19,Esquires Coffee (Beside Savoy Cinema),"16 A Upper, O'Connell Street Upper, Dublin, D0...",D01,NY16,Coffee shop,4.3,315.0,53.351135,-6.260447
20,Insomnia Coffee Company,"181 Howth Rd, Clontarf East, Killester, Co. Du...",D05,NaN,Coffee shop,4.2,246.0,53.370774,-6.205826
21,The Tram Café,"Wolf Tone Square, Jervis St, North City, Dubli...",D01,W8C9,Cafe,4.5,602.0,53.348066,-6.266790
22,Network,"39 Aungier St, Dublin 2, D02 HP86",D02,HP86,Coffee shop,4.7,365.0,53.338643,-6.265836
23,"Quigleys Cafe, Bakery & Deli","Level 2, Belgard Square E, Tallaght, Dublin, D...",D24,X62W,Cafe,NaN,NaN,53.288392,-6.369190
24,Lunch!,"4 Lombard St E, Dublin, D02 VY96",D02,VY96,Cafe,4.5,100.0,53.344341,-6.248970
25,Crosscare Community Cafe,"2 Dunne St, Northside, Dublin, D01 A9X5",D01,A9X5,Cafe,4.2,19.0,53.356135,-6.248235
26,Kennedy's Food Store,"5 Fairview Strand, Northside, Dublin 3, D03 W5H0",D03,W5H0,Cafe,4.4,376.0,53.362863,-6.237181
27,Starbucks Stephens Green,"Stephen Court, GF1, St Stephen's Green, Dublin...",D02,N960,Coffee shop,4.0,1004.0,53.339322,-6.257511
28,TJ's Coffee Bar,"79 Parnell St, Rotunda, Dublin, D01 W3Y7",D01,W3Y7,Cafe,4.7,61.0,53.352749,-6.260734
29,Kennedy's Food Store,"196 Clontarf Rd, Clontarf East, Dublin 3, D03 ...",D03,X2H4,Cafe,4.4,282.0,53.359190,-6.195906
...,...,...,...,...,...,...,...,...,...
586,Java Republic,"510 NW Business Park, Ballycoolen, Dublin, D15...",D15,NaN,Cafe,4.4,267.0,53.412766,-6.346519
587,Kavanaghs Pub Rathfarnham,"39 Main St, Rathfarnham, Dublin, D14 P6CO",D14,NaN,Pub,4.3,30.0,53.298428,-6.285526
588,The 51 Bar,"51 Haddington Rd, Dublin 4, D04 FD83",D04,FD83,Sports bar,4.3,956.0,53.334660,-6.242472
589,The Wine & Tapas Bar At The Old Orchard,"74 Butterfield Ave, Rathfarnham, Dublin, D14 RF96",D14,RF96,Tapas bar,4.5,68.0,53.294688,-6.299247
590,The Carpenter,"Carpenterstown Road, Northside, Dublin, D15 YD63",D15,YD63,Pub,4.3,920.0,53.371946,-6.389071
591,The Black Wolf-Beer & Food Co,"Main St, Blanchardstown Village, Dublin, D15 V20W",D15,V20W,Gastropub,4.2,781.0,53.385909,-6.374389
592,Dundrum House,"57 Main St, Dundrum, Dublin 14",D14,X0T8,Pub,4.4,704.0,53.289390,-6.243334
593,Eagle House Dundrum,"Main St, Dundrum, Dublin",D14,NaN,Pub,3.8,120.0,53.289053,-6.243177
594,Myos,"Castleknock Rd, Castleknock, Dublin 15",D15,K3HN,Irish pub,3.7,339.0,53.372857,-6.362510
595,The Great Wood,"Westend Shopping Park, Blanchardstown, Dublin",D15,NaN,Pub,4.0,2574.0,53.389184,-6.388901
596,Clonsilla Inn,"Weavers Row, Clonsilla, Dublin",D15,C678,Pub,4.3,876.0,53.382392,-6.407795
597,The Strawberry Hall,"Lower Rd, Astagob, Dublin 20, D20 RH59",D20,RH59,Pub,4.6,421.0,53.362341,-6.385715
598,Salmon's Public House,"Mountview Rd, Northside, Dublin",D15,NaN,Pub,4.0,220.0,53.390708,-6.406337
599,The Brock Inn,"North Rd, Broghan, Broughan, Co. Dublin",D11,NaN,Pub,4.5,1205.0,53.433135,-6.332599
600,Pifko Bar,"41 Usher's Quay, Dublin",D08,K1E8,Pub,4.4,918.0,53.346058,-6.280333
601,Buglers Ballyboden House,"Ballyboden Rd, Rathfarnham, Dublin",D14,NaN,Pub,4.2,413.0,53.284101,-6.295429
602,The Knocklyon Inn,"Knocklyon Rd, Knocklyon, Dublin",D16,NaN,Pub,4.1,48.0,53.286993,-6.327999
603,Scholars Pub,"Oldcourt Shopping Centre, Parklands Rd, Dublin 24",D24,NaN,Pub,4.3,668.0,53.274954,-6.344956
604,The Coach House Pub,"16 Ballinteer Ave, Ballinteer, Dublin",D16,HT65,Pub,4.3,470.0,53.276447,-6.249150
605,The Priorswood Inn,"Proirswood Shopping Centre, Clonshaugh Ave, Pr...",D17,XV48,Pub,4.2,43.0,53.403359,-6.207208
606,The Silver Granite,"Kennelsfort Rd Upper, Johnstown, Dublin 20, D2...",D20,KH67,Pub,3.4,394.0,53.350061,-6.377434
607,The Deadman’s Inn,"Lucan Rd Old, Curtis Stream, Palmerstown, Co. ...",D20,NaN,Irish pub,4.2,449.0,53.356036,-6.397637
608,Quinlan's - The Black Lion,"Orchard Rd, Clondalkin, Dublin 22",D22,NaN,Pub,4.4,651.0,53.321343,-6.393529
609,The Speaker Connolly,"Firhouse Rd, Tymon South, Dublin 24",D24,NaN,Gastropub,4.2,250.0,53.281920,-6.341048
610,The Swallows,"Deansrath Shopping Centre, St Cuthberts Rd, De...",D22,R5Y0,Pub,3.7,64.0,53.323596,-6.424749
611,McGettigans Cookhouse KingsWood,"Kingswood, Dublin",D24,NaN,Gastropub,4.3,535.0,53.300985,-6.418979
612,Grumpy McClaffertys,"The Plaza Complex, Belgard Square S, Tallaght,...",D24,NaN,Pub,4.1,49.0,53.285586,-6.367847
613,The Baurnafea House,"Main St, Rathcoole, Co. Dublin",D24,NaN,Pub,4.0,196.0,53.281205,-6.469071
614,The Horseshoe Bar,"27 St Stephen's Green, Dublin 2",D02,H529,Pub,4.6,17.0,53.338997,-6.255904
615,O'Dwyer's Bar & Grill,"Strand Rd, Burrow, Portmarnock, Co. Dublin",D13,NaN,Pub,4.3,570.0,53.420549,-6.137896

In [14]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst>0.5 and dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp>0.5 and wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.8)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [15]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [16]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(26057, 18)
(26057, 22)

In [17]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/final/score_Cafe and pub_final.xlsx', index = False)