In [1]:
import googlemaps
import pandas as pd
import re

In [10]:
gmaps=googlemaps.Client(key='AIzaSyA9Ld4Wi50mgGxWzP7fPvqx5ArYSGgSCJM')

In [11]:
import math

def distance(origin, destination):
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371 # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d

In [12]:
wakable_distance=gmaps.distance_matrix((53.30297694,-6.217174),(53.30297694,-6.236494911),mode='walking',transit_routing_preference='less_walking')
print(wakable_distance)
print(wakable_distance['rows'][0]['elements'][0]['distance']['text'])

{'destination_addresses': ['76 White Oaks, Friarland, Dublin, Ireland'], 'origin_addresses': ['UCD Glenomena Residences, Belfield, Dublin, Ireland'], 'rows': [{'elements': [{'distance': {'text': '1.9 km', 'value': 1947}, 'duration': {'text': '24 mins', 'value': 1449}, 'status': 'OK'}]}], 'status': 'OK'}
1.9 km

In [5]:
df1 = pd.read_csv('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\daftsale_31stmay.csv')

In [6]:
df1

,Location,Area,Area code,Price(in Euros),House_type,Beds,Bathroom,Area_code,latitude,longitude,floor_area,Entered,Views
0,1 Kirkpatrick House|| Spencer House|| IFSC|| D...,Dublin 1,D01,285000,Apartment for sale,1,1,D00,53.350082,-6.238685,42.100,31.05.2020,2108.0
1,109 Parnell Street|| Dublin 1,Dublin 1,D01,220000,Apartment for sale,1,1,D01,53.353609,-6.256895,35.000,10.05.2020,2534.0
2,11 Mountjoy Parade|| Dublin 1,Dublin 1,D01,349950,Terraced House,2,1,D01,53.358588,-6.252270,91.000,27.05.2020,3063.0
3,12 Rutland Cottages|| Dublin 1,Dublin 1,D01,235000,Terraced House,2,1,D01,53.355073,-6.251607,64.000,29.05.2020,7462.0
4,127 Scarriff House|| Custom House Square|| Dub...,Dublin 1,D01,350000,Apartment for sale,2,1,D01,53.349712,-6.241361,59.000,28.05.2020,1883.0
5,14 Abbey Court|| Irish Life|| Lower Abbey Stre...,Dublin 1,D01,235000,Apartment for sale,1,1,D00,53.349259,-6.255467,45.000,31.05.2020,10311.0
6,14 Capel Street|| Dublin 1,Dublin 1,D01,1300000,Terraced House,4,4,D01,53.346906,-6.268017,393.000,21.05.2020,11529.0
7,14 Gandon Hall|| Gardiner Street|| Dublin 1,Dublin 1,D01,250000,Apartment for sale,1,0,D01,53.352508,-6.270212,90.000,31.05.2020,1715.0
8,14 Spencer House|| Custom House Square|| IFSC|...,Dublin 1,D01,370000,Apartment for sale,2,2,D01,53.349209,-6.242093,75.000,30.05.2020,4866.0
9,147 Castleforbes Square|| Docklands|| Dublin 1,Dublin 1,D01,375000,Apartment for sale,2,1,D00,53.348516,-6.231471,70.100,27.11.2019,5008.0
10,19 Rutland Cottages|| Dublin 1,Dublin 1,D01,199000,Terraced House,1,1,D01,53.355048,-6.251370,32.100,29.05.2020,758.0
11,2 Block 7|| Clarion Quay|| Custom House Square...,Dublin 1,D01,280000,Apartment for sale,1,1,D01,53.348765,-6.244157,48.000,31.05.2020,5000.0
12,206 Ivy Exchange|| Parnell Street|| Dublin 1,Dublin 1,D01,265000,Apartment for sale,1,1,D00,53.352255,-6.263984,49.000,31.05.2020,3257.0
13,23 Malton House|| Custom House Square|| Dublin 1,Dublin 1,D01,350000,Apartment for sale,2,1,D01,53.349519,-6.245432,55.000,30.05.2020,4326.0
14,24 Portland Lock|| Portland Place|| Dublin 1,Dublin 1,D01,195000,Apartment for sale,1,1,D01,53.360984,-6.258146,267.600,29.05.2020,5570.0
15,25 Linenhall Street|| Smithfield|| Dublin 1,Dublin 1,D01,325000,Terraced House,2,1,D07,53.350494,-6.272810,55.000,28.05.2020,9014.0
16,25 Rutland Street Lower|| Dublin 1,Dublin 1,D01,440000,Terraced House,3,2,D01,53.354379,-6.251677,120.690,26.05.2020,5472.0
17,28 Quartiere Bloom|| Ormond Quay Lower|| Dublin 1,Dublin 1,D01,395000,Apartment for sale,2,1,D01,53.346544,-6.265002,74.000,06.04.2020,4357.0
18,28 Quartiere Bloom|| Ormond Quay Lower|| North...,Dublin 1,D01,395000,Apartment for sale,2,1,D01,53.346611,-6.265141,74.000,16.04.2020,1762.0
19,30 Kirkpatrick House|| Spencer Dock|| Dublin 1,Dublin 1,D01,300000,Apartment for sale,1,1,D01,53.349818,-6.237930,40.400,31.05.2020,1268.0
20,33 Portland Lock|| Portland Place|| Dublin 1,Dublin 1,D01,250000,Apartment for sale,2,1,D01,53.360874,-6.257766,61.000,29.05.2020,5461.0
21,39 Buckingham Street Lower|| Dublin 1,Dublin 1,D01,450000,End of Terrace House,4,1,D01,53.353152,-6.249412,180.000,28.05.2020,6813.0
22,39 Cloncurry House|| Spencer Dock|| IFSC|| Dub...,Dublin 1,D01,495000,Apartment for sale,2,2,D00,53.349365,-6.239463,94.000,31.05.2020,3791.0
23,4 Dargle House|| Custom House Square|| D01|| I...,Dublin 1,D01,395000,Apartment for sale,2,2,D00,53.349524,-6.243692,112.000,31.05.2020,3469.0
24,4 Summer Street North|| Dublin 1,Dublin 1,D01,395000,Terraced House,4,2,D01,53.356919,-6.252865,103.000,19.05.2020,2735.0
25,24 Willows Drive|| Clonsilla|| Clonsilla|| Dub...,Dublin 15,D15,300000,Semi-Detached House,3,3,D15,53.388724,-6.416441,83.000,29.05.2020,4656.0
26,41 The Millhouse|| Steelworks|| Foley street||...,Dublin 1,D01,325000,Apartment for sale,2,1,D00,53.352585,-6.250851,68.450,29.04.2020,4500.0
27,446 A|| North Circular Road|| Dublin 1,Dublin 1,D01,195000,Detached House,0,0,D00,53.359589,-6.261040,116.000,31.05.2020,6892.0
28,5 Valentia House|| Custom House Square|| Dublin 1,Dublin 1,D01,720000,Apartment for sale,3,3,D01,53.349464,-6.242919,114.000,31.05.2020,5432.0
29,504 Talbot Hall|| Irish Life Centre|| Talbot S...,Dublin 1,D01,240000,Apartment for sale,1,1,D00,53.350198,-6.256100,60.000,31.05.2020,4060.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2391,67 Ferncourt Green|| Ballycullen|| Dublin 24,Dublin 24,D24,379000,Semi-Detached House,3,3,D00,53.273110,-6.345373,66.900,31.05.2020,4394.0
2392,7 Beechdale Place|| Ballycullen|| Dublin 24,Dublin 24,D24,335000,Semi-Detached House,3,2,D00,53.270132,-6.335013,82.030,29.05.2020,2547.0
2393,7 Oakdale Grove|| Ballycullen|| Dublin 24,Dublin 24,D24,390000,Semi-Detached House,4,3,D24,53.271202,-6.339118,111.000,17.04.2020,1559.0
2394,7 Oakdale Grove|| Firhouse|| Dublin 24,Dublin 24,D24,390000,Semi-Detached House,4,3,D24,53.271069,-6.339237,111.000,31.05.2020,2454.0
2395,7 Old Court Close|| Firhouse|| Dublin 24,Dublin 24,D24,320000,Semi-Detached House,3,2,D24,53.274425,-6.349442,162.000,31.05.2020,7686.0
2396,7 Tallow Hall|| Belgard Square West|| Tallaght...,Dublin 24,D24,165000,Apartment for sale,1,1,D24,53.285975,-6.375938,129.000,29.05.2020,3951.0
2397,78 Woodlawn Park Drive|| Firhouse|| Dublin 24,Dublin 24,D24,430000,Semi-Detached House,3,2,D24,53.283073,-6.336963,169.000,31.05.2020,852.0
2398,80 Alpine Rise|| Belgard|| Tallaght|| Dublin 24,Dublin 24,D24,265000,Bungalow for sale,3,1,D24,53.296648,-6.387568,83.600,29.05.2020,3548.0
2399,87 Kiltipper Gate|| Tallaght|| Tallaght|| Dubl...,Dublin 24,D24,185000,Apartment for sale,2,2,D24,53.270741,-6.371885,96.650,29.05.2020,5114.0
2400,88 Suncroft Drive|| Tallaght|| Tallaght|| Dubl...,Dublin 24,D24,224950,Semi-Detached House,3,2,D24,53.282052,-6.408020,85.900,29.05.2020,1506.0
2401,9 Bolbrook Avenue|| Tallaght|| Dublin 24,Dublin 24,D24,249950,End of Terrace House,3,1,D24,53.286633,-6.341230,166.000,31.05.2020,3388.0
2402,9 Drumcairn Avenue|| Tallaght|| Dublin 24,Dublin 24,D24,199000,Terraced House,3,1,D24,53.288785,-6.397602,89.700,29.05.2020,5027.0
2403,9 Fernwood Close|| Tallaght|| Dublin 24,Dublin 24,D24,230000,Terraced House,3,1,D24,53.287029,-6.385336,33.000,31.05.2020,1305.0
2404,9 Parkhill Rise|| Kilnamanagh|| Tallaght|| Dub...,Dublin 24,D24,345000,Semi-Detached House,3,3,D24,53.300664,-6.366307,96.000,11.05.2020,1986.0
2405,9 Redwood Rise|| Kilnamanagh|| Tallaght|| Dubl...,Dublin 24,D24,320000,Semi-Detached House,3,1,D24,53.299663,-6.362265,105.200,10.03.2020,3487.0
2406,9 Swiftbrook Avenue|| Tallaght|| Tallaght|| Du...,Dublin 24,D24,199000,End of Terrace House,3,2,D24,53.285744,-6.406098,83.600,29.05.2020,1324.0
2407,90 Bancroft Park|| Tallaght|| Tallaght|| Dubli...,Dublin 24,D24,150000,Acre Site,1,7,D24,53.289889,-6.357383,95.300,27.02.2020,1565.0
2408,Apartment 1|| Block A|| Westend Gate|| Tallagh...,Dublin 24,D24,260000,Apartment for sale,2,2,D24,53.284715,-6.376575,71.000,28.05.2020,1069.0
2409,Apartment 117|| Block 2|| Priors Gate|| Tallag...,Dublin 24,D24,275000,Apartment for sale,2,2,D24,53.287305,-6.355918,70.000,22.05.2020,2675.0
2410,Apartment 119|| Exchange Hall|| The Exchange||...,Dublin 24,D24,190000,Apartment for sale,2,1,D24,53.290260,-6.374097,76.000,29.05.2020,8006.0
2411,Apartment 125A|| De Selby Park|| Tallaght|| Du...,Dublin 24,D24,165000,Apartment for sale,2,1,D24,53.276323,-6.411363,65.000,31.05.2020,8177.0
2412,Apartment 40|| Tymon Farm|| Tymon Lane|| Talla...,Dublin 24,D24,299950,Apartment for sale,4,3,D24,53.291103,-6.335590,86.000,15.05.2020,1153.0
2413,Apartment 69|| Alen Hall|| Belgard Square|| Ta...,Dublin 24,D24,172500,Apartment for sale,1,1,D24,53.286721,-6.375299,82.000,29.05.2020,2967.0
2414,Avonbeg Gardens|| Tallaght|| Dublin 24,Dublin 24,D24,242000,End of Terrace House,3,1,D24,53.285622,-6.350171,102.193,27.05.2020,2892.0
2415,Killininny Cottages|| Firhouse Road|| Firhouse...,Dublin 24,D24,450000,Semi-Detached House,3,1,D24,53.281559,-6.342813,61.000,29.05.2020,1672.0
2416,105 Alderwood Avenue.|| D24C990|| Tallaght|| D...,Dublin 24,D24,229000,Terraced House,3,1,D24,53.287030,-6.382832,85.000,31.05.2020,1284.0
2417,116 Exchange Hall|| Tallaght|| Dublin 24,Dublin 24,D24,149000,Apartment for sale,1,1,D24,53.290072,-6.374013,76.000,31.05.2020,8931.0
2418,33 Raheen Road|| Tallaght|| Tallaght|| Dublin 24,Dublin 24,D24,255000,Semi-Detached House,3,2,D24,53.285035,-6.388270,100.270,30.04.2020,2843.0
2419,9 De Selby Drive|| Tallaght|| Dublin 24,Dublin 24,D24,250000,End of Terrace House,3,2,D24,53.277114,-6.409177,86.960,31.05.2020,3200.0
2420,Apartment 66|| Block C|| Westend Gate|| Tallag...,Dublin 24,D24,150000,Apartment for sale,1,1,D24,53.285034,-6.376462,45.000,29.05.2020,2771.0

### Post office and mailing

In [8]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Post office and mailing')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,"An Post, General Post Office","O'Connell Street Lower, North City, Dublin 1",D01,TX31,Post office,4.4,347.0,53.349349,-6.260721
1,Post Delivery Services Unit,"Bannow Rd, Northside, Dublin, D07 AX73",D07,AX73,Post office,3.5,24.0,53.370494,-6.292479
2,St. Andrew's St. Post Office,"19 St Andrew's St, Dublin, D02 C966",D02,T382,Post office,4.0,22.0,53.343816,-6.261424
3,Cabra Post Office,"40 Faussagh Rd, Northside, Dublin, D07 DFK0",D11,P3Y0,Post office,4.8,9.0,53.364802,-6.286852
4,Usher's Quay Post Office,"5 Usher's Quay, Dublin 8, D08 W449",D08,W449,Post office,2.9,9.0,53.345325,-6.276420
5,Drumcondra Post Office,"153 Drumcondra Rd Lower, Drumcondra, Dublin 9,...",D09,WN56,Post office,4.3,10.0,53.367507,-6.255252
6,Ashtown Post Office,"23 Ashtown Grove, Ashtown, Dublin 7, D07 E4EK",D07,E4EK,Post office,5.0,4.0,53.370557,-6.323507
7,Ormond Quay Upper Post Office,"The Ormond Building, 31-36 Ormond Quay Upper, ...",D07,E624,Post office,4.0,5.0,53.345728,-6.271606
8,Post Office,"37 Parkgate St, Stoneybatter, Dublin, D08 K5C0",D08,K5C0,Post office,4.0,5.0,53.348217,-6.294479
9,An Post Lomond Avenue - Sorting Office,"18 Lomond Ave, Drumcondra, Dublin, D03 KW58",D03,X9X9,Post office,2.9,23.0,53.366500,-6.241343
10,Dorset street post office,"59 Dorset Street Upper, Rotunda, Dublin 1, D01...",D01,DC95,Post office,4.0,3.0,53.356628,-6.264363
11,Earlsfort Terrace Post Office,"1A Earlsfort Terrace, Saint Kevin's, Dublin 2",D02,C950,Post office,5.0,1.0,53.335719,-6.257246
12,Finglas South Post Office,"Clearwater Shopping Centre, Finglas Rd, Fingla...",D11,NaN,Post office,3.9,10.0,53.383193,-6.296470
13,Permanently Closed - An Post Berkeley Road Pos...,"14 Berkeley Rd, Phibsborough, Dublin, D07 VE82",D07,VE82,Post office,4.3,6.0,53.358806,-6.269857
14,Post Office Kevin Street Upper,"Cathedral Court, New St S, The Liberties, Dubl...",D08,PN81,Post office,5.0,2.0,53.337310,-6.272846
15,Inchicore Post Office,"212 Spa Rd, Inchicore, Dublin",D08,X6N4,Post office,3.8,8.0,53.339208,-6.319934
16,Post Office,"408/410 Collins Ave, Northside, Dublin 9, D09 ...",D09,NaN,Post office,4.3,3.0,53.381758,-6.241394
17,Summerhill Post Office,"Summerhill Parade, Ballybough, Dublin 11",D03,NaN,Post office,5.0,1.0,53.357377,-6.248631
18,Ballygall Road East Post Office,"1 Fitzmaurice Rd, Glasnevin, Dublin, D11 FYH3",D11,FYH3,Post office,4.7,3.0,53.382728,-6.276846
19,An Post,"Rutland Pl, Rotunda, Dublin 1",D01,FP66,Post office,2.1,11.0,53.354260,-6.262082
20,Ballyfermot Post Office,"199 Decies Rd, Decies, Dublin 10, D10 RD36",D10,RD36,Post office,3.4,7.0,53.339378,-6.343812
21,Rialto Post Office,"Centra, 455-457 S Circular Rd, Rialto, Dublin ...",D08,NaN,Post office,4.8,4.0,53.336043,-6.298468
22,Post Office,"McGoverns Corner, Cork St, The Liberties, Dublin",D08,A7K3,Post office,3.1,9.0,53.337214,-6.286746
23,Post Office,"Unit 9, Palmerstown Shopping Centre, Kennelsfo...",D20,W020,Post office,3.2,5.0,53.350152,-6.380185
24,Ringsend Post Office,"Google Building Gordon House, Barrow St, Dubli...",D04,EA27,Post office,3.8,12.0,53.340222,-6.236111
25,Leonard's Corner Post Office,Clanbrassil Street Upper Clanbrassil Street Up...,D08,KA07,Post office,2.5,14.0,53.332132,-6.275025
26,Upper Erne Street Post Office,"24, Erne Street Upper, Dublin 2",D02,X620,Post office,4.2,17.0,53.342977,-6.244838
27,Santry Omni Shopping Centre Post Office,"Omni Park Shopping Centre, Swords Rd, Whitehal...",D09,Y6K4,Post office,3.8,6.0,53.391624,-6.248465
28,Post Office,"123 Old County Rd, Crumlin, Dublin 12, D12 AF83",D12,AF83,Post office,2.8,6.0,53.327398,-6.305586
29,Ballsbridge Post Office,"Shelbourne Rd, Dublin, D04 E038",D04,E038,Post office,3.1,13.0,53.330216,-6.231705
...,...,...,...,...,...,...,...,...,...
105,Edenmore Post Office,"Edenmore Shopping Centre, Edenmore Park, Edenm...",D05,A586,Post office,4.0,8.0,53.388356,-6.182659
106,Shelbourne House,"Shelbourne Rd, Dublin 4, D04 H6F6",D04,H6F6,Post office,4.0,13.0,53.332621,-6.232200
107,An Post Parcel Depot,"St Agnes Rd, Kimmage, Crumlin, Co. Dublin, D12...",D12,WK5A,Post office,2.7,3.0,53.320429,-6.315779
108,Post box,"4 Lock-Keepers Walk, Ashtown, Dublin, D15 H2N0",D15,H2N0,Mailing service,NaN,NaN,53.376577,-6.316500
109,KC Confectionery,"25 Henry St, North City, Dublin 1, D01 XR79",D01,XR79,Post office,NaN,NaN,53.349482,-6.261442
110,Jobstown Post Office,"Post Office, D24 H67T, Kiltalown Way, Jobstown...",D24,NaN,Post office,3.7,3.0,53.278075,-6.400408
111,An Post Delivery Unit,"Ballyogan Rd, Sandyford, Dublin, D18 E098",D18,E098,Post office,4.0,4.0,53.255503,-6.188582
112,An Post Howth,"8 Main St, Howth, Dublin, D13 T1F3",D13,NaN,Post office,NaN,NaN,53.385556,-6.065300
113,Glenview Post Office,"Glenview Park, Tymon South, Tallaght, Co. Dublin",D24,NaN,Post office,5.0,1.0,53.288735,-6.344126
114,Lawrences,"24 Henry St, North City, Dublin 1, D01 P642",D01,P642,Post office,NaN,NaN,53.349454,-6.261607
115,CityPOST,"Greenogue Business Park, Jordanstown, Dublin, ...",D24,NaN,Post office,1.5,16.0,53.300990,-6.475782
116,Clonsilla post office,"Saint Anthony, 1 Orchard Ave, Clonsilla, Dubli...",D15,W7RK,Post office,NaN,NaN,53.382801,-6.409617
117,Kennelsfort rd post box,"Redcowfarm, Dublin",D01,NaN,Post office,NaN,NaN,53.353715,-6.374814
118,Drumcondra Edwardian Pillarbox,"Drumcondra, Dublin",D09,NaN,Post office,NaN,NaN,53.363115,-6.258364
119,An Post,"108 Greenlea Rd, Terenure, Dublin 6W, Co. Dubl...",D6W,W710,Post office,NaN,NaN,53.307485,-6.299920
120,St Mobhi Post Office,"82b Ballymun Rd, Ballygall, Dublin 9, D09 PX93",D09,A4N8,Post office,4.3,6.0,53.379453,-6.266410
121,Shankill Post Office,"Violet House, Dublin Rd, Shanganagh, Dublin 18",D18,CX97,Post office,4.3,7.0,53.231225,-6.124263
122,Post Office,"Castleknock, Dublin",D15,NaN,Post office,3.2,6.0,53.373522,-6.361013
123,Merrion Row Post Office,"16 Merrion Row, Dublin, D02 DY84",D02,DY84,Post office,4.0,4.0,53.338159,-6.254068
124,Jobstown Post Office,"Post Office, D24 H67T, Kiltalown Way, Jobstown...",D24,NaN,Post office,3.7,3.0,53.278082,-6.400501
125,Finglas Post Office,"Finglas Rd, Ballygall, Dublin 11, D11 V620",D11,PA00,Post office,3.7,3.0,53.389089,-6.297736
126,FedEx Station,"Unit 3a, Airways Industrial Estate, Dublin",D17,NaN,Mailing service,2.8,111.0,53.406107,-6.237418
127,Donaghmede Post Office,"Donaghmede Shopping Centre, Grange Rd, Grange,...",D13,NaN,Post office,4.3,3.0,53.395022,-6.162014
128,Cabinteely Post Office,"Bray Rd, Cabinteely, Dublin",D18,NaN,Post office,3.9,16.0,53.261088,-6.150642
129,Aylesbury Post Office,"Church Grove, Oldbawn, Aylesbury, Co. Dublin, ...",D24,NaN,Post office,5.0,1.0,53.275939,-6.366794
130,AN POST Kilnamanagh Shopping Centre,"Kilnamanagh Shopping Centre, Mayberry Rd, Kiln...",D24,NaN,Post office,4.0,4.0,53.299562,-6.359797
131,An Post Depot,"St Margaret's Rd, Charlestown, Finglas, Co. Du...",D11,NaN,Post office,1.0,1.0,53.403724,-6.303870
132,An Post Delivery Office,"36, Fonthill Business Park, Fonthill Rd, Yello...",D22,NaN,Mailing service,4.0,152.0,53.350590,-6.408710
133,An Post Baggot Street Upper Post Office,"13 Baggot Street Upper, Dublin, D04 W7K5",D04,W7K5,Post office,5.0,1.0,53.333581,-6.244781
134,An Post,"Bayside Shopping Centre, Bayside Square E, Nor...",D13,C2F6,Post office,3.8,5.0,53.388278,-6.140610

In [13]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.2)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [14]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [15]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(2712, 19)
(2712, 23)

In [17]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/post_office_final.xlsx', index = False)

### Train and tram

In [18]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Train and tram')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Charlemont Luas Stop,"2 Grand Parade, Saint Kevin's, Dublin, D06 CX34",D06,CX34,Tram stop,4.3,67.0,53.330925,-6.258834
1,Heuston,"Heuston Station, St John's Rd W, Dublin",D08,NaN,Train station,4.2,244.0,53.346185,-6.293492
2,Heuston,"Saint James' (part of Phoenix Park), Dublin",D08,NaN,Tram stop,4.1,7.0,53.346651,-6.291903
3,Saggart Luas Stop,"Fortunestown, Saggart, Co. Dublin",D24,NaN,Tram stop,3.8,14.0,53.284641,-6.437762
4,Connolly Station,"1 Amiens St, North Dock, Dublin",D01,AN81,Transit stop,3.9,275.0,53.351526,-6.249678
5,Dawson,Dublin,D01,NaN,Tram stop,4.3,9.0,53.342190,-6.258048
6,Busáras Luas Stop,"Mountjoy, Dublin 1",D07,PK20,Tram stop,3.6,17.0,53.350085,-6.251451
7,Cheeverstown Luas Stop,"Tallaght, Dublin",D24,NaN,Tram stop,4.7,3.0,53.291036,-6.406877
8,Broombridge,"7 Broombridge Rd, Cabra West, Dublin, D07 N4X0",D07,N4X0,Train station,3.5,95.0,53.372671,-6.299323
9,Grand Canal Dock,"Barrow St, Dublin",D04,NaN,Train station,4.3,38.0,53.339610,-6.237840
10,Brides Glen,"Cherrywood, Co. Dublin",D22,NaN,Tram stop,3.0,9.0,53.241871,-6.142783
11,Rialto Luas Stop,"Saint James' (part of Phoenix Park), Dublin 8",D08,NaN,Tram stop,3.5,6.0,53.337878,-6.297223
12,Lansdowne Road,"Lansdowne Rd, Dublin",D04,V3K1,Train station,3.9,26.0,53.333816,-6.228956
13,Fortunestown Luas Stop,"Tallaght, Dublin",D24,NaN,Tram stop,4.6,7.0,53.284212,-6.424610
14,Fettercairn Luas Stop,"Tallaght, Dublin",D24,NaN,Tram stop,4.0,6.0,53.293565,-6.395579
15,Suir Road Luas Stop,"Drimnagh, Dublin",D12,NaN,Tram stop,3.4,10.0,53.336592,-6.307231
16,St.Stephen's Green,Dublin,D01,NaN,Tram stop,4.3,27.0,53.339077,-6.261241
17,Clondalkin / Fonthill,"Cappagh, Dublin",D11,NaN,Train station,3.3,17.0,53.333417,-6.406295
18,Smithfield,"Smithfield, Dublin",D07,NaN,Tram stop,4.5,15.0,53.347096,-6.277790
19,Kilbarrack,"Briarfield Rd, Raheny - Foxfield, Dublin, D05 ...",D05,KP62,Train station,3.4,37.0,53.387491,-6.160956
20,Shankill Station,"Rathsallagh Dr, Shankill, Dublin, D18 E6H7",D18,E6H7,Train station,3.5,15.0,53.236490,-6.117114
21,Stillorgan,"Mulchanstown, Dublin",D01,NaN,Tram stop,3.9,7.0,53.279345,-6.210254
22,Raheny,"Clontarf East, Dublin",D03,NaN,Train station,4.0,18.0,53.381404,-6.175956
23,The Point,"North Dock, Dublin 1",D04,E0F9,Tram stop,4.2,9.0,53.348348,-6.229184
24,Killester,"Middle Third, Northside, Dublin 5",D05,P927,Train station,3.6,14.0,53.372959,-6.204667
25,Museum Luas Stop,"Stoneybatter, Dublin",D07,NaN,Tram stop,4.4,5.0,53.347827,-6.286734
26,Sydney Parade,"Sydney Parade Ave, Dublin 4, D04 Y1Y6",D04,Y1Y6,Train station,4.1,24.0,53.320296,-6.210956
27,Harmonstown,"Harmonstown Rd, Harmonstown, Dublin",D05,NaN,Train station,4.1,19.0,53.378472,-6.192312
28,George's Dock,"North Dock, Dublin 1",D04,E0F9,Tram stop,4.3,6.0,53.349474,-6.247568
29,Bayside,"13 Sutton Park, Northside, Dublin 13, D13 T921",D13,F3A8,Train station,3.3,76.0,53.391538,-6.136818
...,...,...,...,...,...,...,...,...,...
62,Laughanstown,"Laughanstown, Co. Dublin",D18,NaN,Tram stop,4.0,4.0,53.250635,-6.154947
63,Kylemore,"Inchicore, Dublin 8",D08,DE0V,Tram stop,3.0,11.0,53.326634,-6.343807
64,Kingswood Luas Stop,"Kilnamanagh, Dublin",D24,NaN,Tram stop,3.6,8.0,53.303657,-6.365256
65,Kingswood,"Kilnamanagh, Dublin",D24,NaN,Tram stop,NaN,NaN,53.303691,-6.365507
66,Kilmacud Luas Stop,"Kilmacud West, Dublin",D14,NaN,Tram stop,3.1,8.0,53.282962,-6.223885
67,Kilmacud,"Kilmacud West, Dublin",D14,NaN,Tram stop,NaN,NaN,53.282910,-6.224107
68,Harcourt,"Saint Kevin's, Dublin",D18,Y2R7,Tram stop,3.4,14.0,53.333386,-6.262633
69,Grangegorman Luas Stop,"Arran Quay, Dublin",D07,NaN,Tram stop,4.8,5.0,53.357197,-6.277344
70,Goldenbridge Luas Stop,"Drimnagh, Dublin",D12,NaN,Tram stop,5.0,4.0,53.335867,-6.313580
71,Glencairn Luas Stop,"Sandyford, Dublin",D18,NaN,Tram stop,4.2,11.0,53.266268,-6.209925
72,Glencairn,"Sandyford, Dublin",D18,NaN,Tram stop,NaN,NaN,53.266325,-6.210132
73,Fortunestown,"Tallaght, Dublin",D24,NaN,Tram stop,4.6,7.0,53.284210,-6.424610
74,Fettercairn,"Whitehall, Dublin",D09,NaN,Tram stop,4.8,4.0,53.293318,-6.395875
75,Fatima,"Saint James' (part of Phoenix Park), Dublin 8",D08,NaN,Tram stop,5.0,2.0,53.338417,-6.292773
76,Dundrum,"Dundrum, Dublin",D14,NaN,Tram stop,4.5,16.0,53.292426,-6.245119
77,Dominick Luas Stop,"Rotunda, Dublin 1",D01,NaN,Tram stop,4.0,4.0,53.351345,-6.265547
78,Cowper,"Ranelagh, Dublin",D06,NaN,Tram stop,3.3,4.0,53.316393,-6.253442
79,Cookstown,"Cookstown, Dublin",D24,NaN,Tram stop,4.6,5.0,53.293293,-6.384085
80,Cherrywood Luas Stop,"Cherrywood, Co. Dublin",D22,NaN,Tram stop,2.7,11.0,53.245388,-6.145823
81,Cheeverstown,"Jobstown, Dublin",D24,NaN,Tram stop,NaN,NaN,53.291006,-6.406491
82,Charlemont,"Ranelagh, Dublin",D06,NaN,Tram stop,4.0,11.0,53.330615,-6.258536
83,Central Park,"Carmanhall and Leopardstown, Dublin",D18,NaN,Tram stop,3.5,15.0,53.270176,-6.203824
84,Carrickmines,"Brenanstown, Dublin",D18,NaN,Tram stop,4.1,19.0,53.254000,-6.170000
85,Bluebell,"Inchicore, Dublin 8",D08,DE0V,Tram stop,4.5,8.0,53.329287,-6.333732
86,Blackhorse Luas Stop,"Inchicore, Dublin 8",D08,DE0V,Tram stop,2.7,10.0,53.334263,-6.327534
87,Belgard Luas Stop,"Cookstown, Dublin",D24,NaN,Tram stop,3.8,11.0,53.298921,-6.375407
88,Belgard,"Cookstown, Dublin",D24,NaN,Tram stop,5.0,2.0,53.299292,-6.375066
89,Beechwood,"Ranelagh, Dublin",D06,NaN,Tram stop,4.8,8.0,53.320850,-6.254563
90,Ballyogan Wood,"Sandyford, Dublin",D18,NaN,Tram stop,3.0,11.0,53.255069,-6.184418
91,Balally,"Drummartin, Dublin",D14,NaN,Tram stop,4.4,20.0,53.286055,-6.236711

In [19]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [20]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [21]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(1499, 19)
(1499, 23)

In [22]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/train_tram_final.xlsx', index = False)

### Garda

In [24]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Garda')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,An Garda Síochána Headquarters,"Phoenix Park, Northside, Dublin, D08 HN3X",D08,A7X8,Police,4.0,6.0,53.354579,-6.301498
1,Ballyfermot Garda Station,"Rossmore Ave, Drumfinn, Dublin",D10,NaN,Police station,4.1,8.0,53.344754,-6.358053
2,Ballymun Garda Station,"Ballymun Rd, Northside, Dublin",D09,NaN,Traffic police station,4.5,12.0,53.394374,-6.263922
3,Bridewell Garda Station,"Chancery St, Northside, Dublin",D07,NaN,Civil police,5.0,5.0,53.347066,-6.274349
4,Cabra Garda Station,"Nephin Rd, Cabra West, Dublin, D07 XN61",D07,XN61,Civil police,3.4,14.0,53.365012,-6.307702
5,Clontarf Garda Station,"4 Clontarf Rd, Clontarf, Dublin",D03,V4K8,Police station,4.0,6.0,53.363411,-6.220210
6,Coolock Garda Station,"5 Oscar Traynor Rd, Kilmore, Coolock, Co. Dublin",D17,NaN,Civil police,3.2,11.0,53.390335,-6.201095
7,Crumlin Garda Station,"23 St Agnes Rd, Crumlin, Dublin, D12 C588",D12,C588,Police station,3.7,6.0,53.319569,-6.314994
8,Donnybrook Garda Station,"43 Donnybrook Rd, Ranelagh, Dublin 4, D04 XC78",D04,XC78,Police station,2.3,3.0,53.321720,-6.235774
9,Dundrum Garda Station,"Kilmacud Rd Upper, Dundrum, Dublin",D14,NaN,State police,3.7,11.0,53.289491,-6.242477
10,Finglas Garda Station,"Finglas North, Dublin",D11,NaN,State police,3.3,12.0,53.389656,-6.306434
11,Fitzgibbon Street Garda Station,"1 Fitzgibbon St, Mountjoy, Dublin 1, D01 R2K5",D01,A5Y9,Police department,4.3,3.0,53.357832,-6.255665
12,Garda Shankill,"Dorney Ct, Shanganagh, Dublin",D18,NaN,Police station,3.9,8.0,53.233488,-6.120737
13,Garda Station,"Cabinteely Garda Station, Bray Rd, Kilbogget, ...",D18,FX56,Police department,4.8,4.0,53.260790,-6.150646
14,Howth Garda Station,"Dunbo Hill, Howth, Dublin",D13,NaN,Police department,2.5,2.0,53.387380,-6.068886
15,Irishtown Garda Station,"57 Irishtown Rd, Dublin",D04,CA43,Federal police,4.3,8.0,53.338111,-6.223035
16,Kevin Street District Garda Station,"41 Kevin Street Upper, Wood Quay, Dublin",D08,R83C,Police station,3.5,15.0,53.338328,-6.269445
17,Kilmainham Garda Station,"High Road, Kilmainham Ln, Kilmainham, Dublin 8",D08,N9WT,Police department,4.0,8.0,53.341948,-6.304575
18,Mountjoy Garda Station,"399 N Circular Rd, Northside, Dublin 7, D07 CH02",D07,CH02,Police station,2.7,11.0,53.360530,-6.266834
19,Pearse Street Garda Station,"1-6 Pearse St, Dublin 2, D02 W289",D02,W289,Police station,3.1,43.0,53.345689,-6.256194
20,Police Station,"Strandville Avenue East, Clontarf West, Dublin",D03,NaN,Police station,NaN,NaN,53.363390,-6.220214
21,Raheny District Garda Station,"All Saints Rd, Clontarf East, Dublin",D05,NaN,Civil police,4.2,20.0,53.378845,-6.178075
22,Rathcoole Garda Station,"Main St, Rathcoole, Co. Dublin",D24,NaN,Civil police,3.0,2.0,53.281814,-6.464697
23,Rathfarnham Garda Station,"Butterfield Ave, Rathfarnham, Dublin",D14,NaN,Police station,3.7,6.0,53.297410,-6.288549
24,Rathmines Garda Station,"196 Rathgar Rd, Rathmines, Dublin 6, D06 YW20",D06,NaN,Police station,3.9,8.0,53.321341,-6.266999
25,Ronanstown Garda Station,"St Ronans Avenue, Clondalkin, Dublin",D22,NaN,Civil police,2.8,9.0,53.337878,-6.406166
26,Santry Garda Station,"Shanowen Rd, Whitehall, Dublin 9",D09,NaN,Police station,3.1,9.0,53.389963,-6.250635
27,Store Street Garda Station,"4-6 Store St, Mountjoy, Dublin 1, D01 W773",D01,W773,Police department,3.2,26.0,53.350467,-6.252193
28,Sundrive Road Garda Station,"110 Crumlin Rd, Crumlin, Dublin",D12,EP02,Police academy,5.0,1.0,53.330200,-6.298698
29,Tallaght Garda Station,"Tallaght, Dublin",D24,NaN,Police department,1.8,22.0,53.286807,-6.367589
30,Terenure Garda Station,"30-32 Terenure Rd W, Terenure, Dublin 6W, Co. ...",D6W,XT44,Police station,2.4,7.0,53.309743,-6.288021

In [25]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<2.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<2.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.4)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [26]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [27]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(2812, 19)
(2812, 23)

In [28]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/garda_final.xlsx', index = False)

### Bank

In [29]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Bank')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,AIB,"Carrickmines, Co. Dublin",D18,NaN,Bank,3.9,23.0,53.250958,-6.182087
1,Aareal Bank AG Dublin Branch,"The Gables, Torquay Rd, Foxrock, Dublin 18",D18,A2N7,Bank,NaN,NaN,53.267086,-6.184409
2,Bank of America Merrill Lynch Limited,"Block D Central Park, Carmanhall and Leopardst...",D18,N924,Bank,4.7,11.0,53.271594,-6.203083
3,Grenke,"Suite 306, Q House, Furze Rd, Sandyford Busine...",D18,PN30,Financial institution,1.0,1.0,53.274049,-6.215030
4,Allied Irish Banks Plc,"Unit 33 Blackthorn Road, Sandyford, Dublin",D18,NaN,Bank,2.3,6.0,53.277236,-6.206496
5,Bank of Ireland Sandyford,"The Plaza, Beacon South Quarter, Dublin 18, D1...",D18,F729,Bank,3.0,16.0,53.277819,-6.217460
6,Bank of Ireland,"Main St, Rathcoole, Co. Dublin",D24,NaN,Financial institution,4.4,7.0,53.281414,-6.471161
7,ING Wholesale Banking - ING European Financial...,"Level 6, .1 Block 4 Dundrum Town Centre, 16 Sa...",D16,NaN,Bank,NaN,NaN,53.286471,-6.239229
8,AIB Bank,"Village Green, Tallaght, Dublin 24",D24,NaN,Bank,3.4,22.0,53.287156,-6.361887
9,EBS Tallaght,"217/218, The Square, Belgard Square E, Tallagh...",D24,X62W,Financial institution,3.0,1.0,53.287239,-6.372258
10,permanent tsb,"8 Old Bawn Rd, Tallaght, Dublin 24, D24 HK35",D24,N1YH,Bank,2.7,15.0,53.287320,-6.362511
11,Bank of Ireland,"Priors Gate, Unit 4-6, Block 3, Greenhills Rd,...",D24,AR24,Financial institution,2.4,19.0,53.288040,-6.357276
12,Ulster Bank (Tallaght),"24 Main St, Tallaght, Dublin, D24 Y033",D24,HX2X,Bank,3.3,16.0,53.288058,-6.358718
13,Computershare Investor Services (Ireland) Limited,"3100 Lake Dr, Citywest Business Campus, Dublin...",D24,NaN,Financial institution,1.0,1.0,53.289108,-6.423414
14,Permanent TSB Dundrum,"Main St, Dundrum, Co. Dublin",D14,NaN,Bank,2.9,13.0,53.290324,-6.244428
15,AIB Bank,"Cookstown, Dublin",D24,NaN,Bank,5.0,1.0,53.290721,-6.377826
16,AIB Bank,"10 Main St, Dundrum, Dublin 14",D14,FR80,Bank,5.0,2.0,53.290987,-6.245235
17,EBS Dundrum,"9 Main St, Dundrum, Dublin 14, D14 DH50",D14,A1K9,Bank,NaN,NaN,53.291156,-6.245353
18,KBC Bank,"G-14, Dundrum Village Shopping Centre, Main St...",D14,A1K9,Bank,4.1,8.0,53.291588,-6.246287
19,Bank of Ireland Dundrum,"Main St, Dundrum, Dublin",D14,NaN,Financial institution,2.1,16.0,53.291856,-6.245493
20,Ulster Bank (Dundrum),"Usher House, Dundrum, Dublin, D14 N7Y8",D14,N7Y8,Bank,3.6,15.0,53.292157,-6.245525
21,Bank of Ireland,"Rathfarnham Shopping Centre, Butterfield Ave, ...",D14,NaN,Financial institution,4.6,5.0,53.296459,-6.297436
22,EBS Rathfarnham,"Rathfarnham Shopping Centre, Butterfield Ave, ...",D14,NaN,Financial institution,1.7,6.0,53.296732,-6.297239
23,permanent tsb,"152 R114, Rathfarnham, Dublin",D14,NaN,Bank,4.7,3.0,53.298222,-6.286077
24,AIB Rathfarnham,"6-7 Main St, Ráth Fearnáin, Dublin 14, D14 V382",D14,A1K9,Bank,2.2,6.0,53.299785,-6.284776
25,AIB UCD,"UCD, Belfield, Dublin 4",D14,K5X0,Bank,4.3,12.0,53.306947,-6.220011
26,Bank of Ireland,"University Montrose, Stillorgan Rd, Priesthous...",D04,NaN,Financial institution,4.8,8.0,53.308765,-6.215084
27,Bank of Ireland,"Rathfarnham Road Rathfarnham Rd, Terenure, Co....",D6W,XY66,Financial institution,2.5,12.0,53.309587,-6.283919
28,Ulster Bank (Terenure),"93/95 Terenure Rd E, Terenure, Dublin, D06 V3F4",D06,NaN,Bank,1.8,18.0,53.309955,-6.282747
29,AIB Bank,"9 Terenure Rd E, Rathfarnham, Dublin, D06 F512",D06,F512,Bank,3.0,6.0,53.311650,-6.275082
...,...,...,...,...,...,...,...,...,...
130,EBS,"Malahide Rd, Beaumont, Dublin",D05,NaN,Bank,3.7,3.0,53.380185,-6.210375
131,AIB,"Howth Rd, Clontarf East, Dublin 5, D05 HN82",D03,H344,Bank,4.0,12.0,53.380325,-6.178256
132,Bank of Ireland,"566 Howth Rd, Northside, Raheny, Co. Dublin",D05,NaN,Financial institution,3.4,7.0,53.380536,-6.172527
133,AIB Bank,"St Brigids Road, Artane, Dublin 5",D05,P9W9,Bank,2.9,14.0,53.382347,-6.205367
134,permanent tsb,"Malahide Rd, Beaumont, Dublin 5, D05 FH39",D05,E7K4,Bank,3.9,8.0,53.382568,-6.207230
135,Ulster Bank (Blanchardstown),"Main St, Blanchardstown, Dublin, D15 VY03",D15,VY03,Bank,2.4,19.0,53.385894,-6.374169
136,Bank of Ireland,"The Henry Gratton Building, Dublin City Univer...",D09,FW22,Bank,2.1,9.0,53.386014,-6.258927
137,Bank of Ireland Blanchardstown,"Main St, Blanchardstown, Co. Dublin",D15,NaN,Financial institution,2.2,27.0,53.386861,-6.377234
138,Memory Bank Ltd,"36 Offington Park, Northside, Sutton, Co. Dubl...",D13,E9E5,NaN,NaN,NaN,53.387211,-6.098625
139,permanent tsb,"2-3 Village Centre, Finglas, Co. Dublin",D11,NaN,Bank,4.4,7.0,53.387401,-6.297830
140,Ulster Bank (Coolock),"Main Street, Northside, Dublin 5, D05 N207",D15,W8DR,Bank,3.7,3.0,53.387918,-6.200682
141,AIB Bank,"54 Main St, Finglas East, Dublin 11",D11,H21V,Bank,3.7,18.0,53.388804,-6.298171
142,EBS Finglas,"Unit 1/3, Finglas Main Shopping Centre, Main S...",D11,T6YF,Financial institution,3.7,3.0,53.388948,-6.298256
143,EBS Sutton,"Sutton Cross, Burrow, Dublin 13",D13,E0W5,Financial institution,NaN,NaN,53.389337,-6.109386
144,Bank of Ireland,"60 Main St, Northside, Coolock, Co. Dublin, D0...",D05,F2P5,Financial institution,3.4,10.0,53.389433,-6.200129
145,AIB Bank,"Sutton Cross, Burrow, Dublin 13",D13,E0W5,Bank,4.0,8.0,53.389642,-6.109872
146,Bank of Ireland,"Sutton Cross, Burrow, Sutton, Co. Dublin",D13,NaN,Financial institution,5.0,1.0,53.389642,-6.110140
147,AIB Blanchardstown,"Westend Retail Park, Blanchardstown, Dublin 15",D15,N668,Bank,3.7,40.0,53.389716,-6.389660
148,Bank of Ireland,"Seamus Ennis Rd, Northside, Dublin 11, D11 C927",D11,C927,Financial institution,3.1,12.0,53.390119,-6.298130
149,Bank of Ireland,"Beaumont Hospital, Beaumont Rd, Beaumont, Dubl...",D09,NaN,Bank,4.8,4.0,53.390600,-6.223560
150,permanent tsb,"Unit 1/2 Omni Park Shopping Centre, Swords Rd,...",D09,HP90,Bank,2.6,5.0,53.391947,-6.248168
151,Permanent TSB,"Blanchardstown Centre, Unit 134-135, The Red M...",D15,NaN,Bank,2.3,24.0,53.392187,-6.389140
152,KBC Bank,"Unit 101, Blanchardstown Centre, Blanchardstow...",D15,KX90,Bank,2.4,7.0,53.393000,-6.390180
153,KBC Bank,"Unit 101, Blanchardstown Centre, Blanchardstow...",D15,KX90,Bank,2.4,7.0,53.393754,-6.389975
154,EBS Blanchardstown,"166, Blanchardstown Shopping Centre, Blanchard...",D15,NaN,Financial institution,2.5,2.0,53.393881,-6.390216
155,AIB Bank,"Swords Road, Santry, Dublin 9",D09,DK44,Bank,3.7,19.0,53.395098,-6.246068
156,AIB Bank,"Ballymun Civic Centre, Ballymun, Dublin",D11,NaN,Bank,5.0,4.0,53.395294,-6.263805
157,Ulster Bank (Finglas),"Unit 1C, Charlestown Shopping Centre, St Marga...",D11,H243,Bank,2.9,11.0,53.403924,-6.302608
158,Bank of Ireland,"Ground Floor, Block 1, Blanchardstown Corporat...",D15,AKK1,Bank,4.2,5.0,53.409109,-6.369327
159,Bank of Ireland Collinstown Cross,"2-3, Omega House, Collinstown Cross, Cloghran,...",D22,CD82,Bank,2.9,7.0,53.416988,-6.240120

In [30]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.5)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [31]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [32]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(3637, 19)
(3637, 23)

In [33]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/bank_final.xlsx', index = False)

### Fire station

In [34]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Fire station')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Dublin Fire Brigade HQ,"165-169 Townsend St, Dublin 2, D02 RY99",D02,RY99,Fire station,4.2,12.0,53.345759,-6.254012
1,Phibsborough Fire Station - Dublin Fire Brigade,"Phibsborough Rd, Phibsborough, Dublin, D07 X3TV",D07,X3TV,Fire station,4.5,2.0,53.357717,-6.274122
2,Finglas Fire Station - Dublin Fire Brigade,"Mellowes Ave, Northside, Finglas, Co. Dublin, ...",D11,NaN,Fire station,5.0,2.0,53.390150,-6.303394
3,Dolphin's Barn Fire Station - Dublin Fire Brigade,"Parnell Rd, Drimnagh, Dolphins Barn, Co. Dubli...",D12,C520,Fire station,5.0,6.0,53.331576,-6.292688
4,Kilbarrack Fire Station - Dublin Fire Brigade,"Kilbarrack Road Kilbarrack, Dublin, D05 WF64",D05,WF64,Fire station,4.6,7.0,53.390896,-6.168221
5,Blanchardstown Fire Station - Dublin Fire Brigade,"Snugborough Rd, Coolmine, Dublin, D15 ET89",D15,NaN,Fire station,4.5,2.0,53.384644,-6.395870
6,Tallaght Fire Station - Dublin Fire Brigade,"Belgard Rd, Kingswood, Dublin 22, D22 RD68",D24,R7YV,Fire station,5.0,4.0,53.307359,-6.382882
7,North Strand Fire Station - Dublin Fire Brigade,"N Strand Rd, North Dock, Dublin, D03 YV26",D03,YV26,Fire station,NaN,NaN,53.359802,-6.239403
8,Dublin Fire Garage,"4 Stable Ln, Northside, Dublin",D06,DX96,Fire station,NaN,NaN,53.351174,-6.280339
9,Dublin Airport Fire Station,"Huntstown, Dublin",D15,NaN,Fire station,5.0,1.0,53.427125,-6.262449
10,No 1. Donnybrook Fire Station,"4 Donnybrook Rd, Ranelagh, Dublin, D04 W6R9",D04,VE84,Fire station,5.0,4.0,53.321974,-6.237413
11,Nutgrove Fire Station,"Whitehall, Dublin",D09,NaN,Fire station,5.0,2.0,53.291754,-6.264983
12,Donnybrook Fire Station - Dublin Fire Brigade,"19 - 23 Donnybrook Rd, Ranelagh, Donnybrook, C...",D04,NC43,Fire station,NaN,NaN,53.321914,-6.237472
13,KSS Fire Suppresion,"78A Cookstown Industrial Estate, Tallaght, Co....",D24,NaN,Fire station,NaN,NaN,53.294996,-6.374226

In [35]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<2.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<2.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.4)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [36]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [37]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(1346, 19)
(1346, 23)

In [38]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/fire_station_final.xlsx', index = False)

### Library

In [39]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Library')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Cabra Library,"Navan Road, Dublin, D07 AYW1",D07,AYW1,Public library,4.7,17.0,53.361735,-6.299663
1,Finglas Library,"Finglas Village Centre,, Jamestown Rd, Ballyga...",D11,K330,Public library,4.1,15.0,53.389183,-6.297732
2,Dublin City Library & Archive,"144 Pearse St, Dublin 2, D02 DE68",D02,A320,Library,4.3,12.0,53.343160,-6.245250
3,The Long Room Of The Old Library At Trinity Co...,Dublin,D01,NaN,Library,4.5,192.0,53.343956,-6.256800
4,Central Library,"Henry St, North City, Dublin 1",D01,XH90,Public library,4.1,65.0,53.350253,-6.264369
5,Ballyfermot Library,"Ballyfermot Rd, Kylemore, Dublin",D10,NaN,Public library,4.4,15.0,53.340089,-6.351695
6,Ballymun Library,"9 Ballymun Rd, Ballymun, Dublin 9",D11,NaN,Public library,4.4,15.0,53.390402,-6.265021
7,Dublin City Library,"138-144 Pearse St, Dublin 2",D02,A320,Library,4.0,2.0,53.343114,-6.245219
8,National Library of Ireland,"7-8 Kildare St, Dublin 2, D02 P638",D02,NaN,Library,4.2,105.0,53.341098,-6.254482
9,Drumcondra Library,"9 Millmount Ave, Drumcondra, Dublin 9",D09,K303,Public library,4.4,17.0,53.369894,-6.258985
10,Marsh’s Library,"St Patrick's Close, Wood Quay, Dublin 8",D08,NaN,Public library,4.9,32.0,53.339109,-6.270610
11,Phibsboro Library,"Blacquiere Bridge, North Circular Road, Phibsb...",D07,VX54,Public library,3.8,14.0,53.361136,-6.271054
12,Kevin Street Library,"18 Lower Kevin Street Lower, Portobello, Dubli...",D08,EY79,Public library,4.4,22.0,53.337481,-6.267678
13,Trinity College Library,"College Green, Dublin 2, D02 VR66",D02,VR66,Library,4.5,75.0,53.344223,-6.259634
14,Charleville Mall Library,"Charleville Mall, N Strand Rd, Northside, Dubl...",D01,AD81,Public library,5.0,2.0,53.357127,-6.246084
15,Pearse Street Library,"144 Pearse St, Dublin 2, D02 DE68",D02,A320,Public library,4.5,29.0,53.343140,-6.245194
16,Inchicore Library,"34 Emmet Rd, Inchicore, Dublin 8, D08 ED66",D08,ED66,Public library,3.8,14.0,53.340390,-6.309730
17,Rathmines Library,"Lower Rathmines Road Rathmines Road Lower, Dub...",D06,HW58,Public library,4.5,33.0,53.324196,-6.265871
18,Dolphin's Barn Library,"Parnell Rd, Crumlin, Dublin, D12 ET22",D12,ET22,Public library,4.5,15.0,53.331373,-6.291937
19,Coolock Library,"Barryscourt Rd, Kilmore, Dublin",D17,NaN,Public library,3.9,14.0,53.396379,-6.212173
20,Blanchardstown Library,"The Civic Centre , Blanchardstown Centre, Dubl...",D15,NaN,Library,4.5,44.0,53.390869,-6.391574
21,Walkinstown Library,"Percy French Rd, Walkinstown, Dublin",D12,NaN,Public library,4.4,31.0,53.318691,-6.321806
22,The Reading Room,"138-144 Pearse St, Dublin 2",D02,A320,Library,NaN,NaN,53.343122,-6.245172
23,Marino Library,"Marino Mart, Northside, Dublin",D03,NaN,Public library,4.6,11.0,53.364440,-6.231158
24,Raheny Library,"Howth Rd, Northside, Dublin 5, D05 VY99",D03,H344,Public library,4.6,25.0,53.380015,-6.173108
25,Griffith College Library,"8 S Circular Rd, Merchants Quay, Dublin, D08 V04N",D08,W56T,Library,5.0,2.0,53.331063,-6.279192
26,Pembroke Library,"Anglesea Rd, Dublin",D04,NaN,Public library,4.8,12.0,53.328127,-6.230509
27,Ballyroan Library,"54 Orchardstown Ave, Rathfarnham, Dublin 14, D...",D14,XY75,Library,3.8,29.0,53.290676,-6.299374
28,Terenure Library,"Templeogue Rd, Terenure, Dublin",D6W,NaN,Public library,3.5,14.0,53.308974,-6.285274
29,Ringsend Library,"Fitzwilliam St, Dublin",D04,NaN,Public library,4.8,11.0,53.341516,-6.226448
...,...,...,...,...,...,...,...,...,...
57,Leabharlann Library,"Belgard Square W, Cookstown, Dublin",D24,NaN,Library,NaN,NaN,53.288325,-6.374550
58,South Dublin County Council Mobile Library Stop,"3 Rossmore Rd, Templeogue, Dublin 6W, Co. Dubl...",D6W,CY92,Public library,NaN,NaN,53.297749,-6.319545
59,South Dublin County Council Mobile Library Stop,"Sylvan Ave, Kingswood, Dublin",D24,NaN,Public library,NaN,NaN,53.307424,-6.364967
60,South Dublin County Council Mobile Library Stop,"34 Kilcarrig Ave, Whitehall, Dublin 24, D24 E181",D24,E181,Library,NaN,NaN,53.291300,-6.392363
61,South Dublin County Council Mobile Library Stop,"Heatherview Dr, Oldbawn, Dublin 24",D24,RH5F,Library,NaN,NaN,53.275793,-6.368344
62,The WEB Project,"Taylor's Ln, Rathfarnham, Dublin 16",D16,Y0P6,Library,4.0,4.0,53.281379,-6.293258
63,Shankill Library,"Library Rd, Shankill, Dublin 18, D18 DX43",D18,AX89,Library,4.3,10.0,53.233545,-6.127001
64,Mater Hospital Library,"Eccles St, Northside, Dublin",D07,NaN,Library,5.0,2.0,53.359419,-6.268899
65,South Dublin County Council Mobile Library Stop,"6-12 Cypress Lawn, Templeogue Village, Dublin ...",D6W,N298,Public library,NaN,NaN,53.298236,-6.310285
66,Character Design References,"Dame St, Dublin Southside, Dublin",D02,NaN,Library,2.5,2.0,53.343995,-6.266330
67,Central Catholic Library - Lending & Reference,"71 Merrion Square S, Dublin 2, D02 K223",D02,K223,Library,NaN,NaN,53.339040,-6.250526
68,south dublin mobile library stop,"Palmer Park, Ballyboden, Dublin",D16,NaN,Public library,NaN,NaN,53.281065,-6.291784
69,south dublin mobile library stop,"1-19 Prospect Dr, Prospect Manor, Dublin 16, D...",D16,Y8H0,Public library,NaN,NaN,53.275271,-6.301099
70,South Dublin County Council Mobile Library Stop,"Jobstown, Dublin",D24,NaN,Public library,NaN,NaN,53.285356,-6.413677
71,South Dublin County Council Mobile Library Stop,"3-5 Treepark Rd, Kilnamanagh, Co. Dublin, D24 ...",D24,V8W8,Public library,NaN,NaN,53.299951,-6.357684
72,South Dublin County Council Mobile Library Stop,"Glenshane Dr, Jobstown, Dublin",D24,NaN,Public library,NaN,NaN,53.283453,-6.399181
73,South Dublin County Council Mobile Library Stop,"24-20 Hunters Ave, Ballycullen, Dublin, D24 H7Y4",D24,H7Y4,Public library,NaN,NaN,53.271608,-6.330941
74,Refugee(Economic Migrant) Documentation Centre,"11 Montague Ln, Dublin, D02 RK30",D02,RK30,Library,NaN,NaN,53.336682,-6.264397
75,South Dublin County Council Mobile Library Stop,"2-14 Allenton Dr, Killininny, Dublin 24, D24 PVH3",D24,YP6F,Library,NaN,NaN,53.271955,-6.351318
76,Howth Public Library,"Howth, Co. Dublin",D03,NaN,Library,5.0,2.0,53.385490,-6.064770
77,Cabinteely Library,"D18 W773, Bray Road, Cabinteely, Dublin",D18,W773,Library,4.2,10.0,53.259823,-6.149552
78,St Lukes Institute of Cancer Research Library,"St Luke's Hospital, Highfield Rd, Rathfarnham,...",D06,NaN,Library,NaN,NaN,53.310523,-6.266479
79,RTE Stills Library,"Library Building Rte, Donnybrook, Co. Dublin",D04,NaN,Library,NaN,NaN,53.315765,-6.224320
80,South Dublin Libraries Mobile Stop,"Unit 1, The Square Industrial Complex, Tallagh...",D24,A9KW,Library,NaN,NaN,53.289035,-6.370694
81,Lib,"Larkfield Residences, Artane - Whitehall, Dublin",D09,NaN,Library,NaN,NaN,53.384359,-6.257243
82,South Dublin County Council Mobile Library Stop,"2-20 Broadfield Meadows, Tootenhill, Rathcoole...",D24,C780,Public library,1.0,1.0,53.279337,-6.482125
83,South Dublin County Council Mobile Library Stop,"1 Aylmer Ave, Commons Little, Newcastle, Co. D...",D22,VY44,Public library,NaN,NaN,53.299042,-6.493012
84,South Dublin County Council Mobile Library Stop,"Gortlum, Co. Dublin",D01,NaN,Public library,NaN,NaN,53.234790,-6.450793
85,Baldoyle Library,"The Mall, Baldoyle, Dublin, D13 Y304",D13,Y304,Library,4.6,13.0,53.396859,-6.125746
86,Empire Digital Ballyfermot,"308 Ballyfermot Rd, Drumfinn, Dublin 10, D10 E985",D10,E985,Library,3.3,4.0,53.342470,-6.353494

In [40]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.2)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [41]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [42]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(1537, 19)
(1537, 23)

In [43]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/library_final.xlsx', index = False)

### Hospital

In [44]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Hospital')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Connolly Hospital Blanchardstown,"Mill Rd, Abbotstown, Dublin, D15 X40D",D15,X40D,Hospital,3.2,112.0,53.388303,-6.368848
1,"Inchicore Primary Care Centre, HSE","St Michael's Estate, Inchicore, Dublin",D08,NaN,Hospital,3.0,2.0,53.338727,-6.316247
2,Mater Misericordiae University Hospital - Rapi...,"The Forge, Smithfield Market, Smithfield, Dubl...",D07,VKP9,Urgent care center,3.2,25.0,53.349612,-6.278297
3,"A&E - Accident & Emergency Department, Temple ...","Temple St, Rotunda, Dublin",D06,NaN,Hospital,NaN,NaN,53.357068,-6.261357
4,The Mater Misericordiae University Hospital,"Eccles St, Northside, Dublin 7, D07 R2WY",D07,R2WY,Hospital,2.9,227.0,53.359859,-6.265669
5,St Vincent's University Hospital - Emergency D...,"6, Bayview Court, 53°19'01. 6°12'50., 2 Tivoli...",D04,WP59,Hospital,1.9,16.0,53.316990,-6.214048
6,Clonskeagh Hospital,"Pembroke - Rathmines, Dublin",D06,NaN,Hospital,5.0,1.0,53.315751,-6.240020
7,Emergency Department,"Tallaght Hospital, Belgard Square North, Cooks...",D24,NaN,Hospital,2.0,23.0,53.291928,-6.378216
8,Cherry Orchard Hospital,"Cherry Orchard, Dublin",D10,NaN,Hospital,3.4,7.0,53.343457,-6.377637
9,HSE Dental Clinic,"Old County Rd, Crumlin, Dublin",D12,NaN,Hospital,5.0,2.0,53.327598,-6.303333
10,Mater Private Emergency Department,"Ecles Street, Northside, Dublin 7",D07,XA09,Urgent care center,2.3,7.0,53.357830,-6.264538
11,National Orthopaedic Hospital Cappagh,"Cappagh Rd, Northside, Dublin 11, D11 EV29",D11,NaN,Hospital,4.5,52.0,53.394107,-6.326937
12,Fairview Community Unit,"Griffith Ct, Drumcondra, Dublin 3",D09,N6F9,Hospital,3.3,6.0,53.368229,-6.242366
13,Beacon Hospital,"Beacon Court, Bracken Rd, Sandyford Business P...",D18,AK68,Private hospital,3.7,127.0,53.275737,-6.219444
14,New Children's Hospital (Main Office),"31 James's Walk, Rialto, Dublin 8, D08 E191",D08,E191,Hospital,5.0,1.0,53.338172,-6.293445
15,St. Patrick's University Hospital,"James's St N, Saint James' (part of Phoenix Pa...",D08,NaN,Hospital,3.6,45.0,53.344056,-6.291885
16,Mater Private,"Eccles St, Northside, Dublin 7, D07 WKW8",D07,XA09,Hospital,3.8,89.0,53.357918,-6.264459
17,Beaumont Hospital,"Beaumont Rd, Beaumont, Dublin",D09,NaN,Hospital,3.6,187.0,53.390478,-6.223302
18,Coombe Womens Hospital,"Cork St, Merchants Quay, Dublin, D08 XW7X",D08,NaN,Hospital,3.8,107.0,53.334950,-6.288435
19,CHI at Temple Street,"Temple St, Rotunda, Dublin 1, D01 XD99",D01,XD99,Hospital,3.8,135.0,53.356787,-6.262029
20,Old meath hospital,"Old meath hospital, Heytesbury St, Dublin",D08,NaN,Hospital,NaN,NaN,53.335646,-6.269256
21,The National Maternity Hospital,"Holles St, Dublin, D02 YH21",D02,YH21,Hospital,3.7,94.0,53.339786,-6.246233
22,"Deansrath Health Centre, HSE","Deansrath, Dublin",D22,NaN,Hospital,4.0,1.0,53.323700,-6.424209
23,St Vincent's University Hospital,"196 Merrion Road, Elm Park, Dublin, D04 T6F4",D04,Y8V0,Hospital,3.7,198.0,53.317000,-6.212890
24,Mount Carmel Community Hospital,"Little Company of Mary, 40 Braemor Park, Newto...",D14,K2W5,Hospital,4.3,14.0,53.304509,-6.265639
25,Saint James's Hospital,"James's Street, Saint James' (part of Phoenix ...",D08,NaN,Hospital,3.4,238.0,53.340723,-6.293245
26,Summerhill Primary Care Centre,"Summerhill, Mountjoy, Dublin",D01,A031,Hospital,3.7,3.0,53.355661,-6.253201
27,Tallaght Adult Mental Health Services,"Sheaf House, Exchange Hall, Belgard Square Nor...",D24,A2Y8,Mental health clinic,NaN,NaN,53.290163,-6.373946
28,HSE CLONSKEAGE,"Vergemount Hall, Rathmines, Dublin 6",D06,V6R2,Hospital,5.0,1.0,53.315692,-6.240062
29,SIMMS Building,"Tallaght cross west, Cookstown Way, Tallaght, ...",D24,NaN,Hospital,3.9,7.0,53.287474,-6.376948
...,...,...,...,...,...,...,...,...,...
225,Hilton Dublin Airport,"Malahide Rd, Northern Cross, Dublin",D05,NaN,NaN,4.0,1735.0,53.403419,-6.179944
226,Beacon Consultants Clinic,"Beacon Court, Bracken Rd, Sandyford Business P...",D18,C4H1,Medical clinic,3.6,14.0,53.275336,-6.219709
227,Gastrolife Limited,"Sandyford Healthcare Unit D/E Time Place, 21 C...",D18,R89T,Medical clinic,NaN,NaN,53.276870,-6.215138
228,Stewarts Care Main Administration Building,"Mill Ln, Redcowfarm, Dublin, D20 XT80",D20,XT80,Community health centre,NaN,NaN,53.354634,-6.365554
229,Stewarts Care,"Redcowfarm, Dublin",D01,NaN,Community health centre,NaN,NaN,53.355870,-6.368656
230,Dominican Priory,"100-518 Main St, Tallaght, Dublin 24, D24 P298",D24,P298,Hospital,4.0,1.0,53.289542,-6.360864
231,Tallaght Hospital Mortuary,"Tallaght Hospital, Belgard Square North, Cooks...",D24,NaN,Hospital,NaN,NaN,53.290033,-6.377478
232,Kilnamanagh Tymon Primary Care Centre,"2nd Floor, Junction House, Tallaght, Dublin, D...",D24,CF75,Hospital,5.0,3.0,53.293937,-6.356158
233,Whitehall Clinic,"394a Collins Ave, Whitehall, Dublin 9, D09 X7H5",D09,PD89,Medical clinic,3.8,13.0,53.381583,-6.240843
234,Wellmount Health Centre,"Wellmount Park, Northside, Dublin",D11,NaN,NaN,4.0,25.0,53.385366,-6.311456
235,Old Bawn Dental Practice,"70 Old Bawn Rd, Oldbawn, Dublin 24, D24 EY22",D24,EY22,Dental clinic,5.0,9.0,53.282302,-6.358846
236,Old County Road Health Centre,"57 Old County Rd, Crumlin, Dublin 12, D12 KT66",D12,KT66,Community health centre,5.0,3.0,53.328858,-6.301424
237,Crannog Psychological Services,"5 Main Rd, Tallaght, Dublin, D24 X096",D24,X096,Psychologist,NaN,NaN,53.288517,-6.356115
238,Red Cow Moran Hotel,"22 Naas Rd, Fox-And-Geese, Dublin, D22 YX80",D12,VR83,NaN,4.1,3264.0,53.318673,-6.364109
239,Louis Fitzgerald Hotel,"1A Naas Rd, Newlands Cross, Dublin 22, D22 X5N7",D22,C9T4,NaN,4.1,1619.0,53.315315,-6.384269
240,"Mountain Park, Dental Practice, Tallaght","51 Mountain Park, Tallaght, Co. Dublin, D24 RR28",D24,RR28,Dental clinic,4.9,12.0,53.284114,-6.355812
241,Mayberry Dental Care,"20 Birchview Dr, Tymon North, Dublin 24, D24 VXR2",D24,VXR2,Dental clinic,4.3,7.0,53.298527,-6.355470
242,KingsWood Hotel Citywest,"Naas Rd, Kingswood, Dublin 22",D22,NaN,NaN,4.2,714.0,53.301016,-6.418392
243,Maldron Hotel Tallaght,"Whitestown Way, Oldbawn, Dublin 24, D24 XC9W",D24,XC9W,NaN,3.9,1342.0,53.284019,-6.375945
244,Maldron Hotel Newlands Cross,"22 Naas Rd, Newlands Cross, Dublin, D22 V6Y6",D12,VR83,NaN,4.0,2343.0,53.313491,-6.392423
245,Hotel ibis Dublin,"Off, Red Cow Roundabout, Monastery Road, Naas ...",D22,WY43,NaN,3.8,1183.0,53.318355,-6.372124
246,Edenmore Health Centre,"Edenmore Park, Edenmore, Dublin",D05,NaN,NaN,3.4,7.0,53.387365,-6.183732
247,Neart Le Chéile,"2 Neilstown Rd, Rowlagh, Clondalkin, Co. Dublin",D22,CX97,NaN,NaN,NaN,53.344647,-6.398327
248,"The Green Isle, Sure Hotel Collection by Best ...","St John's Dr, Newlands Cross, Dublin 22, D22 F9F4",D22,E9W3,NaN,3.8,1760.0,53.309542,-6.403690
249,Ballygall Health Centre,"Seamus Ennis Rd, Finglas, Dublin 11",D11,NaN,Medical clinic,1.0,1.0,53.390226,-6.296322
250,Medixclinic,"Beacon Court, Bracken Rd, Sandyford Business P...",D18,C4H1,Medical clinic,4.3,23.0,53.276324,-6.219715
251,Darndale Health Centre,"Darndale Village, Darndale, Dublin",D17,NaN,Dental clinic,4.0,11.0,53.401451,-6.194546
252,Millbrook Lawns Health Centre,"St Dominick's Rd, Tallaght, Dublin",D24,NaN,Community health centre,4.5,4.0,53.284654,-6.355424
253,Slievemore Clinic,"Old Dublin Rd, Stillorgan, Dublin",D04,NaN,Medical clinic,4.0,25.0,53.292561,-6.201525
254,Allergy Ireland Dr Paul Carson & Dr Iseult She...,"First Floor, Old Dublin Road, Stillorgan, Dubl...",D14,NaN,Allergist,NaN,NaN,53.292526,-6.201168

In [45]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.5)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [46]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [47]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(4696, 19)
(4696, 23)

In [48]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/hospital_final.xlsx', index = False)

### Pharmacy

In [49]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Pharmacy')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Hickey's Pharmacy,"55 O'Connell Street Lower, North City, Dublin ...",D01,W2V3,Pharmacy,3.7,30.0,53.347638,-6.259761
1,Meaghers Pharmacy Kinvara Park,"41 Kinvara Park, Ashtown, Dublin 7, D07 P584",D07,P584,Pharmacy,3.6,11.0,53.369012,-6.318337
2,Hickey's Pharmacy,"3 Cardiffsbridge Rd, Cappagh Rd, Northside, Fi...",D11,W623,Pharmacy,5.0,8.0,53.389638,-6.311224
3,City Pharmacy Ltd,"14 Dame St, Dublin 2, D02 XH24",D02,XH24,Pharmacy,3.9,47.0,53.344053,-6.265455
4,McCabe's Pharmacy,"Glasnevin Ave, Finglas East, Ballymun, Dublin,...",D11,TX4R,Pharmacy,4.2,13.0,53.390169,-6.274422
5,LloydsPharmacy,"103a New, Cabra Rd, Dublin 7, D07 R2RF",D07,R2RF,Pharmacy,4.2,12.0,53.361300,-6.284687
6,Hickey's Pharmacy,"6, Dunnes Stores Shopping Centre, 11 Cardiffsb...",D11,RR59,Pharmacy,3.7,6.0,53.384493,-6.312221
7,Hickey's Pharmacy,"Phibsborough Shopping Centre, Phibsborough, Du...",D07,K765,Pharmacy,3.4,26.0,53.361575,-6.272995
8,Clearwater Allcare Pharmacy,"Unit 1, Clearwater Shopping Centre, Finglas Rd...",D11,NaN,Pharmacy,2.9,16.0,53.383168,-6.296154
9,Hickey's Pharmacy,"21 Grafton Street, Dublin 2, D02 FW29",D02,FW29,Pharmacy,4.5,15.0,53.341901,-6.259853
10,Stacks Pharmacy Support Office,"Unit 16, Northern Cross Business Park, 11 Nort...",D11,HN93,Pharmacy,NaN,NaN,53.396347,-6.316938
11,Hickey's Pharmacy,"6 Henry St, North City, Dublin 1, D01 AK46",D01,AK46,Pharmacy,4.7,14.0,53.349506,-6.261710
12,LloydsPharmacy,"39 Stoneybatter, Dublin, D07 AE37",D07,AE37,Pharmacy,3.8,12.0,53.350219,-6.281978
13,McCabes Pharmacy,"Unit 8, College View, Ballymun, Dublin",D11,NaN,Pharmacy,4.5,15.0,53.395022,-6.264449
14,Remedi Pharmacy,"Unit 8 Custom House Square, IFSC, Dublin",D01,A2H3,Pharmacy,4.2,26.0,53.349309,-6.242755
15,Temple Bar Pharmacy,"Essex St E, Temple Bar, Dublin 2",D02,TF24,Pharmacy,4.2,18.0,53.345602,-6.264507
16,Allcare Pharmacy O'Connell Street,"5 O'Connell Street Lower, North City, Dublin 1...",D01,P9F2,Pharmacy,2.6,35.0,53.348000,-6.259002
17,LloydsPharmacy,"10 Drumcondra Rd Upper, Drumcondra, Dublin 9, ...",D09,H3C5,Pharmacy,4.0,13.0,53.369103,-6.254291
18,Hickey's Pharmacy,"290 Harold's Cross Rd, Harold's Cross, Terenur...",D6W,NaN,Pharmacy,3.8,14.0,53.319878,-6.279004
19,Foley's Chemist,"136 Parnell St, Rotunda, Dublin 1, D01 A9C7",D01,A9C7,Pharmacy,4.7,14.0,53.353879,-6.258860
20,McCabes Pharmacy,"Unit 148, 15 The Mall, Blanchardstown, Dublin",D15,HC8D,Pharmacy,4.2,6.0,53.392846,-6.390131
21,Meagher's Pharmacy Baggot Street,"10 Baggot Street Upper, Dublin 4, D04 A6W7",D04,KT35,Pharmacy,4.2,26.0,53.333842,-6.244544
22,Pure Pharmacy,"Portland St N, Northside, Dublin",D01,NaN,Pharmacy,4.2,18.0,53.359299,-6.256212
23,Hogan's Life Pharmacy Parnell Street,"41 Parnell St, North City, Dublin",D01,NaN,Pharmacy,5.0,5.0,53.350571,-6.265269
24,Boots,"6, 11 St Margaret's Rd, Charlestown, Dublin 11...",D11,FNT3,Pharmacy,2.9,15.0,53.403357,-6.303064
25,Limitless Health Pharmacy,"Northern Cross Business Park, 17 North Rd, Nor...",D11,HN93,Pharmacy,NaN,NaN,53.397874,-6.316954
26,Reilly's Pharmacy Thomas Street,"Unit 2, Bertram Court, Cornmarket, Thomas St, ...",D08,NaN,Pharmacy,4.4,9.0,53.342987,-6.275929
27,Superpharm Chemists,"Finglas, Main Centre, Dublin 11",D11,H21V,Pharmacy,NaN,NaN,53.389432,-6.298041
28,Hayes Allcare Pharmacy,"16 Hogan Pl, Dublin 2, D02 DD78",D02,DD78,Pharmacy,3.5,4.0,53.340674,-6.243609
29,Maple Pharmacy,"3, The Maple Centre, Navan Rd, Dublin 7, D07 CKR7",D07,X5XR,Pharmacy,2.7,18.0,53.361430,-6.298677
...,...,...,...,...,...,...,...,...,...
301,LloydsPharmacy,"11B Braemor Rd, Rathmines Little, Dublin 14",D14,CX98,Pharmacy,4.0,4.0,53.296097,-6.260233
302,Hickey's Pharmacy,"10 Main St, Ongar Village, Ongar, Co. Dublin, ...",D15,E9WK,Pharmacy,4.0,24.0,53.395578,-6.439046
303,Andrew Buckley's Totalhealth Pharmacy,"d14, 5 St Enda's Dr, Rathfarnham, Dublin, D14 ...",D14,T2P8,Pharmacy,5.0,14.0,53.289135,-6.283566
304,Hunter's Pharmacy,"5 Olivemount Terrace, Windy Arbour, Dublin 14,...",D14,T8Y1,Pharmacy,4.5,4.0,53.304647,-6.245420
305,Smith's Pharmacy,"121 Braemor Rd, Rathmines Little, Dublin 14, D...",D14,AE17,Pharmacy,4.6,10.0,53.300534,-6.263602
306,Boots,"18 Dundrum Rd, Dundrum, Dublin, D16 EW74",D14,K2T8,Pharmacy,3.5,8.0,53.286369,-6.240568
307,Roebuck Pharmacy,"7 Farmhill Rd, Friarland, Dublin 14, D14 W1W6",D14,T9K1,Pharmacy,4.5,2.0,53.298432,-6.236646
308,Haven Pharmacy Greene's,"36 Main St, Rathfarnham, Dublin, D14 FD73",D14,FD73,Pharmacy,5.0,2.0,53.298297,-6.285639
309,Lloyds Pharmacy,"Nutgrove Shopping Centre, Rathfarnham, Dublin ...",D14,E6W6,Pharmacy,3.5,8.0,53.289700,-6.267643
310,Hilton's Pharmacy,"11 Main St, Rathfarnham, Dublin, D14 C2F5",D14,C2F5,Pharmacy,4.7,6.0,53.299287,-6.285278
311,Sheridan's Pharmacy,"Roselawn Rd, Blanchardstown, Dublin 15",D15,PDN1,Pharmacy,4.9,12.0,53.383600,-6.381864
312,Kilmacud totalhealth Pharmacy,"1 Drummartin Rd, Kilmacud West, Dublin, D14 C3Y0",D14,C3Y0,Pharmacy,4.4,7.0,53.288989,-6.222361
313,Complete Care Pharmacy Mulhuddart,"110, Main Street, Mulhuddart, Co. Dublin, D15 ...",D13,T3H7,Pharmacy,NaN,NaN,53.401905,-6.396338
314,Haven Pharmacy Brennan's,"Taylor's Ln, Rathfarnham, Dublin",D16,NaN,Pharmacy,5.0,5.0,53.281883,-6.294723
315,Limitless Health Pharmacy,"Unit 4, Burnell Court, Malahide Rd, Northern C...",D17,A891,Pharmacy,4.0,5.0,53.404824,-6.178685
316,LloydsPharmacy,"Northside shopping centre Coolock, Dublin 17, ...",D13,C2F6,Pharmacy,2.5,2.0,53.395705,-6.214194
317,Júlia UZLET,"1a Drummartin Rd, Kilmacud West, Dublin 14, D1...",D14,E6H6,Pharmacy,NaN,NaN,53.288747,-6.222528
318,BONNYBROOK PHARMACY,"UNIT 1B, Northside Retail Park, Coolock Dr, No...",D17,TD35,Pharmacy,4.6,9.0,53.393429,-6.202636
319,Darndale Pharmacy,"Darndale Belcamp Village Centre, Northside, Du...",D17,C965,Pharmacy,4.0,4.0,53.401599,-6.194631
320,Meaghers Pharmacy Churchtown,"Unit 2, 96/98 Churchtown Rd Upper, Churchtown ...",D14,K440,Pharmacy,5.0,1.0,53.295243,-6.259130
321,LloydsPharmacy,"14 Bird Ave, Friarland, Dublin 14",D14,NaN,Pharmacy,3.3,8.0,53.305152,-6.236978
322,Corr's Pharmacy,"Unit 6 Clonshaugh Shopping Centre, Coolock, Du...",D17,NaN,Pharmacy,4.3,7.0,53.403317,-6.207439
323,McCabes Pharmacy CLAREHALL,"Clarehall Shopping Centre, Malahide Rd, Dublin 17",D17,NaN,Pharmacy,3.6,19.0,53.401178,-6.180903
324,McCabes Pharmacy Support Office,"Unit 6, Roof Garden Offices Clarehall Shopping...",D17,NaN,Pharmacy,NaN,NaN,53.401006,-6.179224
325,Bhagwan's Pharmacy,"Ballinteer Rd, Ballinteer, Dublin",D16,NaN,Pharmacy,4.8,12.0,53.279400,-6.245335
326,Bourkes Allcare Pharmacy,"220 Rathmines Rd Lower, Rathmines, Dublin 6",D06,XC59,Pharmacy,5.0,1.0,53.323421,-6.265321
327,Cromcastle Pharmacy,"69A Cromcastle Rd, Kilmore, Dublin",D05,A6X5,Pharmacy,5.0,4.0,53.396402,-6.222016
328,Meda Health Sales Ireland Limited,"Apartment 6, Apartment building, Saint Nathy's...",D14,YH61,Pharmacy,NaN,NaN,53.295128,-6.257705
329,totalhealth Pharmacy,"43 Northwood Ct, Northwood Park, Santry, Dubli...",D09,NA02,Pharmacy,NaN,NaN,53.401964,-6.261144
330,Cronin's Pharmacy,"Edenmore Shopping Centre, Edenmore, Raheny, Co...",D05,EV67,Pharmacy,5.0,7.0,53.388356,-6.182659

In [50]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.2)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [51]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [52]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(6961, 19)
(6961, 23)

In [53]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/pharmacy_final.xlsx', index = False)

### Primary and secondary school

In [54]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Primary and secondary school')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,St Brigids Girl School,"5 St Brigid's Rd, Blanchardstown, Dublin 5, D0...",D15,F79X,Primary school,3.0,2.0,53.384664,-6.373433
1,St Louis Senior Primary School,"3 Leinster Rd, Rathmines, Louis Lane, Co. Dubl...",D06,N0A1,Primary school,4.1,8.0,53.324727,-6.267897
2,John Scottus Primary School,"47-49 Northumberland Rd, Ballsbridge, Dublin 4...",D04,NaN,School,4.9,20.0,53.334464,-6.237324
3,St. David's Boys National School,"Kilmore Rd, Beaumont, Dublin 5, D05 YY68",D05,K8X9,Primary school,5.0,8.0,53.386056,-6.216173
4,The Teresian School,"12 Stillorgan Rd, Dublin 4, D04 E9X5",D04,NaN,School,4.8,8.0,53.314923,-6.227960
5,Scoil Neasáin,"McAuley Rd, Harmonstown, Dublin 5, D05 VF95",D05,RT20,School,5.0,2.0,53.382146,-6.196239
6,The Embassy Primary School,"5 Clyde Rd, Dublin 4, D04 W292",D04,W292,School,5.0,2.0,53.329453,-6.235399
7,Springdale National School,"Lough Derg Rd, Edenmore, Dublin 5, D05 E954",D05,X316,School,4.2,13.0,53.382313,-6.179557
8,St Patrick Boys National School,"Cambridge Rd, Dublin, D04 AP98",D04,AP98,Primary school,5.0,1.0,53.343392,-6.225355
9,Scoil Aine Girls School,"5 All Saints Rd, Clontarf East, Dublin 5, D05 ...",D05,C960,School,3.5,8.0,53.378067,-6.177423
10,Saint Mary's National School​,"Belmont Ave, Ranelagh, Dublin 4, D04 K025",D06,X0T8,School,4.8,5.0,53.321066,-6.238920
11,"St Brigids GNS, Killester, Dublin 5","St Brigid's Rd, Northside, Killester, Co. Dubl...",D05,YV44,School,5.0,2.0,53.378968,-6.205224
12,St Conleth's College,"28 Clyde Rd, Dublin, D04 FT98",D04,FT98,School,4.8,15.0,53.327961,-6.240349
13,St Benedicts & St Marys National School,"30-68 Grange Park View, Grange, Dublin 5, D05 ...",D05,NaN,School,5.0,4.0,53.388497,-6.164294
14,"Scoil Mhuire, Lakelands GNS","Gilford Rd, Sandymount, Co. Dublin, D04 DC04",D04,DC04,School,4.8,5.0,53.328315,-6.211172
15,Shellybanks Educate Together School,"Seafort Ave, Dublin 4, D04 F8P5",D04,H330,School,5.0,6.0,53.333026,-6.214351
16,St. Christopher's Primary School,"Haddington Rd, Dublin, D04 FP20",D04,FP20,School,4.8,5.0,53.335503,-6.240301
17,Special Primary School,"46 Seville Pl, North Dock, Dublin 1, D01 K227",D01,K227,Primary school,NaN,NaN,53.351587,-6.242852
18,St. Joseph's CBS Secondary School,"Merville Ave, Fairview, Dublin 3, D03 H524",D03,VY92,High school,3.9,12.0,53.363939,-6.233694
19,Gouyang Primary School,"34 Aungier St, Dublin 2, D02 HK75",D02,HK75,School,NaN,NaN,53.338913,-6.265536
20,The Georgian Montessori Primary School,"40 Belvedere Pl, Mountjoy, Dublin, D01 W3W5",D01,V4F5,School,5.0,1.0,53.358042,-6.257813
21,Saint Columba's National School,"Waterloo Ave, North Strand, Dublin, D03 NH34",D03,NH34,School,5.0,4.0,53.358710,-6.242333
22,Catholic University School,"89 Leeson Street Lower, Dublin 2, D02 KC81",D02,NaN,Catholic school,3.5,13.0,53.335271,-6.255883
23,Scoil Chaoimhin,"Marlborough Street, North City, Dublin, D01 YT29",D01,YT29,Primary school,3.7,3.0,53.351326,-6.257607
24,St. Joseph's Co-Educational National School,"126 E Wall Rd, East Wall, Dublin 3, D03 K220",D03,K220,School,5.0,6.0,53.354366,-6.228532
25,International School of Dublin,"Synge St, Saint Kevin's, Dublin, D08 PW64",D08,PW64,Private school,4.0,10.0,53.333257,-6.266979
26,Howth Road Mixed National School,"Clontarf Rd, Northside, Dublin 3, D03 E166",D04,FT66,School,2.0,4.0,53.363940,-6.224493
27,Scoil Chaitríona Baggot Street,"59 Baggot Street Lower, Dublin 2, D02 H365",D02,C625,School,4.8,4.0,53.336205,-6.246258
28,O'Connell Secondary School,"13 Richmond St N, Drumcondra, Dublin, D01 V1K2",D01,V1K2,Middle school,3.9,15.0,53.358165,-6.250703
29,St Vincents Infant Boys School,"26 William St N, Northside, Dublin, D01 A5V0",D01,A5V0,School,5.0,1.0,53.357101,-6.247245
...,...,...,...,...,...,...,...,...,...
451,Rathmichael Parish National School,"Stonebridge Rd, Shankill, Dublin",D18,NaN,School,5.0,5.0,53.236146,-6.127750
452,Mater Christi Secondary School,"Heathfield View, Kildonan, Dublin",D11,NaN,High school,NaN,NaN,53.394831,-6.321018
453,St.Mary's College,"73_79, Rathmines Rd Lower, Rathmines, Dublin 6",D06,HW58,School,4.3,17.0,53.327562,-6.267247
454,Firhouse Community College,"Firhouse Rd, Dublin 24",D24,CX39,School,2.9,13.0,53.276232,-6.348494
455,"Marino College, Marino Mart, Dublin","15-21 Marino Mart, Northside, Dublin 3",D03,AD90,School,3.0,1.0,53.364247,-6.231430
456,St. Marnock’s National Catholic School,"Strand Rd, Burrow, Portmarnock, Co. Dublin",D13,NaN,School,5.0,4.0,53.422298,-6.134784
457,St Helen's Tuition Centre,"Limetree Ave, Robswalls, Portmarnock, Co. Dublin",D13,NaN,School,4.5,4.0,53.439210,-6.136242
458,St Helens Jr School,"Limetree Ave, Robswalls, Portmarnock, Co. Dublin",D13,NaN,School,NaN,NaN,53.438998,-6.135762
459,Trinity Comprehensive School,"Ballymun Rd, Northside, Dublin 9",D09,A4N8,School,3.9,14.0,53.393579,-6.263472
460,ST MARY'S SECONDARY SCHOOL,"Holy Faith Convent, Clare Rd, Northside, Dublin 9",D09,NaN,High school,5.0,2.0,53.375900,-6.272866
461,Mount Carmel Secondary School,"King's Inns St, Northside, Dublin 1, D01 W657",D01,W657,Single sex secondary school,3.7,11.0,53.351972,-6.268311
462,holy faith secondaryschool,"Philipsburgh Ave, Northside, Dublin",D03,NaN,School,NaN,NaN,53.367692,-6.239772
463,Maryfield College,"Sion Hill Rd, Grace Park, Dublin",D09,NaN,School,3.1,10.0,53.376004,-6.235165
464,Mercy College,"St Brendan's Dr, Northside, Dublin",D05,NaN,School,5.0,2.0,53.386251,-6.199622
465,O'Farrell School Wear,"Unit 104, Kingsford Cross, Strand Rd, Burrow, ...",D13,A028,School,4.7,15.0,53.422650,-6.135185
466,Sandymount Park Educate Together Secondary School,"16 Simmonscourt Rd, Dublin",D04,NaN,School,NaN,NaN,53.326000,-6.225889
467,Dominican College,"204 Griffith Ave, Drumcondra, Dublin 9",D09,NaN,School,4.4,8.0,53.374364,-6.249518
468,St. Fiachra's Senior National Catholic School,"Montrose Park, Beaumont, Dublin 5",D05,NaN,School,3.7,3.0,53.387240,-6.226844
469,The Institute of Education,"85 Leeson Street Lower, Dublin",D02,NaN,School,4.4,31.0,53.335053,-6.255542
470,Coolmine Community School,"Clonsilla, Dublin",D15,NaN,Community school,5.0,1.0,53.349809,-6.260274
471,Gaelscoil Bhaile Munna,"Coultry Rd, Ballymun, Dublin, 9",D09,NaN,School,5.0,3.0,53.398206,-6.255974
472,Gardiner Street School,"6 Belvedere Court, Mountjoy, Dublin",D01,HX30,School,3.6,8.0,53.357882,-6.258940
473,St Marys Boys National School,"Haddington Rd, Dublin",D04,NaN,School,5.0,4.0,53.334323,-6.241028
474,S N Seosamh Na Mbrathar,"Clontarf West, Dublin",D03,NaN,School,NaN,NaN,53.364752,-6.233361
475,Abacas Kilbarrack,"5 Greendale Rd, Northside, Dublin 5",D05,NY54,School,NaN,NaN,53.387060,-6.156940
476,St Eithnes Girls National School,"Edenmore Ave, Edenmore, Dublin 5",D05,A7X6,School,4.4,9.0,53.389311,-6.180828
477,Scoil Bhríde,"Grange Rd, Donaghmede, Dublin",D13,NaN,School,5.0,2.0,53.397125,-6.161100
478,Lindsay Road National School,"Lindsay Rd, Glasnevin, Dublin 9",D09,T2F3,School,3.0,2.0,53.364913,-6.264743
479,Scoil an tSeachtar Laoch,"Ballymun Rd, Ballymun, Dublin 11",D11,NaN,School,3.9,7.0,53.392702,-6.264820
480,Belgrove girls school,"Clontarf East, Dublin",D03,NaN,School,5.0,1.0,53.363868,-6.199438

In [55]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [56]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [57]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(6818, 19)
(6818, 23)

In [58]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/primary_secondary_school_final.xlsx', index = False)

## GP

In [59]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','GP')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Dr. C. Donaghy,"109 Dorset Street Lower, Northside, Dublin 1",D01 X953,General practitioner,4.4,14.0,53.358024,-6.263544
1,Capel Street Medical Centre,"138 Capel St, North City, Dublin, D01 C4E9",D01 C4E9,General practitioner,4.7,91.0,53.347860,-6.268725
2,Dr Edel Dominique,"Clare St, Dublin 2, D02 VX59",D02 CK80,General practitioner,4.6,20.0,53.341471,-6.252176
3,Temple Bar Medical Centre,"26 Wellington Quay, Temple Bar, Dublin, D02 R221",D02 R221,General practitioner,5.0,16.0,53.345666,-6.264570
4,"D15 G.P., Dr Anas Mansour, MICGP, MUDR, MD, Ge...","D15GP, Unit 3 Ground Floor, Main St, Blanchard...",D15 YP03,Doctor,4.1,63.0,53.386900,-6.377402
5,Generation Health Medical Clinic,"9A Castlecourt Shopping Centre, Castleknock, D...",D15 E652,General practitioner,3.9,10.0,53.374805,-6.363206
6,Ballsbridge Medical Centre,"66 Merrion Rd, Ballsbridge, Dublin 4, D04 N1W5",D04 N1W5,Doctor,3.6,30.0,53.327128,-6.224904
7,Griffith Avenue Practice,"411 Griffith Ave, Whitehall, Dublin 9, D09 YY19",D09 YY19,General practitioner,3.7,7.0,53.378135,-6.260983
8,Rafter's Medical Centre Rathmines,"Rathmines Road Lower Rathmines Rd Lower, Rathm...",D06 HW58,General practitioner,3.5,19.0,53.322875,-6.265924
9,Sirona Medical,"185 Cabra Rd, Northside, Dublin 7, D07 FR52",D07 FR52,General practitioner,3.2,11.0,53.361602,-6.291004
10,Summerhill Family Practice,"Summerhill, Mountjoy, Dublin",D01 A031,General practitioner,3.5,4.0,53.355661,-6.253201
11,Chapelizod Medical Centre,"Belgrove Park, Chapelizod, Dublin",D20,General practitioner,4.4,11.0,53.350732,-6.350963
12,Marino Medical Centre,"144 Philipsburgh Ave, Northside, Dublin 3, D03...",D03 R6X6,General practitioner,4.7,11.0,53.368822,-6.239072
13,Corvin Medical Centre,"201 Sevenoaks, Sarsfield Rd, Dublin",D10,General practitioner,2.3,3.0,53.341618,-6.327047
14,Templeogue Village Medical,"184 Templeogue Rd, Templeogue Village, Dublin",D6W WN53,General practitioner,5.0,8.0,53.298265,-6.303698
15,Dr Robert Dybkowski and Dr Ilona Izdebska medi...,"No 1, Orby Chambers, 7 Coke Ln, Smithfield, Du...",D07 NV02,Doctor,3.5,57.0,53.346848,-6.279559
16,"Oakwood Medical Clinic, Castleknock","Castlecourt Shopping Centre, 3, Dublin 15",D15 E652,General practitioner,3.9,16.0,53.374861,-6.363201
17,Dr. John Blennerhassett,"80 Malahide Rd, Northside, Dublin 3, D03 N9C8",D03 N9C8,General practitioner,NaN,NaN,53.367949,-6.226615
18,Clontarf General Practice,"188 Clontarf Rd, Clontarf East, Dublin 3, D03 ...",D03 C3W0,General practitioner,4.2,5.0,53.359506,-6.196921
19,Iveagh Medical Clinic,"235 Crumlin Rd, Crumlin, Dublin 12, D12 WR53",D12 WR53,General practitioner,3.9,14.0,53.327633,-6.308049
20,Rowan Family Practice,"123 Churchtown Rd Lower, Churchtown Lower, Dub...",D14 E840,General practitioner,5.0,10.0,53.296645,-6.253906
21,Dr. Martin Maguire,"40 Drumcondra Rd Upper, Drumcondra South, Dubl...",D09 C4H3,General practitioner,3.7,3.0,53.369717,-6.253959
22,Irishtown & Ringsend Primary Care Centre,"Irishtown Rd, Dublin",D04,General practitioner,3.4,21.0,53.340728,-6.225657
23,Dr Anver Amod,"44 R118, Co. Dublin",D02,General practitioner,4.3,6.0,53.342840,-6.249920
24,Dr. Fred Shackleton GP,"115 Cromwellsfort Rd, Walkinstown, Dublin 12, ...",D12 YR27,General practitioner,3.7,6.0,53.316961,-6.322847
25,Kirkfield Clinic,"Blanchardstown Primary Care Centre, Grove Rd, ...",D15 HNT2,General practitioner,4.8,5.0,53.391130,-6.394036
26,Dr Robert Nelson,"17 Beechpark Ave, Castleknock, Dublin 15, D15 ...",D15 HP5H,General practitioner,5.0,2.0,53.378112,-6.358579
27,Perrystown Medical Centre,"171 Whitehall Rd, Terenure, Dublin 12, D12 P030",D12 P030,General practitioner,4.8,5.0,53.307601,-6.319332
28,Dr. Dolores Rafter,"2 Hazelwood Ave, Clonsilla, Dublin 15, D15 VP04",D15 KCW9,General practitioner,5.0,2.0,53.393617,-6.418285
29,St Jude Family Practice,"69A Orwell Park Rise, Templeogue, Dublin 6W, C...",D6W AF86,General practitioner,5.0,7.0,53.299562,-6.323697
...,...,...,...,...,...,...,...,...
137,Dundrum Family Practice,"218 Barton Rd E, Dundrum, Dublin 14, D14 AE92",D14 AE92,Doctor,4.0,5.0,53.288717,-6.246854
138,Moe Family Practice,"Woodlawn, Clonskeagh Rd, Farranboley, Dublin 14",D14 X5R3,General practitioner,5.0,1.0,53.308040,-6.237337
139,Dr Abdul Rashid Ibrahim,"52 Ascaill Ard an Rátha, Grange, Dublin 13, D1...",D13 RK03,Doctor,5.0,8.0,53.396317,-6.169539
140,Clongriffin Medical Centre,"17A Main St, Clongriffin, Dublin 13, D13 CT89",D13 N2Y4,Doctor,4.2,13.0,53.402377,-6.152325
141,Dr. Luke B. Brady,"65 Knockcullen Dr, Ballyroan, Dublin 16, D16 ET78",D16 ET78,Doctor,4.5,4.0,53.286825,-6.309786
142,Dr. Ashcroft-Jones,"1 Grange Manor Dr, Rathfarnham, Dublin, D16 X254",D16 X254,Doctor,5.0,3.0,53.285504,-6.272591
143,Bayside Surgery,"Bayside Shopping Centre, Bayside Square E, Nor...",D13 C2F6,Doctor,4.8,8.0,53.388413,-6.140352
144,Dr. Alex Khourie,"5 St Enda's Dr, Rathfarnham, Dublin 14, D14 T2P8",D14 P6F2,Doctor,4.0,4.0,53.289172,-6.283425
145,David Kelly,"114 Morehampton Rd, Dublin 4, D04 K3H7",D04 K3H7,Doctor,NaN,NaN,53.323378,-6.238335
146,Dr K.B Olinger,"Village Centre, Unit 6, The, Watery Ln, Dublin 22",D22 AW72,Doctor,4.3,12.0,53.322655,-6.393011
147,The Meridian Clinic Clarehall,"13 Malahide Rd, Grange, Dublin",D03 TH73,Doctor,3.3,24.0,53.401204,-6.180002
148,Dr Patrick O'Connor,"Glenveiw Medical Center 24, 12 Glenview Park, ...",D24 DX6K,Doctor,5.0,4.0,53.288750,-6.347608
149,Grange Mount Surgery,"Grange, Co. Dublin",D16,General practitioner,NaN,NaN,53.609405,-6.252330
150,Glenfield Family Practice,"20 Glenfield Ave, Rowlagh, Dublin, D22 E309",D22 E309,Doctor,4.2,11.0,53.347527,-6.398420
151,Newlands Cross Medical Centre,Newlands Cross Medical Centre Aldi Shopping Co...,D22,Doctor,3.9,25.0,53.313322,-6.394556
152,Doctor Wilson,"15 Ashwood Rd, Clonburris Great, Dublin 22, D2...",D22 C7P9,Doctor,5.0,4.0,53.326159,-6.410975
153,Manor Road Surgery,"31 Manor Rd, Redcowfarm, Dublin 20, D20 AW73",D20 AW73,Doctor,3.6,21.0,53.351019,-6.368593
154,School Age Team HSE,"off, Leopardstown Shopping Centre, Unit 10/11,...",D18,Doctor,NaN,NaN,53.259254,-6.196897
155,Dr. Paul McCormick,"218 Barton Rd E, Dundrum, Dublin 14, D14 AE92",D14 AE92,Doctor,5.0,2.0,53.288706,-6.246909
156,EAST DOC,"Elm Park, Dublin 4, D04 W6N7",D04 W6N7,Doctor,3.6,9.0,53.317594,-6.209613
157,Healthwell Clinic,"15 Clonsilla Rd, Clonsilla, Dublin, D15 TC6X",D15 P2Y8,Doctor,2.3,9.0,53.382547,-6.406679
158,HSE Health Centre Cabra,"75-87 Quarry Rd, Northside, Dublin 7, D07 X002",D07 H7P8,Doctor,3.7,3.0,53.364602,-6.288845
159,Dr. Desmond Coady,"1 Old Bawn Way, Oldbawn, Dublin 24, D24 XF7A",D24 R7DK,Doctor,5.0,6.0,53.279945,-6.359809
160,"Glenview Medical, Centric Health","Ireland, 192B Glenview Park, Dublin 24",D24 K030,Doctor,NaN,NaN,53.288620,-6.344050
161,Ballycullen Medical Centre,"Oldcourt Shopping Centre, 24 Parklands Rd, Dub...",D24 PXV3,Doctor,5.0,5.0,53.274757,-6.345037
162,Dr. Alvise Calamai,"Blanchardstown Primary Care Centre, Grove Rd, ...",D15 HNT2,Doctor,5.0,6.0,53.391118,-6.394063
163,Old Bawn Family Practice,"59a Old Bawn Way, Tallaght, Dublin, D24 RY77",D24 RY77,Doctor,5.0,1.0,53.279810,-6.364290
164,Greenlea Clinic,"118 Greenlea Rd, Terenure, Dublin, D6W WY18",D6W WY18,Doctor,3.8,19.0,53.307378,-6.300449
165,"Old Bawn Medical, Centric Health","Unit 2 & 3 Old Bawn Shopping Centre , Tallaght...",D24 NVR4,Doctor,5.0,1.0,53.285491,-6.360923
166,Dr Ronan Donohoe,"59A Old Bawn Way, Oldbawn, Dublin 24",D24 R7DK,Doctor,4.1,7.0,53.279611,-6.364166

In [60]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.35)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [61]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [62]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(3002, 19)
(3002, 22)

In [63]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/gp_final.xlsx', index = False)

### Sports facility

In [64]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Sports facility')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Scoil Ui Chonaill GAA Club,"95 Clontarf Rd, Clontarf East, Dublin 3, D03 F862",D03,C2X0,Sports club,4.5,12.0,53.361138,-6.207547
1,Trinity College Sports Centre,"43 Pearse St, Dublin 2, D02 W085",D02,NaN,Sports complex,4.3,195.0,53.344057,-6.249955
2,Dublin Port Stadium Stella Maris F.C.,"3 Waterfall Ave, Dublin Port, Drumcondra, Stad...",D03,A4W5,Football club,4.2,87.0,53.366247,-6.247590
3,Cymc/L C Pitch & Putt Club,"80 Philipsburgh Ave, Northside, Dublin 3, D03 ...",D03,H3F1,Sports complex,5.0,6.0,53.366066,-6.239358
4,Lourdes Celtic F.C. Football Pitch and Soccer ...,"32 Henry St, Harold's Cross, Dublin, D01 V279",D01,V279,Soccer club,4.7,26.0,53.326220,-6.291067
5,Dublin Docklands Boxing Club,"Arch 3, Seville Pl, Dublin 1, D01 X2T5",D01,X2T5,Boxing club,4.6,5.0,53.354210,-6.246376
6,Corinthians Boxing Club,"off, 2 Bella Place, Buckingham Street Upper, M...",D01,XT81,Boxing club,5.0,3.0,53.354777,-6.250442
7,SPORTSCO,"S Lotts Rd, Dublin 4, D04 R6C2",D04,FR83,Sports complex,4.4,501.0,53.339529,-6.230142
8,BeatBox Boxing Club,"28 Lower Leeson Street Lower, Saint Kevin's, D...",D02,KF97,Boxing club,5.0,36.0,53.333957,-6.255061
9,Pembroke Wanderers Hockey Club,"27A Serpentine Ave, Dublin 4, D04 T329",D04,NaN,Hockey club,4.4,185.0,53.329345,-6.225141
10,Donnybrook Lawn Tennis Club,"4 Brookvale Rd, Ranelagh, Dublin 4, D04 K5V6",D04,K5V6,Sports club,4.5,23.0,53.319440,-6.234087
11,Elm Park Golf & Sports Club,"Nutley House, Nutley Ln, Dublin",D04,WE09,Golf club,4.4,144.0,53.313897,-6.217228
12,Old Wesley,"Donnybrook, Co. Dublin, D04 EY28",D04,NaN,Rugby club,4.5,102.0,53.320090,-6.232962
13,Ballyfermot United Sports & Social Club,"2 Blackditch Rd, Cherry Orchard, Dublin 10, D1...",D10,W738,Sports club,4.1,84.0,53.341819,-6.357480
14,A1 Coaching,"1 Portland St N, Ballybough, Dublin 1, D01 EY00",D01,K768,Sports complex,NaN,NaN,53.359500,-6.256176
15,Dublin City Handball,"27 Mariners Port, North Dock, Dublin",D01,Y0A2,Handball club,5.0,1.0,53.350305,-6.243096
16,Skyvelo Ireland Cycling Club,"3 Burlington Rd, Ballsbridge, Dublin, D04 RD68",D04,RD68,Sports club,NaN,NaN,53.332179,-6.245760
17,Erins Isle GAA Club,"Farnham Dr, Northside, Dublin",D11,NaN,Sports complex,4.4,226.0,53.384970,-6.300142
18,Railway Union Sports Club,"Park Ave, Dublin 4",D04,K462,Sports complex,4.2,164.0,53.325840,-6.212426
19,Wanderers Rugby Club House,"65A Merrion Rd, Ballsbridge, Dublin 4, D04 F8F8",D04,F8F8,Rugby club,4.2,74.0,53.322846,-6.220853
20,Old Belvedere Rugby Club,"Ailesbury Grove, Ballsbridge, Dublin, D04 HF60",D04,NaN,Rugby club,4.2,174.0,53.321602,-6.228584
21,Dublin Chess Club,"3 Fitzwilliam Street Upper, Dublin 2, D02 RR50",D02,RR50,Sports complex,5.0,7.0,53.336609,-6.249609
22,Energia 7's,"Energia Park, 4 Donnybrook Rd, Donnybrook, Co....",D04,VE84,Sports club,NaN,NaN,53.322618,-6.236989
23,Dublin GAA,"Parnell Park, Clancarthy Rd, Northside, Dublin...",D05,X971,Sports club,4.1,21.0,53.372675,-6.217866
24,Ballsbridge Football Club,"Herbert Park, Ballsbridge, Dublin 4, D04 FE40",D04,FE40,Football club,5.0,1.0,53.325320,-6.234150
25,Loop Table Tennis Club,"Ardscoil La Salle, Raheny Rd, Donaghmede, Rahe...",D05,Y132,Table tennis club,4.9,17.0,53.389696,-6.169581
26,St Brigids GAA Club,"Russell Park, Navan Rd, Castleknock, Dublin 15",D15,NaN,Sports complex,4.4,210.0,53.377522,-6.351350
27,Parnells GAA Club,"30 Main Street, Coolock, Dublin 5, D05 H2W0",D05,F2P5,Sports complex,4.2,594.0,53.388390,-6.204958
28,St. John Vianney Football Club,"Kilmore Dr, Beaumont, Dublin, D05 Y765",D05,Y765,Soccer club,3.7,17.0,53.388665,-6.208187
29,UCD Karate,"UCD Sports Centre, University College Dublin, ...",D04,NaN,Martial arts club,5.0,8.0,53.308137,-6.228915
...,...,...,...,...,...,...,...,...,...
281,Red Arches Pitch,"Northside, Baldoyle, Co. Dublin",D13,NaN,Sports complex,3.5,2.0,53.400606,-6.134011
282,Malahide Fingal Hockey Club,"Unnamed Road, Sainthelens, Malahide, Co. Dublin",D17,NaN,Sports club,4.6,8.0,53.439905,-6.150491
283,Poppintree Community And Sports Centre,"Balbutcher Ln, Ballymun, Dublin",D11,NaN,Sports complex,4.4,32.0,53.402879,-6.274250
284,"Pitches 1-7 St Annes Park, Clontarf","Clontarf, Dublin",D03,NaN,Sports complex,NaN,NaN,53.375151,-6.186777
285,Broomfield St. Sylvester's GAA Pitches,"Unnamed Road, Sainthelens, Malahide, Co. Dublin",D17,NaN,Sports club,NaN,NaN,53.438720,-6.151558
286,Raheny GAA Pitch 9,"76-90 All Saints Rd, Clontarf East, Dublin",D05,TK71,Sports complex,3.9,12.0,53.375064,-6.172847
287,Palmerstown Sport Complex,"Oakcourt Ave, Johnstown, Palmerstown, Co. Dublin",D20,NaN,Sports complex,4.2,75.0,53.347865,-6.375080
288,Saint Monica's Gaa,"10, 12 Millwood Park, Grange, Dublin",D05,A5R3,Sports complex,3.9,14.0,53.388832,-6.178250
289,National Tennis Centre,"9 Albert College Park, Whitehall, Dublin 9",D09,AE28,Sports complex,4.5,10.0,53.384463,-6.260495
290,Pitch 30 Clontarf GAA,"Clontarf East, Dublin",D03,NaN,Sports complex,4.0,3.0,53.370728,-6.182849
291,Portmarnock Chess Club,"Clg Naomh Mearnog, Blackwood Lane, Portmarnock...",D13,NaN,Chess club,NaN,NaN,53.434639,-6.140387
292,Cricket Ireland High Performance Training Centre,"Sport Ireland National Sports Campus, Snugboro...",D15,NaN,Sports complex,NaN,NaN,53.394931,-6.353247
293,Portrane Athletic Football Club,Co. Dublin,D01,NaN,Soccer club,4.1,21.0,53.491511,-6.119147
294,Setanta GAA Club,"123 Ballymun Rd, Ballymun, Dublin",D09,W523,Sports complex,4.3,89.0,53.390833,-6.265278
295,Irish Institute of Sports Surface,"Swords Rd, Northside, Dublin 9",D09,DK44,Sports club,1.0,1.0,53.401471,-6.243536
296,Ridgewood New Pitches,"53 The Elms, Rathingle, Co. Dublin",D15,NaN,Football club,3.9,11.0,53.447614,-6.253304
297,Dublin Kendo Kobukai,"Haverty Road, Clontarf West, Dublin",D03,NaN,Sports club,NaN,NaN,53.364722,-6.233405
298,Glasnevin Basketball Club,"St Aidans CBS, Whitehall, Dublin 9",D24,YX6V,Sports club,NaN,NaN,53.384478,-6.251470
299,Dublin Kendo Kobukai,"Grace Park, Dublin",D09,NaN,Sports club,NaN,NaN,53.373792,-6.233759
300,Dublin Kendo Kobukai,"Ballybough, Dublin",D03,NaN,Sports club,NaN,NaN,53.360752,-6.243024
301,A.B.S Powerlifting,"Unit 5 Tolka Valley Industrial Estate, Ballybo...",D11,NaN,Sports club,5.0,27.0,53.376492,-6.295251
302,Glin Boxing Club,"Unit 2, 5 Clonshaugh Rd, Northside, Dublin",D17,NX32,Boxing club,3.7,6.0,53.398043,-6.215624
303,St. Margaret's Golf & Country Club,"Skephubble, St Margaret's, Co. Dublin",D11,NaN,Golf club,4.5,402.0,53.451439,-6.304092
304,Dublin Kendo Kobukai,"Davitt Rd, Dublin Southside, Dublin",D12,NaN,Sports club,NaN,NaN,53.335156,-6.318303
305,Ballymun United Soccer Complex,"St Margaret's Road, Ballymun, Dublin 11",D11,NaN,Soccer club,4.7,54.0,53.407055,-6.278565
306,St Pauls Artane Football Club,"Gracefield Ave, Northside, Artane, Co. Dublin, 5",D05,DR12,Football club,4.3,41.0,53.382275,-6.194623
307,Dublin Combat Academy,"Unit 2 7, Cross Guns Business Park, 7 Royal Ca...",D07,X0W7,Martial arts club,5.0,10.0,53.363696,-6.271252
308,Shankill GAA Shanganagh Cliffs Pitch,"Hackettsland, Dublin",D18,NaN,Sports club,4.8,4.0,53.239841,-6.113179
309,Sportsworld Terenure Running Club,"68 Rathdown Ave, Terenure, Dublin, DUBLIN 6W",D6W,VW80,Athletic club,4.9,8.0,53.302525,-6.289237
310,Batterstown GAA Pitch,"5, 53°28'26.0""N 6°32'41., 6 Richmond St N, Dub...",D01,A0E7,Sports complex,4.3,26.0,53.473889,-6.544861

In [65]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.45)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [66]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [67]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(3401, 19)
(3401, 23)

In [68]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/sports_facility_final.xlsx', index = False)

### College and university

In [69]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','College and university')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Harmony School of Music/Tipperary Fine Foods,"10 Fairview Strand, Northside, Dublin 3, D03 VX48",D03,VX48,University,NaN,NaN,53.362540,-6.238159
1,Pulse College,"20 Ringsend Rd, Dublin 4, D04 CF66",D04,CF66,College,4.6,15.0,53.342172,-6.234706
2,Dorset College,"8 Belvedere Pl, Mountjoy, Dublin, D01 EV27",D01,EV27,College,3.7,29.0,53.358172,-6.257379
3,Hibernia College,"Block B, The Merrion Centre, Merrion Rd, Dubli...",D04,H2H4,College,2.4,7.0,53.319161,-6.213845
4,Trinity College Dublin,"College Green, Dublin 2",D02,VR66,University,4.5,1780.0,53.343793,-6.254572
5,Clonliffe College Seminary,"Clonliffe Rd, Drumcondra, Dublin",D03,NaN,Christian college,5.0,1.0,53.364486,-6.253315
6,University College Dublin,"University College Dublin, Belfield, Dublin 4",D14,K5X0,University,4.5,319.0,53.306749,-6.221034
7,Griffith College,"S Circular Rd, Merchants Quay, Dublin 8, D08 V04N",D08,W56T,College,4.0,153.0,53.330989,-6.278118
8,DCU St Patrick's Campus,"Drumcondra Rd Upper, Drumcondra, Dublin 9",D09,HY29,University,4.3,38.0,53.370180,-6.254689
9,Dublin College of Advanced Studies,"98 Capel St, Rotunda, Dublin 1, D01 HP52",D01,HP52,College,3.9,18.0,53.350174,-6.269685
10,TU Dublin City Campus Mountjoy Square,"41-45, Mountjoy Square S, Mountjoy, Dublin 1, ...",D01,A998,Technical university,4.1,10.0,53.355818,-6.256919
11,CCT College Dublin,"30-34 Westmoreland St, Dublin 2, D02 HK35",D02,NaN,College,4.4,35.0,53.346041,-6.258875
12,Dublin Business School,"13/14 Aungier St, Dublin, D02 WC04",D02,NaN,College,3.7,90.0,53.340538,-6.265492
13,TU Dublin Sackville Place,"5 Sackville Pl, North City, Dublin 1, D01 FH94",D01,FH94,Technical university,3.0,1.0,53.348974,-6.258546
14,Technological University Dublin Bolton Street ...,"Bolton St, Rotunda, Dublin, D01 K822",D01,K822,University,4.2,44.0,53.351515,-6.269278
15,Royal College of Surgeons in Ireland,"123 St Stephen's Green, Dublin, D02 YN77",D02,YN77,University,4.2,72.0,53.338962,-6.262036
16,Independent College Dublin,"Block B, The Steelworks, Foley Street, Dublin ...",D01,X997,College,4.0,12.0,53.352644,-6.250364
17,National College of Ireland,"Mayor Street Lower, International Financial Se...",D01,NaN,College,4.0,96.0,53.349103,-6.242812
18,TCD School of Nursing & Midwifery,"The Gas Building, 24 D'Olier Street, Dublin, D...",D02,T283,University,5.0,4.0,53.346556,-6.257853
19,Irish Bible Institute,"Ulysses House, Foley St, Mountjoy, Dublin 1, D...",D01,WA07,Christian college,4.7,18.0,53.351914,-6.250878
20,Oxford College International,"5 Abbey Street Lower, North City, Dublin 1, D0...",D01,P7V2,College,NaN,NaN,53.348672,-6.258879
21,College of Naturopathic Medicine,"CNM Ireland, 25 Wolfe Tone St, North City, Dub...",D01,E167,College,3.7,7.0,53.349400,-6.267823
22,Kilroy's College,"Wentworth, 13 Eblana Villas, Grand Canal Stree...",D02,T268,College,5.0,2.0,53.340810,-6.242938
23,Dublin City University,"Dublin City University Glasnevin, Dublin 9",D11,W8H1,University,4.3,242.0,53.386094,-6.256369
24,Griffith College City Centre,"25 Wolfe Tone St, North City, Dublin 1, D01 X9K7",D01,X9K7,Private college,4.8,9.0,53.349400,-6.267823
25,Technological University Dublin - City Campus,"Aungier St, Dublin, D02 HW71",D02,HW71,University,4.4,85.0,53.338530,-6.266599
26,TU Dublin Kevin Street,"Kevin Street, Portobello, Dublin 2, D08 X622",D08,F2K3,University,4.3,56.0,53.337144,-6.268237
27,Boston College Ireland,"43 St Stephen's Green, Dublin 2, D02 DY80",D02,DY80,University,4.6,5.0,53.338262,-6.255360
28,GMB College,"14 Mount Street Upper, Dublin 2, D02 EY24",D02,EY24,College,4.0,2.0,53.337710,-6.245939
29,Champlain College Dublin,"43 Leeson Street Lower, Saint Kevin's, Dublin ...",D02,EH10,College,5.0,1.0,53.333022,-6.254051
...,...,...,...,...,...,...,...,...,...
128,Ringsend College,"Cambridge Rd, Dublin 4",D06,HH76,College,3.0,4.0,53.343755,-6.224509
129,Trinity Online Services,"3/ Dublin 2 Ireland, 4 Foster Pl, Dublin",D02,NaN,University,NaN,NaN,53.344827,-6.261318
130,Coláiste na hÉireann,"Clare Ln, Dublin 2",D02,NaN,College,NaN,NaN,53.341543,-6.251294
131,TU Dublin Faculty of Tourism and Food,"Dublin Institute of Technology, Cathal Brugha ...",D01,NaN,Technical university,NaN,NaN,53.352060,-6.260187
132,TCD Arts Building,"20-32 Nassau St, Dublin",D02,VY46,University,NaN,NaN,53.343239,-6.256538
133,Unigran Dublin,"Zhivago Building, Seda College, Dublin Institu...",D06,NaN,Private university,5.0,3.0,53.350484,-6.269391
134,Trinity Research & Innovation,"O'Reilly Institute, Trinity College Dublin, Du...",D03,DH67,University,5.0,1.0,53.343345,-6.250045
135,Drumcondra House,"167 R132, Drumcondra, Dublin",D09,NaN,University,NaN,NaN,53.371031,-6.249237
136,"DIT Grangegorman, Rathdown House","TU Dublin Grangegorman, Rathdown Rd, Arran Qua...",D07,NaN,University,NaN,NaN,53.354784,-6.279085
137,Lloyd Institute,"42A Pearse St, Dublin",D02,EA22,University,4.7,7.0,53.343818,-6.250987
138,Department of Psychiatry,"38 Eccles St, Phibsborough, Dublin 7",D07,V294,University,NaN,NaN,53.359247,-6.268949
139,testprepDublin,"41B Drury St, Dublin",D02,DP11,University,NaN,NaN,53.342374,-6.263371
140,"Greenway Hub, TU Dublin","Grangegorman, Dublin",D07,NaN,University,NaN,NaN,53.356784,-6.279265
141,TU Dublin North House,"Grangegorman Lower, Arran Quay, Dublin",D07,NaN,University,NaN,NaN,53.356345,-6.283620
142,University College Dublin,"Merrion Rd, Dublin",D04,NaN,University,NaN,NaN,53.320649,-6.215804
143,"Trinity College Dublin, School of Nursing and ...","2 Clare St, Dublin 2",D02,CK80,University,NaN,NaN,53.341748,-6.251927
144,Belgrove Student Residences,"Belfield, Dublin",D04,NaN,University,5.0,5.0,53.304572,-6.224095
145,DIT School of Electronic and Communications En...,"Dublin Institute Of Technology, Kevin St, Port...",D08,NF82,University,4.3,3.0,53.336655,-6.267908
146,"Block E, Institute of Technology, Blanchardstown","Blanchardstown Rd N, Ballycoolen, Dublin",D15,NaN,College,NaN,NaN,53.405699,-6.372307
147,"Centre For Talented Youth, Ireland","Dublin City University, Dublin 9",D09,FW22,College,3.0,4.0,53.386029,-6.260915
148,DIT,"Grangegorman Upper, Phibsborough, Dublin",D07,NaN,College,NaN,NaN,53.356762,-6.279085
149,DBL College,"Unit C3, The Steelworks, Foley Street, Dublin 1",D01,NaN,College,NaN,NaN,53.352275,-6.250862
150,Dublin Institute of Technology - Admin and HR,"149 Rathmines Rd Lower, Rathmines, Dublin 6",D06,HW58,College,5.0,1.0,53.325254,-6.265549
151,RCSI Smurfit Building,"Hospital Rd, Beaumont, Dublin",D09,NaN,College,NaN,NaN,53.388954,-6.225557
152,dudance society,"Regent House, Trinity College Dublin, College ...",D02,AT80,College,5.0,1.0,53.344454,-6.258913
153,Agriculture Food Science Center,"Roebuck, Dublin",D14,NaN,College,NaN,NaN,53.307298,-6.224479
154,Adult Basic Education For Everyone (ABLE),"Adult Education Centre, Main St, Blanchardstow...",D15,NaN,College,5.0,2.0,53.386124,-6.375231
155,Trinity,"118-112 R138, Dublin",D01,NaN,College,NaN,NaN,53.344243,-6.259579
156,International School of Business Dublin,"84, 88 South Great George's Street, Dublin",D02,NaN,College,4.7,3.0,53.343711,-6.264589
157,UCD Teaching & Learning,"F309 Newman Building, University College Dubli...",D18,NaN,University,NaN,NaN,53.305487,-6.222079

In [70]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [71]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [72]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(3536, 19)
(3536, 23)

In [73]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/College_university_final.xlsx', index = False)

### Religious activity

In [74]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Religious activity')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Abbey Street Methodist Church,"1 Abbey Street Lower, North City, Dublin",D01,K6R2,Methodist church,4.5,68,53.348712,-6.258178
1,Immanuel Gospel Mission Church IGM Dublin,"1st Floor, 11 Keypoint, Rosemount Business Par...",D11,NaN,Pentecostal church,5.0,9,53.399246,-6.347275
2,Assembly Of God Ireland Ministry Dublin,"2 Rutland Pl, Rotunda, Dublin, D01 FP66",D01,FP66,Christian church,4.5,8,53.353763,-6.261279
3,Dublin Krishna Temple,"83 Middle Abbey St, North City, Dublin 1, D01 ...",D01,EV91,Hindu temple,4.8,24,53.348427,-6.260764
4,St Francis Xavier's Church,"Gardiner Street Upper, Mountjoy, Dublin, D01 RK07",D01,RK07,Catholic church,4.7,184,53.357996,-6.259553
5,Blessed Sacrament Chapel,"20 Bachelors Walk, North City, Dublin 1",D01,NW14,Catholic church,4.6,199,53.347158,-6.261526
6,Immanuel Church Dublin,"28 Bachelors Walk, North City, Dublin 1",D01,P4V6,Christian church,4.5,8,53.347479,-6.260487
7,Bethlehem Christian Fellowship,"Century Business Park, Unit 3B, Dublin 11",D11,NaN,Christian church,5.0,8,53.402099,-6.301452
8,St. Mark's Church,"42A Pearse St, Dublin, D02 R123",D02,EA22,Christian church,4.8,52,53.344737,-6.251019
9,Friends Meeting House (Quakers),"4-5 Eustace St, Temple Bar, Dublin 2, D02 XN59",D02,NaN,Church,4.1,75,53.344570,-6.264876
10,St. Thomas Indian Orthodox Church,"Palmerstown Lower, Dublin",D20,NaN,Christian church,4.0,4,53.357281,-6.375931
11,All Nations Church,"National Boxing Arena, 145 S Circular Rd, Merc...",D08,HY40,Christian church,4.7,30,53.330833,-6.280278
12,Trinity Church Network,"50 Gardiner Street Lower, North City, Dublin 1...",D01,VC03,Church,4.5,11,53.350019,-6.254138
13,Romanian Orthodox Church,"Leeson Park, Ranelagh, Dublin 6",D06,TY77,Orthodox church,4.7,149,53.330231,-6.252083
14,Peoples Church Dublin City,"67 Pearse St, Dublin",D02,NaN,Church,5.0,2,53.343637,-6.245977
15,Ballyroan Parish Church,"Marian Rd, Rathfarnham, Dublin",D14,NaN,Catholic church,4.4,48,53.289931,-6.299307
16,Brahma Kumaris Ireland,"11 Clare St, Dublin, D02 XF25",D02,XF25,Meditation center,4.9,9,53.341473,-6.251226
17,St. Joseph the Artisan Catholic Church,"122 Greencastle Rd, Northside, Dublin 17, D17 ...",D17,PY90,Catholic church,4.3,34,53.397306,-6.203722
18,Saint James's Church,"James's Street North, Dublin 8, D03 VX82",D03,VX82,Catholic church,4.4,99,53.343120,-6.287859
19,St Anthony Parish Church,"Clontarf Rd, Northside, Dublin, D03 HD91",D03,HD91,Church,4.5,42,53.363202,-6.216976
20,"Clontarf Parish, Church of St. John the Baptis...","15 Seafield Rd W, Clontarf East, Dublin, D03 NX77",D03,NX77,Protestant church,4.8,27,53.364131,-6.202417
21,Church of the Nativity of Our Lord,"Montrose Park, Beaumont, Dublin 5",D05,NaN,Catholic church,4.5,47,53.386884,-6.225554
22,St. Brendan's Catholic Church Coolock,"5 Coolock Village, Northside, Dublin 5, D05 Y316",D05,Y316,Catholic church,4.4,90,53.388386,-6.200047
23,Donnycarney Church - Our Lady Of Consolation,"Malahide Rd, Northside, Dublin",D05,NaN,Catholic church,4.3,140,53.374752,-6.218691
24,St. John Vianney Catholic Church,"95 Ardlea Rd, Beaumont, Artane, Co. Dublin, 5",D05,A4X9,Catholic church,4.7,34,53.387070,-6.209002
25,"St Brigid's Church, Killester","Howth Rd, Clontarf East, Killester, Co. Dublin",D05,NaN,Catholic church,4.5,30,53.375422,-6.196911
26,All Saints' Church,"403 Howth Rd, Clontarf East, Raheny, Co. Dublin",D05,YX72,Church,4.7,26,53.378851,-6.179789
27,St Peters Roman Catholic Church,"Saint Peter's Church, Cabra Rd, Dublin, D07 N152",D07,NaN,Catholic church,4.6,178,53.360585,-6.276401
28,Greek Orthodox Church of the Annunciation,"46 Arbour Hill, Stoneybatter, Dublin 7, D07 W6T7",D07,CX33,Orthodox church,4.6,55,53.349727,-6.289740
29,All Saints Parish Church,"Phibsborough Rd, Phibsborough, Dublin 7",D07,NaN,Church,4.4,8,53.358211,-6.273866
...,...,...,...,...,...,...,...,...,...
55,Holy Cross Church & Pastoral Centre,"Main St, Dundrum, Dublin 14, D14 K820",D14,A1K9,Catholic church,4.7,68,53.289465,-6.243890
56,Rathfarnham Church of the Annunciation,"Willbrook Rd, Rathfarnham, Dublin, D14 E803",D14,E803,Catholic church,4.5,57,53.296223,-6.284599
57,Rathfarnham Parish Church of Ireland,"Main St, Rathfarnham, Dublin, D14 Y5N7",D14,Y5N7,Church,4.6,12,53.299588,-6.285422
58,Church of the Good Shepherd,"Nutgrove Ave, Whitehall, Churchtown, Co. Dubli...",D14,NaN,Church,4.6,64,53.293423,-6.261729
59,Church of St John The Evangelist,"Ballinteer, Dublin",D16,NaN,Catholic church,4.5,26,53.274720,-6.256904
60,Church of the Ascension of the Lord - Balally ...,"Cedar Rd, Balally, Dublin, D16 E032",D16,NaN,Catholic church,4.6,28,53.277248,-6.224549
61,Dundrum Methodist Church,"Ballinteer Rd, Ballinteer, Dublin",D16,NaN,Methodist church,4.7,34,53.276371,-6.244033
62,Ballycullen Community Church,"St Colmcille's Community School, Scholarstown ...",D16,H298,Church,5.0,2,53.278965,-6.315030
63,St. Colmcille’s Church,"Idrone Ave, Schollarstown, Dublin 16",D16,ET38,Church,4.6,43,53.283611,-6.318056
64,St. Mary’s Sandyford,"Sandyford, Dublin 18",D18,H9W9,Church,4.4,46,53.270111,-6.226255
65,Saint Brigid's Church,"St Brigid's Church, 18 Johnstown Rd, Cabinteel...",D18,YP96,Church,4.4,36,53.261327,-6.150360
66,Rathmichael Parish Church,"Ferndale Rd, Shankill, Dublin",D18,NaN,Church,4.5,19,53.234380,-6.138263
67,Tullow Parish Church,"18 Brighton Rd, Kerrymount, Dublin 18, D18 RF79",D18,NaN,Church,4.4,17,53.258594,-6.172896
68,Kilternan Parish Church,"Anglican Communion, Enniskerry Rd, Glebe, Kilt...",D18,NaN,Anglican church,4.3,13,53.243652,-6.200096
69,Church of Our Lady of Perpetual Succour,"Foxrock, Dublin 18",D18,Y7N9,Church,4.3,104,53.274216,-6.172495
70,St Anne's Shankill,"Shanganagh Rd, Shankill, Dublin 18",D18,NaN,Church,4.5,76,53.234113,-6.123920
71,Saint Philomena's Church,"Lucan Rd Old, Palmerstown Lower, Dublin 20",D20,YF84,Catholic church,4.1,30,53.357753,-6.374600
72,Our Lady Queen of Peace,"230 Merrion Rd, Dublin, D04 NX33",D04,AW88,Catholic church,4.5,49,53.317943,-6.208978
73,"Saint Mary's Church of Ireland, Donnybrook","Anglesea Rd, Ballsbridge, Dublin 4",D04,P6N2,Church,4.3,14,53.324708,-6.229723
74,Crinken Church,"R119, Dublin Rd, Bray, Co. Dublin",D18,NaN,Church,4.4,16,53.219578,-6.119567
75,Church of the Three Patrons,"Rathgar Rd, Rathmines, Dublin 6, D06 R924",D06,Y5F7,Catholic church,4.7,32,53.317155,-6.271139
76,"The Salvation Army, Dublin South Corps","1st Floor, Swan Shopping Centre, Rathmines, Du...",D06,A448,Christian church,5.0,2,53.323111,-6.265298
77,Christ Church Rathgar,"Rathgar Rd, Rathmines, Dublin 6, D06 CF63",D06,Y5F7,Church,4.6,20,53.312434,-6.273225
78,"Parish of St Columbanus, St Gall and Assumptio...","Milltown Rd, Rathmines, Dublin 6",D06,XW72,Catholic church,4.4,16,53.311728,-6.248202
79,Parish of St Jude the Apostle,"Rossmore Rd, Templeogue, Dublin 6W, Co. Dublin",D6W,HY97,Church,4.0,33,53.298701,-6.319718
80,Grosvenor Road Baptist Church,"15A Grosvenor Rd, Rathmines, Dublin 6, D06 AH26",D06,AH26,Church,4.5,51,53.319805,-6.271971
81,St Mary's Priory,"Main St, Tallaght Village, Dublin, D24 X585",D24,X585,Catholic church,4.6,164,53.288496,-6.360704
82,Lifegate Bible Baptist Church,"3 Main St, Tallaght, Dublin, D24 DPK2",D24,N9P1,Baptist church,4.9,20,53.288410,-6.356644
83,"Church of the Incarnation, Fettercairn","Kilcarrig Ave, Fettercairn, Dublin 24",D24,E1N8,Church,4.4,30,53.291269,-6.391410
84,Church of Our Lady of Mount Carmel,"Ballycullen Ave, Tymon South, Dublin 24",D24,NaN,Catholic church,4.3,38,53.280371,-6.340554

In [75]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.4)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [76]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [77]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(1657, 19)
(1657, 23)

In [78]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/religious_final.xlsx', index = False)

### Hotel and restaurant

In [79]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Hotel and restaurant')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Enoteca Delle Langhe,"Italian Quarter, Bloom Ln, North City, Dublin,...",D01,C850,Italian restaurant,4.3,507.0,53.346610,-6.265166
1,Fusciardi's Restaurant and Takeaway,"10 Capel St, North City, Dublin, D01 PW32",D01,PW32,Restaurant,4.4,283.0,53.346724,-6.267948
2,Boco,"57 Bolton St, Northside, Dublin 1, D01 CK40",D01,CK40,Pizza restaurant,4.6,780.0,53.351330,-6.270068
3,The Winding Stair,"40 Ormond Quay Lower, North City, Dublin 1, D0...",D01,R9Y5,Irish restaurant,4.4,1443.0,53.346667,-6.263611
4,Bar Italia ristorante,"26 Ormond Quay Lower, North City, Dublin, D01 ...",D01,X942,Italian restaurant,4.4,738.0,53.346395,-6.264980
5,Il Vignardo Restaurant,"21 Store St, Mountjoy, Dublin 1, D01 T9R2",D01,T9R2,Italian restaurant,3.8,77.0,53.350096,-6.252712
6,Chapter One Restaurant,"18-19 Parnell Square N, Rotunda, Dublin 1, D01...",D01,NaN,Fine dining restaurant,4.7,714.0,53.354343,-6.264093
7,Wasabi Bar & Grill,"4 Dorset Street Lower, Rotunda, Dublin, D01 E1X7",D01,NaN,Brazilian restaurant,4.0,410.0,53.357633,-6.263206
8,Veginity,"101 Dorset Street Upper, Inns Quay, Dublin, D0...",D01,A2F4,Vegan restaurant,4.5,218.0,53.355425,-6.265953
9,Le Bon Crubeen,"81-82 Talbot St, North City, Dublin 1, D01 CD34",D01,P6H2,French restaurant,4.2,799.0,53.350512,-6.255137
10,Hot Bubble Café,"55 Capel St, North City, Dublin 1, D01 N9Y5",D01,N9Y5,Restaurant,4.7,188.0,53.349248,-6.268912
11,Arisu Restaurant,"120 Capel St, North City, Dublin, D01 KC63",D01,KC63,Korean restaurant,4.4,919.0,53.348878,-6.269060
12,Flanagan's Restaurant,"61 O'Connell Street Upper, North City, Dublin ...",D01,Y274,Irish restaurant,4.1,1775.0,53.350333,-6.260933
13,Supermac's & Papa John's,"47-49 Talbot St, Mountjoy, Dublin 1, D01 H798",D01,H798,Family restaurant,3.9,492.0,53.351518,-6.250405
14,Star Pizza Dublin 1,"46 Talbot St, Mountjoy, Dublin, D01 HX49",D01,HX49,Pizza restaurant,4.2,973.0,53.351488,-6.250501
15,Chickn Lickn Dublin,"27 Liffey Street Lower, North City, Dublin, D0...",D01,FK58,American restaurant,3.9,263.0,53.347294,-6.263515
16,Nana's Restaurant African cuisine,"482B N Circular Rd, Mountjoy, Dublin 1, D01 P205",D01,P205,African restaurant,4.5,19.0,53.358859,-6.257759
17,Istanbel Buffet House,"90-91 Marlborough St, North City, Dublin, D01 ...",D01,XT82,Buffet restaurant,4.0,634.0,53.349956,-6.258222
18,Kimchi Hophouse,"160-161 Parnell St, Rotunda, Dublin, D01 Y4A7",D01,Y4A7,Korean restaurant,4.4,1715.0,53.353031,-6.260892
19,Laica Catering,"54b Dorset Street Lower, Northside, Dublin, D0...",D01,E278,Restaurant,4.8,38.0,53.360884,-6.259852
20,Wasabi Restaurant Sushi Bar,"77 Dorset Street Upper, Inns Quay, Dublin, D01...",D01,K3H4,Sushi restaurant,3.9,786.0,53.357139,-6.264567
21,Musashi Sushi Parnell Street,"179 Parnell St, Rotunda, Dublin 1, D01 YP60",D01,YP60,Sushi restaurant,4.5,507.0,53.351309,-6.264402
22,Wallace’s Asti,"15 Russell St, Drumcondra, Dublin 1, D01 VW02",D03,K6C4,Pizza restaurant,4.4,426.0,53.358857,-6.254582
23,Benvindo,"33 Foley St, Mountjoy, Dublin 1, D01 V2H7",D01,WA07,Brazilian restaurant,4.1,163.0,53.352445,-6.249780
24,Toto Ristorante Italiano,"8 Talbot St, North City, Dublin 1, D01 HC56",D01,E065,Italian restaurant,4.1,339.0,53.350393,-6.257075
25,Madina Street Food Co,"60 Mary St, North City, Dublin 1, D01 CD40",D01,CD40,Eclectic restaurant,3.8,1103.0,53.348624,-6.268231
26,Bleecker Street Cafe Bar,"68 Dorset Street Upper, Rotunda, Dublin 1, D01...",D01,KT22,New American restaurant,4.6,628.0,53.357180,-6.263914
27,The Italian Connection Restaurant,"95 Talbot St, North City, Dublin 1, D01 HR68",D01,HR68,Italian restaurant,4.2,495.0,53.350267,-6.256581
28,55 Sushi Bar,"143 Parnell St, Rotunda, Dublin 1, D01 AY02",D01,AY02,Sushi restaurant,3.7,412.0,53.353692,-6.259343
29,Il Fornaio IFSC,"Mayor Street Lower, International Financial Se...",D01,P3K7,Italian restaurant,4.3,471.0,53.349403,-6.243004
...,...,...,...,...,...,...,...,...,...
602,Lemongrass Restaurant,"The Arc Bar, Fonthill Rd, Yellow Walls, Lucan,...",D22,NaN,Asian restaurant,4.2,286.0,53.354293,-6.402827
603,Tamara,"18 Belgard Square W, Whitestown, Dublin 24",D24,NaN,Thai restaurant,3.9,177.0,53.286133,-6.376164
604,The India Gate Take Away,"Belgard Rd, Cookstown, Dublin",D24,NaN,Indian restaurant,4.1,78.0,53.295156,-6.370002
605,Chili Club,"1 Anne's Ln, Dublin 2, D02 Y052",D02,Y052,Thai restaurant,4.2,146.0,53.340874,-6.259646
606,Camile Thai Tallaght,"Village Green Centre, 22 Old Bawn Rd, Tallaght...",D24,YT10,Thai restaurant,4.2,258.0,53.286605,-6.361489
607,Bite Cafe,"36 Killakee Walk, Tymon South, Dublin 24, D24 ...",D24,YWR5,Restaurant,4.4,94.0,53.280793,-6.342446
608,The Woodlock Brasserie,"Citywest hotel, Lána Gairtéir, Saggart, Dublin...",D24,KF8A,Restaurant,4.2,103.0,53.285967,-6.446025
609,Kundan Tandoori,"Tallaght Retail Centre, Belgard Rd, Tallaght, ...",D24,NaN,Indian restaurant,4.3,132.0,53.287534,-6.365713
610,Hala Cafe,"Unit 2, Greenhills Business Centre, Tymon Nort...",D24,EK64,Restaurant,5.0,2.0,53.295376,-6.350056
611,Nando's Tallaght,"Belgard Square S Unit 317, The Square Shopping...",D24,NaN,Chicken restaurant,4.3,645.0,53.286777,-6.372454
612,Aussie Outback Tallaght,"7 Belgard Square W, Tallaght, Dublin",D24,NaN,Australian restaurant,4.3,613.0,53.286334,-6.375207
613,Pizza Mór,"Tallaght Retail Centre, High St, Tallaght, Dub...",D24,FF65,Pizza restaurant,4.0,87.0,53.287754,-6.364866
614,Graham O'Sullivan,"The Square, Tallaght, Dublin 24",D17,F785,Family restaurant,3.1,95.0,53.286664,-6.371556
615,Kay's Kitchen,"Unit 308, The Square, Oldbawn, Dublin 24",D17,F785,Restaurant,4.1,255.0,53.286328,-6.371058
616,Cosmo City Dinner,"Irishtown, Dublin 22",D04,P3Y0,Restaurant,4.0,226.0,53.352741,-6.394453
617,The Brass Fox Tallaght,"2 Tuansgate, Tallaght, Dublin",D24,NaN,Restaurant,3.9,163.0,53.288281,-6.369887
618,Tallaght Hospital Dining Room,"Tallaght Hospital, Belgard Square North, Cooks...",D24,NaN,Restaurant,5.0,3.0,53.290033,-6.377478
619,Kay’s Kitchen,"Unit 14, Jervis St, North City, Dublin",D01,NaN,Restaurant,4.2,272.0,53.348077,-6.266132
620,Kay's Kitchen,"Unit 122, Blanchardstown SC, Blanchardstown, D...",D15,NaN,Restaurant,4.1,704.0,53.392982,-6.389385
621,WOWBURGER Wicklow St.,"8 Wicklow St, Dublin 2, D02 AX90",D02,NaN,Restaurant,4.5,1132.0,53.342870,-6.260389
622,Main Street Pizza Tallaght,"2 Main Rd, Tallaght, Dublin, D24 X27P",D24,NaN,Restaurant,4.6,11.0,53.288318,-6.357175
623,Michie Sushi Rathcoole,"Avoca Rathcoole, Fitzmaurice Rd, Dublin",D24,NaN,Sushi restaurant,4.5,38.0,53.284322,-6.456234
624,Pizza Hut Delivery Tallaght,"Greenhills Retail Park, Unit 2a, Greenhills Rd...",D24,NaN,Pizza restaurant,3.7,92.0,53.293980,-6.354982
625,Kay's Kitchen,Donaghmede SC Donaghmede Dublin 13,D13,PX37,Restaurant,4.0,119.0,53.394696,-6.162198
626,The Egg Cafe,"Naas Rd, Saggart, Rathcoole, Co. Dublin",D24,NaN,Health food restaurant,4.3,113.0,53.284298,-6.456233
627,Ly Garden,"Saint Dominic's Shopping Centre, Unit 6, Millb...",D24,NaN,Chinese restaurant,4.1,152.0,53.285477,-6.355262
628,Carpe Diem @ Saggart Village,"The Forge Guesthouse, Mill Rd, Saggart, Co. Du...",D24,NaN,Mediterranean restaurant,4.4,223.0,53.280810,-6.445155
629,Top Tops,"Unit 8, Old Bawn Shopping Centre, 24 R114, Kil...",D24,NaN,Chinese restaurant,4.4,46.0,53.275622,-6.352917
630,China Moon,Dublin,D01,NaN,Chinese restaurant,3.9,62.0,53.274991,-6.344966
631,"The Good Catch, Dublin Port","3 Promenade Rd, North Dock, Dublin",D03,NaN,Seafood restaurant,3.1,10.0,53.354087,-6.212787

In [80]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst>0.5 and dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp>0.5 and wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.8)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [81]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [82]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(8747, 19)
(8747, 23)

In [83]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/hotel_restaurant_final.xlsx', index = False)

### Cafe and pub

In [84]:
df = pd.read_excel('E:\\MCM\Practicum docs\\Datasets\\Final_project\\ds\\amenities_d01_24.xlsx','Cafe and pub')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,The Music Café Dublin,"Grattan House, 1 Wellington Quay, Temple Bar, ...",D02,DY95,Cafe,4.4,755.0,53.345302,-6.267496
1,Lemon Jelly Cafe,"Millennium Walkway, North City, Dublin 1, D01 ...",D01,Y027,Cafe,4.5,2209.0,53.347195,-6.265404
2,Cloud Cafe,"43 N Strand Rd, North Strand, Dublin 3, D03 E977",D03,H5W5,Cafe,4.6,386.0,53.357305,-6.243441
3,RóCo café,"13 Lord Edward St, Dublin, D02 Y278",D08,NaN,Cafe,4.6,135.0,53.343599,-6.269626
4,Scrumptious Café,"207 Philipsburgh Ave, Drumcondra, Dublin, D03 ...",D03,NR20,Cafe,4.6,108.0,53.371089,-6.238795
5,Blas Cafe,"26 King's Inns St, Rotunda, Dublin 1, D01 P2W7",D01,P2W7,Cafe,4.6,302.0,53.351312,-6.267582
6,Ebb & Flow Coffee,"56 Clontarf Rd, Northside, Dublin 3, D03 YN93",D03,YN93,Cafe,4.5,263.0,53.362728,-6.218209
7,Lily's Café,"3A Cavendish Row, Rae Cavendish, Rotunda, Dubl...",D01,NaN,Cafe,4.2,293.0,53.352901,-6.261394
8,Cocobrew,"5 Bedford Row, Temple Bar, Dublin, D02 E393",D02,E393,Cafe,4.6,203.0,53.346026,-6.261925
9,Tillies Cafe,"18 St Gabriel's Rd, Clontarf East, Dublin 3, D...",D03,VN29,Cafe,4.2,174.0,53.365000,-6.183889
10,Cobalt Cafe & Gallery,"16 N Great George's St, Rotunda, Dublin 1, D01...",D01,W2X9,Art cafe,4.2,82.0,53.354301,-6.260770
11,Shoe Lane Coffee (Tara Street),"7 Tara St, Dublin 2, D02 Y662",D02,Y662,Coffee shop,4.7,484.0,53.347165,-6.255280
12,The Pepper Pot,"59 William St S, Dublin 2, D02 CH28",D02,A625,Cafe,4.3,313.0,53.342199,-6.261688
13,Koffee and Kale,"21B Hill St, Rotunda, Dublin 1, D01 HY68",D01,HY68,Cafe,4.4,166.0,53.355775,-6.260709
14,Keoghs Cafe,"1 & 2 Trinity St, Dublin, D02 A440",D02,H684,Cafe,4.3,813.0,53.344033,-6.262204
15,Javaholics Coffee Company,"Merville Ave, Northside, Dublin 3, D03 XK52",D03,XK52,Cafe,4.6,168.0,53.363611,-6.234722
16,KC Peaches Cafe Dame Street,"54 Dame St, Temple Bar, Dublin, D02 X364",D02,X364,Cafe,4.1,649.0,53.344291,-6.264339
17,Food Room,"46 Clontarf Rd, Northside, Dublin 3, D03 AC84",D03,AC84,Cafe,4.0,382.0,53.363057,-6.219265
18,Starbucks,"1 College Green, Temple Bar, Dublin, D02 YT92",D02,YT92,Coffee shop,4.0,1368.0,53.344475,-6.261256
19,Esquires Coffee (Beside Savoy Cinema),"16 A Upper, O'Connell Street Upper, Dublin, D0...",D01,NY16,Coffee shop,4.3,315.0,53.351135,-6.260447
20,Insomnia Coffee Company,"181 Howth Rd, Clontarf East, Killester, Co. Du...",D05,NaN,Coffee shop,4.2,246.0,53.370774,-6.205826
21,The Tram Café,"Wolf Tone Square, Jervis St, North City, Dubli...",D01,W8C9,Cafe,4.5,602.0,53.348066,-6.266790
22,Network,"39 Aungier St, Dublin 2, D02 HP86",D02,HP86,Coffee shop,4.7,365.0,53.338643,-6.265836
23,"Quigleys Cafe, Bakery & Deli","Level 2, Belgard Square E, Tallaght, Dublin, D...",D24,X62W,Cafe,NaN,NaN,53.288392,-6.369190
24,Lunch!,"4 Lombard St E, Dublin, D02 VY96",D02,VY96,Cafe,4.5,100.0,53.344341,-6.248970
25,Crosscare Community Cafe,"2 Dunne St, Northside, Dublin, D01 A9X5",D01,A9X5,Cafe,4.2,19.0,53.356135,-6.248235
26,Kennedy's Food Store,"5 Fairview Strand, Northside, Dublin 3, D03 W5H0",D03,W5H0,Cafe,4.4,376.0,53.362863,-6.237181
27,Starbucks Stephens Green,"Stephen Court, GF1, St Stephen's Green, Dublin...",D02,N960,Coffee shop,4.0,1004.0,53.339322,-6.257511
28,TJ's Coffee Bar,"79 Parnell St, Rotunda, Dublin, D01 W3Y7",D01,W3Y7,Cafe,4.7,61.0,53.352749,-6.260734
29,Kennedy's Food Store,"196 Clontarf Rd, Clontarf East, Dublin 3, D03 ...",D03,X2H4,Cafe,4.4,282.0,53.359190,-6.195906
...,...,...,...,...,...,...,...,...,...
586,Java Republic,"510 NW Business Park, Ballycoolen, Dublin, D15...",D15,NaN,Cafe,4.4,267.0,53.412766,-6.346519
587,Kavanaghs Pub Rathfarnham,"39 Main St, Rathfarnham, Dublin, D14 P6CO",D14,NaN,Pub,4.3,30.0,53.298428,-6.285526
588,The 51 Bar,"51 Haddington Rd, Dublin 4, D04 FD83",D04,FD83,Sports bar,4.3,956.0,53.334660,-6.242472
589,The Wine & Tapas Bar At The Old Orchard,"74 Butterfield Ave, Rathfarnham, Dublin, D14 RF96",D14,RF96,Tapas bar,4.5,68.0,53.294688,-6.299247
590,The Carpenter,"Carpenterstown Road, Northside, Dublin, D15 YD63",D15,YD63,Pub,4.3,920.0,53.371946,-6.389071
591,The Black Wolf-Beer & Food Co,"Main St, Blanchardstown Village, Dublin, D15 V20W",D15,V20W,Gastropub,4.2,781.0,53.385909,-6.374389
592,Dundrum House,"57 Main St, Dundrum, Dublin 14",D14,X0T8,Pub,4.4,704.0,53.289390,-6.243334
593,Eagle House Dundrum,"Main St, Dundrum, Dublin",D14,NaN,Pub,3.8,120.0,53.289053,-6.243177
594,Myos,"Castleknock Rd, Castleknock, Dublin 15",D15,K3HN,Irish pub,3.7,339.0,53.372857,-6.362510
595,The Great Wood,"Westend Shopping Park, Blanchardstown, Dublin",D15,NaN,Pub,4.0,2574.0,53.389184,-6.388901
596,Clonsilla Inn,"Weavers Row, Clonsilla, Dublin",D15,C678,Pub,4.3,876.0,53.382392,-6.407795
597,The Strawberry Hall,"Lower Rd, Astagob, Dublin 20, D20 RH59",D20,RH59,Pub,4.6,421.0,53.362341,-6.385715
598,Salmon's Public House,"Mountview Rd, Northside, Dublin",D15,NaN,Pub,4.0,220.0,53.390708,-6.406337
599,The Brock Inn,"North Rd, Broghan, Broughan, Co. Dublin",D11,NaN,Pub,4.5,1205.0,53.433135,-6.332599
600,Pifko Bar,"41 Usher's Quay, Dublin",D08,K1E8,Pub,4.4,918.0,53.346058,-6.280333
601,Buglers Ballyboden House,"Ballyboden Rd, Rathfarnham, Dublin",D14,NaN,Pub,4.2,413.0,53.284101,-6.295429
602,The Knocklyon Inn,"Knocklyon Rd, Knocklyon, Dublin",D16,NaN,Pub,4.1,48.0,53.286993,-6.327999
603,Scholars Pub,"Oldcourt Shopping Centre, Parklands Rd, Dublin 24",D24,NaN,Pub,4.3,668.0,53.274954,-6.344956
604,The Coach House Pub,"16 Ballinteer Ave, Ballinteer, Dublin",D16,HT65,Pub,4.3,470.0,53.276447,-6.249150
605,The Priorswood Inn,"Proirswood Shopping Centre, Clonshaugh Ave, Pr...",D17,XV48,Pub,4.2,43.0,53.403359,-6.207208
606,The Silver Granite,"Kennelsfort Rd Upper, Johnstown, Dublin 20, D2...",D20,KH67,Pub,3.4,394.0,53.350061,-6.377434
607,The Deadman’s Inn,"Lucan Rd Old, Curtis Stream, Palmerstown, Co. ...",D20,NaN,Irish pub,4.2,449.0,53.356036,-6.397637
608,Quinlan's - The Black Lion,"Orchard Rd, Clondalkin, Dublin 22",D22,NaN,Pub,4.4,651.0,53.321343,-6.393529
609,The Speaker Connolly,"Firhouse Rd, Tymon South, Dublin 24",D24,NaN,Gastropub,4.2,250.0,53.281920,-6.341048
610,The Swallows,"Deansrath Shopping Centre, St Cuthberts Rd, De...",D22,R5Y0,Pub,3.7,64.0,53.323596,-6.424749
611,McGettigans Cookhouse KingsWood,"Kingswood, Dublin",D24,NaN,Gastropub,4.3,535.0,53.300985,-6.418979
612,Grumpy McClaffertys,"The Plaza Complex, Belgard Square S, Tallaght,...",D24,NaN,Pub,4.1,49.0,53.285586,-6.367847
613,The Baurnafea House,"Main St, Rathcoole, Co. Dublin",D24,NaN,Pub,4.0,196.0,53.281205,-6.469071
614,The Horseshoe Bar,"27 St Stephen's Green, Dublin 2",D02,H529,Pub,4.6,17.0,53.338997,-6.255904
615,O'Dwyer's Bar & Grill,"Strand Rd, Burrow, Portmarnock, Co. Dublin",D13,NaN,Pub,4.3,570.0,53.420549,-6.137896

In [85]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst>0.5 and dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp>0.5 and wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.8)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [86]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [87]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(8904, 19)
(8904, 23)

In [88]:
Final_distance_data.to_excel(r'E:/MCM/Practicum docs/Datasets/Final_project/sale/cafe_pub_final.xlsx', index = False)

### Retail stores

In [5]:
df1 = pd.read_csv('daftsale_31stmay.csv')

In [6]:
df1

,Location,Area,Area code,Price(in Euros),House_type,Beds,Bathroom,Area_code,latitude,longitude,floor_area,Entered,Views
0,1 Kirkpatrick House|| Spencer House|| IFSC|| D...,Dublin 1,D01,285000,Apartment for sale,1,1,D00,53.350082,-6.238685,42.10,31.05.2020,2108.0
1,109 Parnell Street|| Dublin 1,Dublin 1,D01,220000,Apartment for sale,1,1,D01,53.353609,-6.256895,35.00,10.05.2020,2534.0
2,11 Mountjoy Parade|| Dublin 1,Dublin 1,D01,349950,Terraced House,2,1,D01,53.358588,-6.252270,91.00,27.05.2020,3063.0
3,12 Rutland Cottages|| Dublin 1,Dublin 1,D01,235000,Terraced House,2,1,D01,53.355073,-6.251607,64.00,29.05.2020,7462.0
4,127 Scarriff House|| Custom House Square|| Dub...,Dublin 1,D01,350000,Apartment for sale,2,1,D01,53.349712,-6.241361,59.00,28.05.2020,1883.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2416,105 Alderwood Avenue.|| D24C990|| Tallaght|| D...,Dublin 24,D24,229000,Terraced House,3,1,D24,53.287030,-6.382832,85.00,31.05.2020,1284.0
2417,116 Exchange Hall|| Tallaght|| Dublin 24,Dublin 24,D24,149000,Apartment for sale,1,1,D24,53.290072,-6.374013,76.00,31.05.2020,8931.0
2418,33 Raheen Road|| Tallaght|| Tallaght|| Dublin 24,Dublin 24,D24,255000,Semi-Detached House,3,2,D24,53.285035,-6.388270,100.27,30.04.2020,2843.0
2419,9 De Selby Drive|| Tallaght|| Dublin 24,Dublin 24,D24,250000,End of Terrace House,3,2,D24,53.277114,-6.409177,86.96,31.05.2020,3200.0
2420,Apartment 66|| Block C|| Westend Gate|| Tallag...,Dublin 24,D24,150000,Apartment for sale,1,1,D24,53.285034,-6.376462,45.00,29.05.2020,2771.0

In [6]:
df = pd.read_excel('amenities_d01_24.xlsx','Retail Store')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,ALDI,"St Margaret's Rd, Northside, Finglas, Co. Dubl...",D11,ARW5,Discount supermarket,4.2,1099.0,53.398635,-6.304434
1,ALDI,"Santry Ave, Santry, Dublin, D09 H218",D09,H218,Discount supermarket,4.3,1363.0,53.399572,-6.254207
2,ALDI,"Old Lucan Road, Palmerstown Lower, Palmerstown...",D20,DT92,Discount supermarket,4.4,261.0,53.357841,-6.377260
3,ALDI,"38-41 Parnell St, Rotunda, Dublin, D01 F295",D01,NaN,Store,4.3,1251.0,53.349747,-6.268753
4,ALDI,"Main Street, Buzzardstown, Dublin, D15 FP99",D15,NaN,Discount supermarket,4.3,1010.0,53.401460,-6.396199
...,...,...,...,...,...,...,...,...,...
459,Tesco Superstore,"Link Rd, Holywell, Swords, Co. Dublin",D03,NaN,Supermarket,4.2,720.0,53.445380,-6.214465
460,Tesco Superstore,"Rathfarnham Shopping Centre, Butterfield Ave, ...",D14,NaN,Supermarket,3.8,240.0,53.297725,-6.296705
461,Tesco Superstore,"Dundrum Town Centre, Dundrum, Co. Dublin",D16,NaN,Supermarket,3.7,117.0,53.286441,-6.241863
462,Tesco Superstore,"Nutgrove Shopping Centre, Rathfarnham, Co. Dublin",D14,NaN,Supermarket,3.6,83.0,53.289511,-6.267480
463,Tyre Centre,"Taylors Lane R133, Ballyboden, Dublin",D16,NaN,Tire shop,4.7,17.0,53.281614,-6.289006

In [7]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.75)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [8]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [9]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(9318, 19)
(9318, 23)

In [10]:
Final_distance_data.to_excel(r'C:/Users/Akhilesh/Desktop/Retail_score_sale_final.xlsx', index = False)

### Gym

In [7]:
df = pd.read_excel('amenities_d01_24.xlsx','Gym, swimming and yoga')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,Aura De Paul Swimming Pool,"Saint Vincents Centre, Navan Rd, Ashtown, Dubl...",D07,DH42,Swimming pool,4.5,194.0,53.368882,-6.323035
1,Marian Swimming Pool,"Lansdowne Rd, Ballsbridge, Dublin 4",D04,HC65,Swimming pool,4.5,117.0,53.332566,-6.226057
2,Mespil Swimming Pool,"Mespil House Flats, 4 Sussex Rd, Dublin, D04 H9T0",D04,H9T0,Public swimming pool,3.7,97.0,53.331516,-6.250590
3,Sean McDermott Street Pool,"Sean Macdermott Street Lower, Mountjoy, Dublin",D01,NaN,Swimming pool,4.2,80.0,53.353859,-6.252517
4,Crumlin Swimming Pool,"80A Windmill Rd, Crumlin, Dublin 12, D12 Y5Y2",D12,Y5Y2,Swimming pool,4.1,44.0,53.323879,-6.312960
...,...,...,...,...,...,...,...,...,...
375,DLRCoCo All Weather Pitch,"Enniskerry Rd, Jamestown, Dublin",D18,NaN,Gym,4.2,28.0,53.247560,-6.201997
376,Finglas Area Office & Sports Centre,"11 Mellowes Rd, Finglas West, Dublin, D11 E6K2",D11,E6K2,Gym,4.3,252.0,53.389625,-6.308765
377,Iveagh Fitness Club,"Bride Road, Christchurch Pl, Wood Quay, Dublin 8",D08,NaN,Gym,4.2,203.0,53.341578,-6.270880
378,St James Gate Health and Fitness Club,"Watling St, The Liberties, Dublin 8",D08,X7Y2,Gym,4.2,37.0,53.344112,-6.285172
379,Positive Fitness,"6 Shamrock Villas, Harold's Cross, Terenure, D...",D6W,DH67,Gym,5.0,2.0,53.322763,-6.280093

In [8]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<1.0):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<1.0):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(0.15)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [9]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [10]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(6112, 19)
(6112, 23)

In [11]:
Final_distance_data.to_excel(r'C:/Users/Akhilesh/Desktop/Gym_score_sale_final.xlsx', index = False)

### Bus stop

In [9]:
df = pd.read_excel("amenities_d01_24.xlsx", 'Bus stop')
df.drop(columns=['Price level','Opening Hours','Search Keyword','Search Location','Claimed','Map Link','Date Add'],inplace=True)
df

,Company Name,Address,Zip/Postal,Code,Type,Rating,Total Reviews,Latitude,Longitude
0,"Ashtown, Ashtown Roundabout","Ashtown, Dublin",D15,NaN,Bus stop,3.7,3.0,53.371580,-6.330482
1,"Ashtown, Navan Road","Ashtown, Dublin",D15,NaN,Bus stop,NaN,NaN,53.370658,-6.327702
2,"Cabra, Navan Road (Nephin Road)","Ashtown, Dublin",D15,NaN,Bus station,NaN,NaN,53.365137,-6.309269
3,"Castleknock Road, Stop 1667","Ashtown, Dublin",D15,NaN,Bus stop,NaN,NaN,53.371010,-6.334256
4,"Rathbourne Avenue, Stop 5145","Ashtown, Dublin",D15,NaN,Bus stop,2.0,1.0,53.377197,-6.326754
...,...,...,...,...,...,...,...,...,...
2378,"Cloghran, Cruiserath Road","Ballycoolen, Dublin",D11,NaN,Bus stop,NaN,NaN,53.409915,-6.368446
2379,"Cloghran, Business Park (Ballycoolin Road)","Ballycoolen, Dublin",D11,NaN,Bus stop,NaN,NaN,53.405877,-6.356477
2380,Brock Inn,"Broghan, Co. Dublin",D11,NaN,Bus stop,5.0,1.0,53.433660,-6.333221
2381,"Brittas Grange, Stop 4071","Glenaraneen, Co. Dublin",D24,NaN,Bus stop,NaN,NaN,53.241367,-6.455802
2382,Balrothery (Opp Balrothery Inn),"Balrothery, Co. Dublin",D24,NaN,Bus stop,1.0,1.0,53.587968,-6.189527

In [13]:
for i in df:
    aminities_tmp=list(df.Latitude)
    aminities1_tmp=list(df.Longitude)
for i in df1:
    property_tmp=list(df1.latitude)
    property1_tmp=list(df1.longitude)
i=0
j=0
k=0
l=0
m=0
wakable_distance=[]
property_latitude=[]
property_longitude=[]
aminities_latitude=[]
aminities_longitude=[]
wakable_radius=[]
property_coord=[]
aminities_coord=[]
score=[]
n=len(aminities_tmp)
n1=len(property_tmp)
Final_distance= pd.DataFrame(columns =['wakable_distance','property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])

while(i<n1):
#     wakable_radius.clear()
#     property_coord.clear()
#     aminities_coord.clear()
    j=0
    while(j<n):
        dst=distance((property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j]))
        if(dst<0.6):
            wakable_radius.append(dst)
            property_coord.append((property_tmp[i],property1_tmp[i]))
            aminities_coord.append((aminities_tmp[j],aminities1_tmp[j]))
#             radius_retail.append((dst,(property_tmp[i],property1_tmp[i]),(aminities_tmp[j],aminities1_tmp[j])))
        j=j+1
    distance_df= pd.DataFrame(list(zip(wakable_radius,property_coord,aminities_coord)),
                              columns =['radius', 'property_coord','aminities_coord'])
#     print(len(distance_df))
#     print(distance_df)
    wakable_radius.clear()
    property_coord.clear()
    aminities_coord.clear()
    wakable_distance.clear()
    property_latitude.clear()
    property_longitude.clear()
    aminities_latitude.clear()
    aminities_longitude.clear()
    score.clear()
    k=0
    while(k<len(distance_df)):
        wakable_dist_tmp=gmaps.distance_matrix(distance_df.property_coord[k],distance_df.aminities_coord[k],mode='walking',transit_routing_preference='less_walking',units='metric')
        wakable_distance_tmp=wakable_dist_tmp['rows'][0]['elements'][0]['distance']['text']
        r=re.search(r" m",wakable_distance_tmp,re.I|re.S)
        if(r):
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])/1000
        else:
            dst_tmp=wakable_distance_tmp.split()
            wakable_distance_tmp=float(dst_tmp[0])
        if(wakable_distance_tmp<0.6):
            wakable_distance.append(wakable_distance_tmp)
            property_latitude.append(distance_df.property_coord[k][0])
            property_longitude.append(distance_df.property_coord[k][1])
            aminities_latitude.append(distance_df.aminities_coord[k][0])
            aminities_longitude.append(distance_df.aminities_coord[k][1])     
        k=k+1
#     print(wakable_distance)
# #     print(distance_df.property_coord[0][0])
#     print(property_latitude)
#     print(property_longitude)
#     print(aminities_latitude)
#     print(aminities_longitude)
    total_aminities= len(wakable_distance)
    total_points=len(wakable_distance)*5
#     print(total_aminities)
#     print(total_points)
    m=0
    while(m<len(wakable_distance)):
        score.append(1)
        m=m+1
    Final_distance_tmp=pd.DataFrame(list(zip(wakable_distance,property_latitude,property_longitude,aminities_latitude,aminities_longitude,score)),
                          columns =['wakable_distance', 'property_latitude','property_longitude',
                                       'aminities_latitude','aminities_longitude','score'])
    Final_distance=Final_distance.append(Final_distance_tmp,ignore_index = True)
#     print(Final_distance)
#     while(l<len(wakable_distance)):
#         Final_distance.append(list(zip(wakable_distance[l],property_latitude[l],property_longitude[l],aminities_latitude[l],aminities_longitude[l])))
#         l=l+1
    distance_df.drop(distance_df.index, inplace=True)
    i=i+1

In [14]:
Final_distance_data_tmp = pd.merge(df1,Final_distance,left_on='latitude',right_on='property_latitude') 
Final_distance_data=pd.merge(Final_distance_data_tmp,df,left_on='aminities_latitude',right_on='Latitude')
Final_distance_data.drop(columns=['longitude','latitude','Total Reviews',
                                  'Latitude','Longitude'],inplace=True)

In [15]:
print(Final_distance_data_tmp.shape)
print(Final_distance_data.shape)

(12304, 19)
(12304, 23)

In [16]:
Final_distance_data.to_excel(r'C:/Users/Akhilesh/Desktop/Bus_stop_score_sale_final.xlsx', index = False)