In [1]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv('E:\\MCM\\Practicum docs\\Final_documents\\datasets\\Crime_area_code.csv')

In [68]:
df

,id,Area_code,Station,Divisions,"Attempts or threats to murder, assaults, harassments and related offences 2007","Attempts or threats to murder, assaults, harassments and related offences 2008","Attempts or threats to murder, assaults, harassments and related offences 2009","Attempts or threats to murder, assaults, harassments and related offences 2010","Attempts or threats to murder, assaults, harassments and related offences 2011","Attempts or threats to murder, assaults, harassments and related offences 2012",...,"Offences against government, justice procedures and organisation of crime 2009","Offences against government, justice procedures and organisation of crime 2010","Offences against government, justice procedures and organisation of crime 2011","Offences against government, justice procedures and organisation of crime 2012","Offences against government, justice procedures and organisation of crime 2013","Offences against government, justice procedures and organisation of crime 2014","Offences against government, justice procedures and organisation of crime 2015","Offences against government, justice procedures and organisation of crime 2016","Offences against government, justice procedures and organisation of crime 2017","Offences against government, justice procedures and organisation of crime 2018"
0,2033,D01,Fitzgibbon Street,D.M.R. North Central Division,130,161,128,117,147,130,...,18,17,17,6,8,12,7,4,67,63
1,2032,D01,Store Street,D.M.R. North Central Division,279,284,270,313,338,289,...,110,57,54,33,39,25,32,4,226,491
2,201,D02,Pearse Street,D.M.R. South Central Division,525,538,446,521,551,451,...,273,110,139,132,88,107,78,14,151,193
3,2027,D03,Clontarf,D.M.R. Northern Division,93,113,131,86,53,74,...,16,4,8,10,17,14,10,1,36,48
4,205,D04,Donnybrook,D.M.R. South Central Division,67,77,91,71,45,41,...,10,14,3,7,5,4,8,1,29,26
5,206,D04,Irishtown,D.M.R. South Central Division,42,41,33,40,43,41,...,10,3,2,10,20,15,7,0,34,22
6,2023,D05,Coolock,D.M.R. Northern Division,104,141,122,141,165,105,...,66,59,40,20,30,49,36,8,196,241
7,2026,D05,Raheny,D.M.R. Northern Division,58,70,76,58,46,37,...,19,10,6,12,10,15,24,5,20,18
8,2017,D06,Rathmines,D.M.R. Southern Division,97,92,81,85,96,65,...,7,8,7,8,6,5,6,0,57,61
9,2018,D06,Terenure,D.M.R. Southern Division,54,46,63,46,49,33,...,9,5,9,5,8,4,6,2,36,54
10,2035,D07,Bridewell Dublin,D.M.R. North Central Division,142,163,137,117,117,106,...,3939,4000,3586,3553,3044,3138,3580,938,1906,2192
11,2028,D07,Cabra,D.M.R. Western Division,53,62,83,189,90,64,...,24,23,27,10,7,14,15,1,26,22
12,2034,D07,Mountjoy,D.M.R. North Central Division,148,93,106,137,184,173,...,158,116,65,61,50,55,25,13,49,80
13,2036,D08,Kevin Street,D.M.R. South Central Division,172,194,171,188,196,175,...,30,34,25,9,19,17,25,4,109,190
14,204,D08,Kilmainham,D.M.R. South Central Division,98,178,193,193,194,151,...,58,35,25,18,14,16,23,11,377,472
15,2021,D09,Ballymun,D.M.R. Northern Division,177,211,224,186,166,140,...,24,23,20,9,23,32,34,11,58,42
16,2019,D09,Santry,D.M.R. Northern Division,130,152,137,159,127,109,...,27,14,18,15,20,14,16,5,36,41
17,2030,D11,Finglas,D.M.R. Western Division,126,163,141,193,244,98,...,56,39,24,36,26,41,55,15,86,51
18,207,D12,Crumlin,D.M.R. Southern Division,76,61,70,68,79,65,...,13,5,8,17,8,19,11,3,33,70
19,208,D12,Sundrive Road,D.M.R. Southern Division,111,102,102,108,86,82,...,23,10,9,24,14,18,13,1,48,61
20,2029,D13,Howth,D.M.R. Northern Division,29,32,47,36,35,31,...,2,6,6,4,13,12,5,1,18,17
21,2045,D14,Dundrum,D.M.R. Eastern Division,78,99,94,86,113,100,...,35,25,18,17,24,13,18,7,34,38
22,2031,D15,Blanchardstown,D.M.R. Western Division,223,210,223,265,336,207,...,626,720,517,491,472,439,473,91,137,106
23,2015,D16,Rathfarnham,D.M.R. Southern Division,148,141,132,112,98,78,...,24,23,22,26,18,25,21,1,58,73
24,2039,D18,Cabinteely,D.M.R. Eastern Division,46,50,51,58,49,47,...,12,8,11,10,11,13,15,3,19,13
25,2042,D18,Shankill,D.M.R. Eastern Division,103,97,88,89,65,76,...,14,15,18,16,9,14,16,3,24,23
26,209,D10,Ballyfermot,D.M.R. Western Division,105,72,75,78,82,120,...,69,84,32,27,24,23,21,6,78,89
27,2012,D22,Clondalkin,D.M.R. Western Division,131,116,116,121,116,131,...,42,39,27,32,35,36,55,10,165,145
28,2013,D22,Ronanstown,D.M.R. Western Division,143,123,113,139,174,170,...,207,173,111,100,87,88,112,19,137,149
29,2014,D24,Rathcoole,D.M.R. Western Division,19,7,24,28,22,28,...,3,3,0,4,4,7,4,2,7,5
30,2016,D24,Tallaght,D.M.R. Southern Division,371,354,387,351,282,278,...,337,254,245,220,256,299,355,83,353,322

In [69]:
print(df.columns)

Index(['id', 'Area_code', 'Station', 'Divisions',
       'Attempts or threats to murder, assaults, harassments and related offences 2007',
       'Attempts or threats to murder, assaults, harassments and related offences 2008',
       'Attempts or threats to murder, assaults, harassments and related offences 2009',
       'Attempts or threats to murder, assaults, harassments and related offences 2010',
       'Attempts or threats to murder, assaults, harassments and related offences 2011',
       'Attempts or threats to murder, assaults, harassments and related offences 2012',
       ...
       'Offences against government, justice procedures and organisation of crime 2009',
       'Offences against government, justice procedures and organisation of crime 2010',
       'Offences against government, justice procedures and organisation of crime 2011',
       'Offences against government, justice procedures and organisation of crime 2012',
       'Offences against government, justice procedures and organisation of crime 2013',
       'Offences against government, justice procedures and organisation of crime 2014',
       'Offences against government, justice procedures and organisation of crime 2015',
       'Offences against government, justice procedures and organisation of crime 2016',
       'Offences against government, justice procedures and organisation of crime 2017',
       'Offences against government, justice procedures and organisation of crime 2018'],
      dtype='object', length=149)

In [71]:
df.drop(columns=['id'],inplace = True)

In [132]:
df.head()

,Area_code,Station,Divisions,"Attempts or threats to murder, assaults, harassments and related offences 2007","Attempts or threats to murder, assaults, harassments and related offences 2008","Attempts or threats to murder, assaults, harassments and related offences 2009","Attempts or threats to murder, assaults, harassments and related offences 2010","Attempts or threats to murder, assaults, harassments and related offences 2011","Attempts or threats to murder, assaults, harassments and related offences 2012","Attempts or threats to murder, assaults, harassments and related offences 2013",...,"Offences against government, justice procedures and organisation of crime 2009","Offences against government, justice procedures and organisation of crime 2010","Offences against government, justice procedures and organisation of crime 2011","Offences against government, justice procedures and organisation of crime 2012","Offences against government, justice procedures and organisation of crime 2013","Offences against government, justice procedures and organisation of crime 2014","Offences against government, justice procedures and organisation of crime 2015","Offences against government, justice procedures and organisation of crime 2016","Offences against government, justice procedures and organisation of crime 2017","Offences against government, justice procedures and organisation of crime 2018"
0,D01,Fitzgibbon Street,D.M.R. North Central Division,130,161,128,117,147,130,109,...,18,17,17,6,8,12,7,4,67,63
1,D01,Store Street,D.M.R. North Central Division,279,284,270,313,338,289,304,...,110,57,54,33,39,25,32,4,226,491
2,D02,Pearse Street,D.M.R. South Central Division,525,538,446,521,551,451,481,...,273,110,139,132,88,107,78,14,151,193
3,D03,Clontarf,D.M.R. Northern Division,93,113,131,86,53,74,60,...,16,4,8,10,17,14,10,1,36,48
4,D04,Donnybrook,D.M.R. South Central Division,67,77,91,71,45,41,41,...,10,14,3,7,5,4,8,1,29,26

In [133]:
df.sum(axis=1, skipna=True)

0      27062
1     102171
2     112308
3      21011
4      19659
5      15593
6      35125
7      12039
8      21675
9      15336
10     67347
11     16717
12     28542
13     37812
14     31377
15     24071
16     27194
17     35653
18     17934
19     19417
20      9754
21     33811
22     66124
23     29246
24     12941
25     13741
26     25599
27     31616
28     29675
29      7214
30     69330
dtype: int64

In [134]:
df1 = df.iloc[:,0:15]

In [135]:
df1.head()

,Area_code,Station,Divisions,"Attempts or threats to murder, assaults, harassments and related offences 2007","Attempts or threats to murder, assaults, harassments and related offences 2008","Attempts or threats to murder, assaults, harassments and related offences 2009","Attempts or threats to murder, assaults, harassments and related offences 2010","Attempts or threats to murder, assaults, harassments and related offences 2011","Attempts or threats to murder, assaults, harassments and related offences 2012","Attempts or threats to murder, assaults, harassments and related offences 2013","Attempts or threats to murder, assaults, harassments and related offences 2014","Attempts or threats to murder, assaults, harassments and related offences 2015","Attempts or threats to murder, assaults, harassments and related offences 2016","Attempts or threats to murder, assaults, harassments and related offences 2017","Attempts or threats to murder, assaults, harassments and related offences 2018"
0,D01,Fitzgibbon Street,D.M.R. North Central Division,130,161,128,117,147,130,109,136,158,29,85,134
1,D01,Store Street,D.M.R. North Central Division,279,284,270,313,338,289,304,305,435,111,207,268
2,D02,Pearse Street,D.M.R. South Central Division,525,538,446,521,551,451,481,520,635,158,391,484
3,D03,Clontarf,D.M.R. Northern Division,93,113,131,86,53,74,60,51,69,15,67,65
4,D04,Donnybrook,D.M.R. South Central Division,67,77,91,71,45,41,41,45,57,13,42,62

In [136]:
df1['Total Attempts or threats to murder, assaults, harassments and related offences'] = df1.sum(axis=1)
df1

,Area_code,Station,Divisions,"Attempts or threats to murder, assaults, harassments and related offences 2007","Attempts or threats to murder, assaults, harassments and related offences 2008","Attempts or threats to murder, assaults, harassments and related offences 2009","Attempts or threats to murder, assaults, harassments and related offences 2010","Attempts or threats to murder, assaults, harassments and related offences 2011","Attempts or threats to murder, assaults, harassments and related offences 2012","Attempts or threats to murder, assaults, harassments and related offences 2013","Attempts or threats to murder, assaults, harassments and related offences 2014","Attempts or threats to murder, assaults, harassments and related offences 2015","Attempts or threats to murder, assaults, harassments and related offences 2016","Attempts or threats to murder, assaults, harassments and related offences 2017","Attempts or threats to murder, assaults, harassments and related offences 2018","Total Attempts or threats to murder, assaults, harassments and related offences"
0,D01,Fitzgibbon Street,D.M.R. North Central Division,130,161,128,117,147,130,109,136,158,29,85,134,1464
1,D01,Store Street,D.M.R. North Central Division,279,284,270,313,338,289,304,305,435,111,207,268,3403
2,D02,Pearse Street,D.M.R. South Central Division,525,538,446,521,551,451,481,520,635,158,391,484,5701
3,D03,Clontarf,D.M.R. Northern Division,93,113,131,86,53,74,60,51,69,15,67,65,877
4,D04,Donnybrook,D.M.R. South Central Division,67,77,91,71,45,41,41,45,57,13,42,62,652
5,D04,Irishtown,D.M.R. South Central Division,42,41,33,40,43,41,32,35,40,4,24,28,403
6,D05,Coolock,D.M.R. Northern Division,104,141,122,141,165,105,136,131,189,38,88,122,1482
7,D05,Raheny,D.M.R. Northern Division,58,70,76,58,46,37,29,42,44,7,40,55,562
8,D06,Rathmines,D.M.R. Southern Division,97,92,81,85,96,65,81,87,73,28,60,95,940
9,D06,Terenure,D.M.R. Southern Division,54,46,63,46,49,33,54,37,54,10,56,55,557
10,D07,Bridewell Dublin,D.M.R. North Central Division,142,163,137,117,117,106,119,127,132,33,104,102,1399
11,D07,Cabra,D.M.R. Western Division,53,62,83,189,90,64,55,65,38,8,46,52,805
12,D07,Mountjoy,D.M.R. North Central Division,148,93,106,137,184,173,181,229,212,51,89,127,1730
13,D08,Kevin Street,D.M.R. South Central Division,172,194,171,188,196,175,160,205,230,61,99,126,1977
14,D08,Kilmainham,D.M.R. South Central Division,98,178,193,193,194,151,123,128,176,41,104,110,1689
15,D09,Ballymun,D.M.R. Northern Division,177,211,224,186,166,140,135,127,159,29,153,172,1879
16,D09,Santry,D.M.R. Northern Division,130,152,137,159,127,109,110,97,125,39,82,104,1371
17,D11,Finglas,D.M.R. Western Division,126,163,141,193,244,98,103,110,110,35,98,100,1521
18,D12,Crumlin,D.M.R. Southern Division,76,61,70,68,79,65,66,90,89,24,55,53,796
19,D12,Sundrive Road,D.M.R. Southern Division,111,102,102,108,86,82,62,97,100,21,82,117,1070
20,D13,Howth,D.M.R. Northern Division,29,32,47,36,35,31,24,22,25,12,29,37,359
21,D14,Dundrum,D.M.R. Eastern Division,78,99,94,86,113,100,104,82,134,45,63,85,1083
22,D15,Blanchardstown,D.M.R. Western Division,223,210,223,265,336,207,188,226,204,68,154,217,2521
23,D16,Rathfarnham,D.M.R. Southern Division,148,141,132,112,98,78,84,83,113,21,82,118,1210
24,D18,Cabinteely,D.M.R. Eastern Division,46,50,51,58,49,47,60,85,74,10,50,44,624
25,D18,Shankill,D.M.R. Eastern Division,103,97,88,89,65,76,54,96,83,19,66,52,888
26,D10,Ballyfermot,D.M.R. Western Division,105,72,75,78,82,120,100,91,69,26,106,142,1066
27,D22,Clondalkin,D.M.R. Western Division,131,116,116,121,116,131,112,120,137,29,88,105,1322
28,D22,Ronanstown,D.M.R. Western Division,143,123,113,139,174,170,106,120,169,34,126,138,1555
29,D24,Rathcoole,D.M.R. Western Division,19,7,24,28,22,28,23,47,41,14,19,17,289
30,D24,Tallaght,D.M.R. Southern Division,371,354,387,351,282,278,279,322,347,72,383,370,3796

In [124]:
data_merged = pd.DataFrame(columns = ['Attempts or threats to murder, assaults, harassments and related offences',
                                      'Dangerous or negligent acts',
                                     'Kidnapping and related offences',
                                     'Robbery, extortion and hijacking offences',
                                     'Burglary and related offences',
                                     'Theft and related offences',
                                     'Fraud, deception and related offences',
                                     'Controlled drug offences 2008','Weapons and Explosives Offences',
                                     'Damage to property and to the environment 2008','Public order and other social code offences',
                                     'Offences against government, justice procedures and organisation of crime'])

In [86]:
##col_list1 = list(df1)
##col_list1
##df_merge['Total Attempts or threats to murder, assaults, harassments and related offences'] = df1[col_list1].sum(axis=1)
##df_merged = df1[col_list1].sum(axis=1)

In [104]:
df2 = df.iloc[:,15:27]

In [105]:
df2.head()

,Dangerous or negligent acts 2007,Dangerous or negligent acts 2008,Dangerous or negligent acts 2009,Dangerous or negligent acts 2010,Dangerous or negligent acts 2011,Dangerous or negligent acts 2012,Dangerous or negligent acts 2013,Dangerous or negligent acts 2014,Dangerous or negligent acts 2015,Dangerous or negligent acts 2016,Dangerous or negligent acts 2017,Dangerous or negligent acts 2018
0,93,119,105,72,54,41,36,28,48,17,56,91
1,199,227,154,103,76,76,69,64,47,20,159,161
2,246,152,147,110,92,87,49,52,57,11,213,225
3,95,97,120,66,46,60,43,35,36,10,78,90
4,133,126,81,49,57,56,38,29,27,10,103,120

In [137]:
df2['Total Dangerous or negligent acts'] = df2.sum(axis=1)
df2

,Dangerous or negligent acts 2007,Dangerous or negligent acts 2008,Dangerous or negligent acts 2009,Dangerous or negligent acts 2010,Dangerous or negligent acts 2011,Dangerous or negligent acts 2012,Dangerous or negligent acts 2013,Dangerous or negligent acts 2014,Dangerous or negligent acts 2015,Dangerous or negligent acts 2016,Dangerous or negligent acts 2017,Dangerous or negligent acts 2018,Total Dangerous or negligent acts
0,93,119,105,72,54,41,36,28,48,17,56,91,760
1,199,227,154,103,76,76,69,64,47,20,159,161,1355
2,246,152,147,110,92,87,49,52,57,11,213,225,1441
3,95,97,120,66,46,60,43,35,36,10,78,90,776
4,133,126,81,49,57,56,38,29,27,10,103,120,829
5,72,40,36,17,25,16,18,9,11,2,51,53,350
6,183,234,267,155,114,91,88,78,66,24,104,121,1525
7,50,72,50,53,32,37,29,25,28,6,48,44,474
8,68,79,54,47,37,30,23,20,22,3,80,61,524
9,90,104,86,51,63,71,52,36,21,10,95,132,811
10,152,145,98,69,57,79,47,43,48,15,101,168,1022
11,88,103,72,51,40,28,15,19,21,1,65,64,567
12,90,127,92,81,49,59,44,50,42,10,67,74,785
13,182,211,143,95,63,62,46,43,48,11,139,140,1183
14,152,154,123,104,105,78,59,34,46,10,141,149,1155
15,138,132,99,83,51,53,59,41,31,8,117,115,927
16,212,222,163,103,106,73,69,57,53,14,140,179,1391
17,168,203,155,124,90,92,70,79,59,18,92,120,1270
18,112,101,81,46,44,29,30,26,33,6,66,90,664
19,113,113,77,61,39,37,18,29,15,2,82,101,687
20,40,49,49,31,34,24,18,23,17,7,24,39,355
21,125,121,100,110,100,98,67,49,45,6,81,68,970
22,617,475,355,251,207,178,123,120,116,42,345,452,3281
23,162,145,98,74,67,70,67,68,39,8,145,130,1073
24,67,45,56,40,34,27,19,27,31,6,35,37,424
25,60,51,50,45,35,37,18,18,24,7,39,52,436
26,172,193,155,124,91,91,49,63,62,15,72,103,1190
27,174,196,187,174,115,126,110,80,77,14,81,129,1463
28,178,133,145,101,79,68,52,44,32,11,85,101,1029
29,62,52,38,54,39,34,14,14,15,2,37,37,398
30,398,340,305,258,193,157,134,125,114,31,315,429,2799

In [108]:
df3 = df.iloc[:,27:40]

In [110]:
df3.head()

,Kidnapping and related offences 2006,Kidnapping and related offences 2007,Kidnapping and related offences 2008,Kidnapping and related offences 2009,Kidnapping and related offences 2010,Kidnapping and related offences 2011,Kidnapping and related offences 2012,Kidnapping and related offences 2013,Kidnapping and related offences 2014,Kidnapping and related offences 2015,Kidnapping and related offences 2016,Kidnapping and related offences 2017,Kidnapping and related offences 2018
0,1,0,0,1,2,1,1,3,0,4,1,0,0
1,1,1,3,3,1,1,4,4,2,4,1,1,1
2,1,4,3,5,4,1,3,2,2,2,0,1,1
3,0,1,0,0,0,0,0,0,2,0,0,0,0
4,0,1,0,1,2,1,3,0,2,0,0,0,0

In [142]:
df3['Total Kidnapping and related offences'] = df3.sum(axis=1)
df3.head()

,Kidnapping and related offences 2006,Kidnapping and related offences 2007,Kidnapping and related offences 2008,Kidnapping and related offences 2009,Kidnapping and related offences 2010,Kidnapping and related offences 2011,Kidnapping and related offences 2012,Kidnapping and related offences 2013,Kidnapping and related offences 2014,Kidnapping and related offences 2015,Kidnapping and related offences 2016,Kidnapping and related offences 2017,Kidnapping and related offences 2018,Total Kidnapping and related offences
0,1,0,0,1,2,1,1,3,0,4,1,0,0,14
1,1,1,3,3,1,1,4,4,2,4,1,1,1,27
2,1,4,3,5,4,1,3,2,2,2,0,1,1,29
3,0,1,0,0,0,0,0,0,2,0,0,0,0,3
4,0,1,0,1,2,1,3,0,2,0,0,0,0,10

In [111]:
df4 = df.iloc[:,40:52]
df4.head()

,"Robbery, extortion and hijacking offences 2007","Robbery, extortion and hijacking offences 2008","Robbery, extortion and hijacking offences 2009","Robbery, extortion and hijacking offences 2010","Robbery, extortion and hijacking offences 2011","Robbery, extortion and hijacking offences 2012","Robbery, extortion and hijacking offences 2013","Robbery, extortion and hijacking offences 2014","Robbery, extortion and hijacking offences 2015","Robbery, extortion and hijacking offences 2016","Robbery, extortion and hijacking offences 2017","Robbery, extortion and hijacking offences 2018"
0,52,63,68,120,120,93,91,82,61,8,81,80
1,83,84,102,208,171,132,121,131,166,20,98,130
2,145,118,115,245,165,241,186,179,178,36,187,120
3,45,52,31,41,82,55,50,30,29,5,53,47
4,14,20,16,23,19,13,21,24,19,3,40,21

In [145]:
df4['Total Robbery, extortion and hijacking offences'] = df4.sum(axis=1)
df4.head()

,"Robbery, extortion and hijacking offences 2007","Robbery, extortion and hijacking offences 2008","Robbery, extortion and hijacking offences 2009","Robbery, extortion and hijacking offences 2010","Robbery, extortion and hijacking offences 2011","Robbery, extortion and hijacking offences 2012","Robbery, extortion and hijacking offences 2013","Robbery, extortion and hijacking offences 2014","Robbery, extortion and hijacking offences 2015","Robbery, extortion and hijacking offences 2016","Robbery, extortion and hijacking offences 2017","Robbery, extortion and hijacking offences 2018","Total Robbery, extortion and hijacking offences"
0,52,63,68,120,120,93,91,82,61,8,81,80,919
1,83,84,102,208,171,132,121,131,166,20,98,130,1446
2,145,118,115,245,165,241,186,179,178,36,187,120,1915
3,45,52,31,41,82,55,50,30,29,5,53,47,520
4,14,20,16,23,19,13,21,24,19,3,40,21,233

In [112]:
df5 = df.iloc[:,52:64]
df5.head()

,Burglary and related offences 2007,Burglary and related offences 2008,Burglary and related offences 2009,Burglary and related offences 2010,Burglary and related offences 2011,Burglary and related offences 2012,Burglary and related offences 2013,Burglary and related offences 2014,Burglary and related offences 2015,Burglary and related offences 2016,Burglary and related offences 2017,Burglary and related offences 2018
0,218,205,242,217,267,278,248,269,212,32,273,239
1,309,339,311,299,276,212,267,351,269,56,311,318
2,577,700,560,489,579,572,586,531,501,88,663,576
3,240,282,388,354,333,259,243,356,298,50,175,267
4,242,283,210,226,280,268,247,294,291,71,389,314

In [146]:
df5['Total Burglary and related offences'] = df5.sum(axis=1)
df5.head()

,Burglary and related offences 2007,Burglary and related offences 2008,Burglary and related offences 2009,Burglary and related offences 2010,Burglary and related offences 2011,Burglary and related offences 2012,Burglary and related offences 2013,Burglary and related offences 2014,Burglary and related offences 2015,Burglary and related offences 2016,Burglary and related offences 2017,Burglary and related offences 2018,Total Burglary and related offences
0,218,205,242,217,267,278,248,269,212,32,273,239,2700
1,309,339,311,299,276,212,267,351,269,56,311,318,3318
2,577,700,560,489,579,572,586,531,501,88,663,576,6422
3,240,282,388,354,333,259,243,356,298,50,175,267,3245
4,242,283,210,226,280,268,247,294,291,71,389,314,3115

In [115]:
df6 = df.iloc[:,64:76]
df6.head()

,Theft and related offences 2007,Theft and related offences 2008,Theft and related offences 2009,Theft and related offences 2010,Theft and related offences 2011,Theft and related offences 2012,Theft and related offences 2013,Theft and related offences 2014,Theft and related offences 2015,Theft and related offences 2016,Theft and related offences 2017,Theft and related offences 2018
0,721,841,745,851,1030,868,850,864,936,237,860,797
1,4352,4733,4205,4963,4648,4449,5014,5008,5999,1401,4398,3990
2,4001,3952,3674,3712,4595,5751,6511,5952,5613,1330,4191,3769
3,671,656,582,738,851,766,759,669,642,142,701,676
4,713,602,681,712,703,772,755,811,760,182,724,656

In [147]:
df6['Total Theft and related offences'] = df6.sum(axis=1)
df6.head()

,Theft and related offences 2007,Theft and related offences 2008,Theft and related offences 2009,Theft and related offences 2010,Theft and related offences 2011,Theft and related offences 2012,Theft and related offences 2013,Theft and related offences 2014,Theft and related offences 2015,Theft and related offences 2016,Theft and related offences 2017,Theft and related offences 2018,Total Theft and related offences
0,721,841,745,851,1030,868,850,864,936,237,860,797,9600
1,4352,4733,4205,4963,4648,4449,5014,5008,5999,1401,4398,3990,53160
2,4001,3952,3674,3712,4595,5751,6511,5952,5613,1330,4191,3769,53051
3,671,656,582,738,851,766,759,669,642,142,701,676,7853
4,713,602,681,712,703,772,755,811,760,182,724,656,8071

In [116]:
df7 = df.iloc[:,76:88]
df7.head()

,"Fraud, deception and related offences 2007","Fraud, deception and related offences 2008","Fraud, deception and related offences 2009","Fraud, deception and related offences 2010","Fraud, deception and related offences 2011","Fraud, deception and related offences 2012","Fraud, deception and related offences 2013","Fraud, deception and related offences 2014","Fraud, deception and related offences 2015","Fraud, deception and related offences 2016","Fraud, deception and related offences 2017","Fraud, deception and related offences 2018"
0,42,90,52,37,35,46,64,45,65,6,28,32
1,231,203,200,214,214,223,168,175,281,50,168,171
2,459,273,219,263,271,327,247,304,315,105,179,255
3,58,25,38,28,41,56,29,36,26,7,63,24
4,64,64,33,44,44,40,44,51,78,38,35,60

In [148]:
df7['Total Fraud, deception and related offences'] = df7.sum(axis=1)
df7.head()

,"Fraud, deception and related offences 2007","Fraud, deception and related offences 2008","Fraud, deception and related offences 2009","Fraud, deception and related offences 2010","Fraud, deception and related offences 2011","Fraud, deception and related offences 2012","Fraud, deception and related offences 2013","Fraud, deception and related offences 2014","Fraud, deception and related offences 2015","Fraud, deception and related offences 2016","Fraud, deception and related offences 2017","Fraud, deception and related offences 2018","Total Fraud, deception and related offences"
0,42,90,52,37,35,46,64,45,65,6,28,32,542
1,231,203,200,214,214,223,168,175,281,50,168,171,2298
2,459,273,219,263,271,327,247,304,315,105,179,255,3217
3,58,25,38,28,41,56,29,36,26,7,63,24,431
4,64,64,33,44,44,40,44,51,78,38,35,60,595

In [117]:
df8 = df.iloc[:,88:100]
df8.head()

,Controlled drug offences 2007,Controlled drug offences 2008,Controlled drug offences 2009,Controlled drug offences 2010,Controlled drug offences 2011,Controlled drug offences 2012,Controlled drug offences 2013,Controlled drug offences 2014,Controlled drug offences 2015,Controlled drug offences 2016,Controlled drug offences 2017,Controlled drug offences 2018
0,128,134,182,165,134,160,141,272,412,95,116,146
1,319,351,460,471,378,557,567,1336,926,180,262,295
2,449,506,545,356,294,206,215,476,448,111,217,313
3,88,101,108,93,72,64,56,69,72,18,123,62
4,77,75,100,71,33,28,34,61,67,11,39,26

In [149]:
df8['Total Controlled drug offences '] = df8.sum(axis=1)
df8.head()

,Controlled drug offences 2007,Controlled drug offences 2008,Controlled drug offences 2009,Controlled drug offences 2010,Controlled drug offences 2011,Controlled drug offences 2012,Controlled drug offences 2013,Controlled drug offences 2014,Controlled drug offences 2015,Controlled drug offences 2016,Controlled drug offences 2017,Controlled drug offences 2018,Total Controlled drug offences
0,128,134,182,165,134,160,141,272,412,95,116,146,2085
1,319,351,460,471,378,557,567,1336,926,180,262,295,6102
2,449,506,545,356,294,206,215,476,448,111,217,313,4136
3,88,101,108,93,72,64,56,69,72,18,123,62,926
4,77,75,100,71,33,28,34,61,67,11,39,26,622

In [118]:
df9 = df.iloc[:,100:112]
df9.head()

,Weapons and Explosives Offences 2007,Weapons and Explosives Offences 2008,Weapons and Explosives Offences 2009,Weapons and Explosives Offences 2010,Weapons and Explosives Offences 2011,Weapons and Explosives Offences 2012,Weapons and Explosives Offences 2013,Weapons and Explosives Offences 2014,Weapons and Explosives Offences 2015,Weapons and Explosives Offences 2016,Weapons and Explosives Offences 2017,Weapons and Explosives Offences 2018
0,50,60,63,95,75,45,45,39,32,10,34,73
1,132,147,118,155,145,118,122,109,108,27,99,127
2,93,121,132,145,125,101,72,122,119,33,57,94
3,22,28,33,33,21,10,13,13,11,1,13,20
4,15,15,21,29,12,13,16,11,15,2,14,13

In [150]:
df9['Total Weapons and Explosives Offences '] = df9.sum(axis=1)
df9.head()

,Weapons and Explosives Offences 2007,Weapons and Explosives Offences 2008,Weapons and Explosives Offences 2009,Weapons and Explosives Offences 2010,Weapons and Explosives Offences 2011,Weapons and Explosives Offences 2012,Weapons and Explosives Offences 2013,Weapons and Explosives Offences 2014,Weapons and Explosives Offences 2015,Weapons and Explosives Offences 2016,Weapons and Explosives Offences 2017,Weapons and Explosives Offences 2018,Total Weapons and Explosives Offences
0,50,60,63,95,75,45,45,39,32,10,34,73,621
1,132,147,118,155,145,118,122,109,108,27,99,127,1407
2,93,121,132,145,125,101,72,122,119,33,57,94,1214
3,22,28,33,33,21,10,13,13,11,1,13,20,218
4,15,15,21,29,12,13,16,11,15,2,14,13,176

In [119]:
df10 = df.iloc[:,112:124]
df10.head()

,Damage to property and to the environment 2007,Damage to property and to the environment 2008,Damage to property and to the environment 2009,Damage to property and to the environment 2010,Damage to property and to the environment 2011,Damage to property and to the environment 2012,Damage to property and to the environment 2013,Damage to property and to the environment 2014,Damage to property and to the environment 2015,Damage to property and to the environment 2016,Damage to property and to the environment 2017,Damage to property and to the environment 2018
0,359,464,398,393,493,352,338,288,291,57,394,386
1,572,672,737,660,619,504,386,513,582,100,508,486
2,613,584,539,592,585,528,428,458,458,124,484,549
3,343,327,367,294,265,219,231,229,175,43,470,511
4,251,219,230,206,192,160,171,137,124,41,241,260

In [151]:
df10['Total Damage to property and to the environment '] = df10.sum(axis=1)
df10.head()

,Damage to property and to the environment 2007,Damage to property and to the environment 2008,Damage to property and to the environment 2009,Damage to property and to the environment 2010,Damage to property and to the environment 2011,Damage to property and to the environment 2012,Damage to property and to the environment 2013,Damage to property and to the environment 2014,Damage to property and to the environment 2015,Damage to property and to the environment 2016,Damage to property and to the environment 2017,Damage to property and to the environment 2018,Total Damage to property and to the environment
0,359,464,398,393,493,352,338,288,291,57,394,386,4213
1,572,672,737,660,619,504,386,513,582,100,508,486,6339
2,613,584,539,592,585,528,428,458,458,124,484,549,5942
3,343,327,367,294,265,219,231,229,175,43,470,511,3474
4,251,219,230,206,192,160,171,137,124,41,241,260,2232

In [120]:
df11 = df.iloc[:,124:136]
df11.head()

,Public order and other social code offences 2007,Public order and other social code offences 2008,Public order and other social code offences 2009,Public order and other social code offences 2010,Public order and other social code offences 2011,Public order and other social code offences 2012,Public order and other social code offences 2013,Public order and other social code offences 2014,Public order and other social code offences 2015,Public order and other social code offences 2016,Public order and other social code offences 2017,Public order and other social code offences 2018
0,420,498,442,355,279,271,209,214,226,49,383,477
1,1854,2444,1564,1512,1654,1329,1181,1027,3265,432,3021,2174
2,2553,2960,2380,2520,2851,2167,1795,1967,2510,528,2839,2616
3,298,379,342,276,196,135,116,110,96,16,257,258
4,312,347,300,275,262,208,178,187,168,30,350,368

In [152]:
df11['Total Public order and other social code offences '] = df11.sum(axis=1)
df11.head()

,Public order and other social code offences 2007,Public order and other social code offences 2008,Public order and other social code offences 2009,Public order and other social code offences 2010,Public order and other social code offences 2011,Public order and other social code offences 2012,Public order and other social code offences 2013,Public order and other social code offences 2014,Public order and other social code offences 2015,Public order and other social code offences 2016,Public order and other social code offences 2017,Public order and other social code offences 2018,Total Public order and other social code offences
0,420,498,442,355,279,271,209,214,226,49,383,477,3823
1,1854,2444,1564,1512,1654,1329,1181,1027,3265,432,3021,2174,21457
2,2553,2960,2380,2520,2851,2167,1795,1967,2510,528,2839,2616,27686
3,298,379,342,276,196,135,116,110,96,16,257,258,2479
4,312,347,300,275,262,208,178,187,168,30,350,368,2985

In [155]:
df12 = df.iloc[:,136:148]
df12.head()

,"Offences against government, justice procedures and organisation of crime 2007","Offences against government, justice procedures and organisation of crime 2008","Offences against government, justice procedures and organisation of crime 2009","Offences against government, justice procedures and organisation of crime 2010","Offences against government, justice procedures and organisation of crime 2011","Offences against government, justice procedures and organisation of crime 2012","Offences against government, justice procedures and organisation of crime 2013","Offences against government, justice procedures and organisation of crime 2014","Offences against government, justice procedures and organisation of crime 2015","Offences against government, justice procedures and organisation of crime 2016","Offences against government, justice procedures and organisation of crime 2017","Offences against government, justice procedures and organisation of crime 2018"
0,73,29,18,17,17,6,8,12,7,4,67,63
1,413,375,110,57,54,33,39,25,32,4,226,491
2,107,162,273,110,139,132,88,107,78,14,151,193
3,24,21,16,4,8,10,17,14,10,1,36,48
4,19,13,10,14,3,7,5,4,8,1,29,26

In [156]:
df12['Total Offences against government, justice procedures and organisation of crime '] = df12.sum(axis=1)
df12.head()

,"Offences against government, justice procedures and organisation of crime 2007","Offences against government, justice procedures and organisation of crime 2008","Offences against government, justice procedures and organisation of crime 2009","Offences against government, justice procedures and organisation of crime 2010","Offences against government, justice procedures and organisation of crime 2011","Offences against government, justice procedures and organisation of crime 2012","Offences against government, justice procedures and organisation of crime 2013","Offences against government, justice procedures and organisation of crime 2014","Offences against government, justice procedures and organisation of crime 2015","Offences against government, justice procedures and organisation of crime 2016","Offences against government, justice procedures and organisation of crime 2017","Offences against government, justice procedures and organisation of crime 2018","Total Offences against government, justice procedures and organisation of crime"
0,73,29,18,17,17,6,8,12,7,4,67,63,321
1,413,375,110,57,54,33,39,25,32,4,226,491,1859
2,107,162,273,110,139,132,88,107,78,14,151,193,1554
3,24,21,16,4,8,10,17,14,10,1,36,48,209
4,19,13,10,14,3,7,5,4,8,1,29,26,139

In [209]:
#t_d = pd.concat([test,test_1],axis=1)
crime_data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12],axis=1)

In [210]:
crime_data.head()

,Area_code,Station,Divisions,"Attempts or threats to murder, assaults, harassments and related offences 2007","Attempts or threats to murder, assaults, harassments and related offences 2008","Attempts or threats to murder, assaults, harassments and related offences 2009","Attempts or threats to murder, assaults, harassments and related offences 2010","Attempts or threats to murder, assaults, harassments and related offences 2011","Attempts or threats to murder, assaults, harassments and related offences 2012","Attempts or threats to murder, assaults, harassments and related offences 2013",...,"Offences against government, justice procedures and organisation of crime 2010","Offences against government, justice procedures and organisation of crime 2011","Offences against government, justice procedures and organisation of crime 2012","Offences against government, justice procedures and organisation of crime 2013","Offences against government, justice procedures and organisation of crime 2014","Offences against government, justice procedures and organisation of crime 2015","Offences against government, justice procedures and organisation of crime 2016","Offences against government, justice procedures and organisation of crime 2017","Offences against government, justice procedures and organisation of crime 2018","Total Offences against government, justice procedures and organisation of crime"
0,D01,Fitzgibbon Street,D.M.R. North Central Division,130,161,128,117,147,130,109,...,17,17,6,8,12,7,4,67,63,321
1,D01,Store Street,D.M.R. North Central Division,279,284,270,313,338,289,304,...,57,54,33,39,25,32,4,226,491,1859
2,D02,Pearse Street,D.M.R. South Central Division,525,538,446,521,551,451,481,...,110,139,132,88,107,78,14,151,193,1554
3,D03,Clontarf,D.M.R. Northern Division,93,113,131,86,53,74,60,...,4,8,10,17,14,10,1,36,48,209
4,D04,Donnybrook,D.M.R. South Central Division,67,77,91,71,45,41,41,...,14,3,7,5,4,8,1,29,26,139

In [211]:
#t_d = t_d.loc[:,['e','k']]
crime_data = crime_data.loc[:,['Area_code','Station','Total Attempts or threats to murder, assaults, harassments and related offences',
                                     'Total Dangerous or negligent acts',
                                     'Total Kidnapping and related offences',
                                     'Total Robbery, extortion and hijacking offences',
                                     'Total Burglary and related offences',
                                     'Total Theft and related offences','Total Fraud, deception and related offences',
                              'Total Controlled drug offences ','Total Weapons and Explosives Offences ',
                              'Total Damage to property and to the environment ','Total Public order and other social code offences ',
                              'Total Offences against government, justice procedures and organisation of crime ']]

In [212]:
crime_data.to_excel(r'E:/MCM/Practicum docs/Final_documents/datasets/crime_data.xlsx', index = False)